### ISSUE TITLE
use of R2RML predicateMaps throws error

### ISSUE THREAD

**Issue by PaulZH** [ontop/ontop#107]
My R2RML mapping works as long as I do not include predicateMaps.
When adding the second predicateObjectMap with a predicateMap I get the error below.

```
<ActivityMapping>
  a rr:TriplesMap;
  rr:logicalTable [ rr:tableName "activity" ];
  rr:subjectMap [
    rr:template "http://data.kbodata.be/organisation/{EntityNumber}#id";
    rr:class org:FormalOrganization;
    rr:termType rr:IRI 
  ];

 rr:predicateObjectMap [
    rr:predicate rov:orgActivity;
    rr:objectMap [
    rr:template "http://id.fedstats.be/nace{NaceVersion}/{NaceCode}#id";
    rr:termType rr:IRI
    ]
   ];

 rr:predicateObjectMap [
    rr:predicateMap 
    [
    rr:template "http://data.kbodata.be/def#{Classification}";
    rr:termType rr:IRI
    ];
    rr:objectMap [
    rr:template "http://id.fedstats.be/nace{NaceVersion}/{NaceCode}#id";
    rr:termType rr:IRI
    ]
   ];  

.
```

Error

```
Error during r2rml import. 

java.lang.RuntimeException: java.lang.NullPointerException
    at it.unibz.krdb.obda.r2rml.R2RMLManager.getMappings(R2RMLManager.java:131)
    at it.unibz.krdb.obda.r2rml.R2RMLReader.readMappings(R2RMLReader.java:110)
    at org.semanticweb.ontop.protege.gui.action.R2RMLImportAction.actionPerformed(R2RMLImportAction.java:95)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
    at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)
    at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
    at java.awt.MenuItem.processEvent(MenuItem.java:628)
    at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
    at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:754)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:702)
    at java.awt.EventQueue$3.run(EventQueue.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:724)
    at java.awt.EventQueue$4.run(EventQueue.java:722)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
    at it.unibz.krdb.obda.model.impl.PredicateImpl.<init>(PredicateImpl.java:36)
    at it.unibz.krdb.obda.model.impl.OBDADataFactoryImpl.getPredicate(OBDADataFactoryImpl.java:92)
    at it.unibz.krdb.obda.model.impl.OBDADataFactoryImpl.getPredicate(OBDADataFactoryImpl.java:37)
    at it.unibz.krdb.obda.r2rml.R2RMLParser.getBodyPredicates(R2RMLParser.java:221)
    at it.unibz.krdb.obda.r2rml.R2RMLManager.getMappingTripleAtoms(R2RMLManager.java:254)
    at it.unibz.krdb.obda.r2rml.R2RMLManager.getMapping(R2RMLManager.java:144)
    at it.unibz.krdb.obda.r2rml.R2RMLManager.getMappings(R2RMLManager.java:117)
    ... 30 more
```

**Comment by skomlaebri** [comment]
Hi, 
thanks for reporting the problem, there is indeed a bug with predicate map having a template, after a predicate map having a constant value.

**Comment by gesteban** [comment]
Hi, I'm doing some testing in Protégé and this bug keep happening to me (predicate template leads to error).

This is the map I'm using:
`<#just_a_map_five>
	a rr:TriplesMap;
	rr:logicalTable [
		rr:tableSchema "DB";
		rr:tableOwner "TEST";
		rr:tableName "SG_TABLE_ONE"
	];
	rr:subjectMap [
		rr:termType rr:IRI;
		rr:template "http://example.org/test/id-{ID}";
		rr:graph <http://example.org/test>
	];
	rr:predicateObjectMap [
		rr:predicateMap [
			rr:template "http://example.org/{NAME}";
			rr:termType rr:IRI
		];
		rr:objectMap [ rr:column "NAME" ];
	].`

With the error message in Protégé (version 1.18.1) while starting reasoner:
`Level:       ERROR
Time:        1507109491276
Message:     An error occurred during reasoning: it.unibz.inf.ontop.model.OBDAException: java.lang.IllegalArgumentException: There was an error analyzing the following mappings. Please correct the issue(s) to continue.
Error in mapping with id: urn:mapping--1949017033#3af50fca09674ca596650599d5cc7404 
 Description: Error in identifying column name "NAME", please check the query source in the mappings.
Possible reasons:
1. The name is ambiguous, or
2. The name is not defined in the database schema.
{"ID"=t0, VIEW_0."ID"=t0} 
Mapping: [SELECT DISTINCT SG_TABLE_ONE."ID" FROM SG_TABLE_ONE WHERE SG_TABLE_ONE."NAME" = 'S030500' ==> [http://example.org/S030500(URI("http://example.org/test/id-{}",ID),NAME)]]`

Still don't know if I'm doing something wrong or it's not been fixed. Tested in both 1.18.1 and 3.0.0. In the 3.0.0 version it throws a NullPointerException while adding the mapping.

**Comment by kontchakov** [comment]
Hi Guillermo

I have a strong suspicion that the error message is generated by another mapping (the string ‘S030500’ does not appear in the <#just_a_map_five>).

On another note, do not use “DISTINCT” in mapping queries; and rr:tableOwner/rr:tableSchema are not part of R2RML - use TEST.DB.SG_TABLE_ONE in rr:tableName instead.

Best
Roman

**Comment by gesteban** [comment]
The string 'S030500' is in the database, not the mapping. I'm testing one mapping each time.

The translation of the R2RML mapping to Ontop is:
```
target		<http://example.org/test/id-{ID}> <http://example.org/{NAME}> {NAME} . 
source		SELECT * FROM SG_TABLE_ONE
```

**Comment by skomlaebri** [comment]
Hi @gesteban 
It's a different issue unrelated to the one reported by Paul, here the translation from r2rml to obda is correct. The bug is due to the way we handle [MetaMapping](https://github.com/ontop/ontop/wiki/MetaMapping). The use of the column name both inside the predicate and the target is creating a problem at the moment. We are working on the fix. We generally discourage the use of dynamically created properties for performance reasons.

**Comment by gesteban** [comment]
I'm not comfortable with using dynamic properties cause it means we will have a partially dynamic ontology, but the database we are working with gives us no other option to properly describe the data :expressionless:  Thank you @skomlaebri.

**Comment by kontchakov** [comment]
Fixed in version 4.
