### ISSUE TITLE
error while loading ontologies from file in Protégé-ontop

### ISSUE THREAD

**Issue by PaulZH** [ontop/ontop#108]
Loading w3c's org and regorg vocabs in Protégé-ontop from local file system.

I get
```
An exception has occurred when loading input file.
Message: URI scheme is not "file"

###################################################
##    Debugging information (for the authors)    ##
###################################################

	at org.semanticweb.ontop.protege.core.OBDAModelManager$OBDAPluginOWLModelManagerListener.handleOntologyLoadedAndReLoaded(OBDAModelManager.java:579)
	at org.semanticweb.ontop.protege.core.OBDAModelManager$OBDAPluginOWLModelManagerListener.handleChange(OBDAModelManager.java:453)
	at org.protege.editor.owl.model.OWLModelManagerImpl.fireEvent(OWLModelManagerImpl.java:791)
	at org.protege.editor.owl.ui.ontology.imports.OntologyImportsList.handleAdd(OntologyImportsList.java:116)
	at org.protege.editor.core.ui.list.MList.lambda$new$5(MList.java:37)
	at org.protege.editor.core.ui.list.MList$$Lambda$59/1170462719.actionPerformed(Unknown Source)
	at org.protege.editor.core.ui.list.MList.handleMouseClick(MList.java:198)
	at org.protege.editor.core.ui.list.MList.access$200(MList.java:19)
	at org.protege.editor.core.ui.list.MList$3.mouseReleased(MList.java:96)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
Although the ontology seems to be imported correctly.

**Comment by skomlaebri** [comment]
Fixed in 5049cbc6c23e34a57776010af64eaef206569290. 
Add classes and properties of imported ontologies at runtime
