### ISSUE TITLE
NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering

### ISSUE THREAD

**Issue by JensPiegsa** [ontop/ontop#117]
Using Ontop with bundled Jetty from [here](https://sourceforge.net/projects/ontop4obda/files/ontop-1.17.0/ontop-jetty-bundle-1.17.0.zip/download) I ran into the following error while trying to create a test repository:

> http://localhost:8080/openrdf-workbench/repositories/NONE/create

## HTTP ERROR 500

Problem accessing /openrdf-workbench/repositories/NONE/create. Reason:

    com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z

### Caused by:

```
java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:445)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:366)
	at com.github.jsonldjava.utils.JsonUtils.<clinit>(JsonUtils.java:37)
	at com.github.jsonldjava.sesame.SesameJSONLDParser.parse(SesameJSONLDParser.java:88)
	at org.semanticweb.owlapi.rio.RioParserImpl.parseDocumentSource(RioParserImpl.java:250)
	at org.semanticweb.owlapi.rio.RioParserImpl.parse(RioParserImpl.java:191)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:212)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1035)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:979)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:990)
	at it.unibz.krdb.obda.owlrefplatform.questdb.QuestDBVirtualStore.getOntologyFromFile(QuestDBVirtualStore.java:248)
	at it.unibz.krdb.obda.owlrefplatform.questdb.QuestDBVirtualStore.<init>(QuestDBVirtualStore.java:164)
	at it.unibz.krdb.obda.owlrefplatform.questdb.QuestDBVirtualStore.<init>(QuestDBVirtualStore.java:97)
	at sesameWrapper.SesameVirtualRepo.createRepo(SesameVirtualRepo.java:181)
	at sesameWrapper.SesameVirtualRepo.<init>(SesameVirtualRepo.java:57)
	at sesameWrapper.SesameRepositoryConfig.buildRepository(SesameRepositoryConfig.java:259)
	at sesameWrapper.SesameRepositoryConfig.validate(SesameRepositoryConfig.java:170)
	at org.openrdf.repository.config.RepositoryConfig.validate(RepositoryConfig.java:123)
	at org.openrdf.workbench.commands.CreateServlet.updateRepositoryConfig(CreateServlet.java:145)
	at org.openrdf.workbench.commands.CreateServlet.createRepositoryConfig(CreateServlet.java:130)
	at org.openrdf.workbench.commands.CreateServlet.doPost(CreateServlet.java:75)
	at org.openrdf.workbench.base.TransformationServlet.service(TransformationServlet.java:106)
	at org.openrdf.workbench.base.BaseServlet.service(BaseServlet.java:136)
	at org.openrdf.workbench.proxy.ProxyRepositoryServlet.service(ProxyRepositoryServlet.java:104)
	at org.openrdf.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:222)
	at org.openrdf.workbench.proxy.WorkbenchServlet.handleRequest(WorkbenchServlet.java:151)
	at org.openrdf.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:119)
	at org.openrdf.workbench.proxy.WorkbenchGateway.service(WorkbenchGateway.java:131)
	at org.openrdf.workbench.base.BaseServlet.service(BaseServlet.java:136)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:669)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1448)
	at org.openrdf.workbench.proxy.CookieCacheControlFilter.doFilter(CookieCacheControlFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:368)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:488)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:943)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1004)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:861)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Unknown Source)
```

#### Steps:

* `ontop mapping to-obda --input test_r2rml.ttl --output test.obda`
* test.obda and test.owl stored in `jetty-distribution-8.1.9\`
* Set JETTY_HOME
* Run `java -jar start.jar`
* `http://localhost:8080/openrdf-workbench/` > New repository
	* Type: Ontop Virtual RDF Store
	* ID: test
	* Title: test
	* OWL file: test.owl
	* OBDA file: test.obda
	* Create ...

Is this a dependency issue? Any hints?

**Comment by JensPiegsa** [comment]
Ok, this seemed to be caused by a syntax error on my side.
