### ISSUE TITLE
ontocli

### ISSUE THREAD

**Issue by bertvannuffelen** [ontop/ontop#127]
Dear,

when starting the commandline with empty value for -m 
an exeception is thrown.

Can one please provide proper error messages?

kr,

Bert

**Comment by bertvannuffelen** [comment]
exammple
 ./ontop  bootstrap -m 

com.github.rvesse.airline.parser.errors.ParseOptionMissingValueException: Required values for option 'mappingFile' not provided
	at com.github.rvesse.airline.restrictions.global.NoMissingOptionValuesRestriction.validate(NoMissingOptionValuesRestriction.java:28)
	at com.github.rvesse.airline.parser.command.CliParser.validate(CliParser.java:98)
	at com.github.rvesse.airline.parser.command.CliParser.parse(CliParser.java:54)
	at com.github.rvesse.airline.Cli.parse(Cli.java:75)
	at com.github.rvesse.airline.Cli.parse(Cli.java:70)
	at it.unibz.inf.ontop.cli.Ontop.main(Ontop.java:20)
