### ISSUE TITLE
Select * queries when using Teiid

### ISSUE THREAD

**Issue by martinrezk** [ontop/ontop#13]
When using teid, if one writes a query in the mapping of the form

select \* from tb_books

It gives the following error:

Quest was not initialized properly. This is generally indicates, connection problems or error during ontology or mapping pre-processing. 

Original error message:
org.teiid.jdbc.TeiidSQLException: Remote org.teiid.api.exception.query.QueryParserException: TEIID31100 Parsing error: Encountered "tb_books) view20130219 [_]null[_]" at line 1, column 53.
Was expecting: <EOF> | "cross" | "except" | "fetch" | "full" | "group" | "having" | "inner" | "intersect" | "join" ...
###### 
###### 

```
at it.unibz.krdb.obda.owlrefplatform.core.Quest.setupRepository(Quest.java:938)
at it.unibz.krdb.obda.owlrefplatform.owlapi3.QuestOWL.prepareQuestInstance(QuestOWL.java:244)
at it.unibz.krdb.obda.owlrefplatform.owlapi3.QuestOWL.prepareReasoner(QuestOWL.java:418)
at it.unibz.krdb.obda.owlrefplatform.owlapi3.QuestOWL.<init>(QuestOWL.java:173)
at it.unibz.krdb.obda.owlrefplatform.owlapi3.QuestOWLFactory.createReasoner(QuestOWLFactory.java:112)
at org.protege.editor.owl.model.inference.ReasonerUtilities.createReasoner(ReasonerUtilities.java:21)
at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.ensureRunningReasonerInitialized(OWLReasonerManagerImpl.java:398)
at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.run(OWLReasonerManagerImpl.java:354)
at java.lang.Thread.run(Thread.java:722)
```

**Comment by seralf** [comment]
Hi I had a similar problem using Impala, I suppose it can be relates to the lack of metadata: maybe the actual engine executing the query (behind teiid) is unable to provide explicit metadata when the projection is declared as `*` ? just an idea...
