### ISSUE TITLE
connecting to MS SQL server: generated SQL not compatible?

### ISSUE THREAD

**Issue by PaulZH** [ontop/ontop#131]
Latest version used from Protégé-bundled
jdbc connection tested: OK
importing R2RML: OK
starting reasoner: OK
doing a query:
```
SELECT ?x
WHERE {?x ?y ?z.}
LIMIT 5
```
Error thrown:
```
it.unibz.inf.ontop.model.OBDAException: Error executing SQL query: 
Incorrect syntax near '`'.
SQL query:
 SELECT *
FROM (
SELECT 
   1 AS `xQuestType`, NULL AS `xLang`, CONCAT('http://id.vlaanderen.be/id/adres/', REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CAST(QVIEW1."AdresID" AS CHAR(8000) CHARACTER SET utf8), ' ', '%20'), '!', '%21'), '''', '%22'), '#', '%23'), '$', '%24'), '&', '%26'), '(', '%28'), ')', '%29'), '*', '%2A'), '+', '%2B'), ',', '%2C'), '/', '%2F'), ':', '%3A'), ';', '%3B'), '=', '%3D'), '?', '%3F'), '@', '%40'), '[', '%5B'), ']', '%5D'), '#id') AS `x`
 FROM 
"dbo"."Adres" QVIEW1
WHERE 
QVIEW1."AdresID" IS NOT NULL
) SUB_QVIEW
LIMIT 5
```
The same done using MySQL: OK

**Comment by skomlaebri** [comment]
Hi,
it seems to be a problem related to the jdbc driver. Are you using the standard sql driver com.microsoft.sqlserver.jdbc.SQLServerDriver ?
In the SQL query the reasoner seems like it is still using the syntax for the mysql driver.

**Comment by PaulZH** [comment]
I have in my [SourceDeclaration]
sourceUri	datasource1
driverClass	com.microsoft.sqlserver.jdbc.SQLServerDriver
And I get now a different SQL dialect meaning my config was obviously wrong.
But with the corrections made I still get errors:

```
it.unibz.inf.ontop.owlapi.OntopOWLException: it.unibz.inf.ontop.model.OBDAException: Error executing SQL query: 
Incorrect syntax near 'OFFSET'.
SQL query:
 SELECT *
FROM (
SELECT 
   1 AS "xQuestType", NULL AS "xLang", (CAST ('http://id.vlaanderen.be/id/adres/' as varchar(8000)) + CAST(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CAST(QVIEW1."AdresID" AS VARCHAR(8000)), ' ', '%20'), '!', '%21'), '''', '%22'), '#', '%23'), '$', '%24'), '&', '%26'), '(', '%28'), ')', '%29'), '*', '%2A'), '+', '%2B'), ',', '%2C'), '/', '%2F'), ':', '%3A'), ';', '%3B'), '=', '%3D'), '?', '%3F'), '@', '%40'), '[', '%5B'), ']', '%5D') as varchar(8000)) + CAST('#id' as varchar(8000))) AS "x"
 FROM 
"dbo"."Adres" QVIEW1
WHERE 
QVIEW1."AdresID" IS NOT NULL
UNION ALL
SELECT 
   1 AS "xQuestType", NULL AS "xLang", (CAST ('http://id.vlaanderen.be/id/adres/' as varchar(8000)) + CAST(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CAST(QVIEW1."AdresID" AS VARCHAR(8000)), ' ', '%20'), '!', '%21'), '''', '%22'), '#', '%23'), '$', '%24'), '&', '%26'), '(', '%28'), ')', '%29'), '*', '%2A'), '+', '%2B'), ',', '%2C'), '/', '%2F'), ':', '%3A'), ';', '%3B'), '=', '%3D'), '?', '%3F'), '@', '%40'), '[', '%5B'), ']', '%5D') as varchar(8000)) + CAST('#id' as varchar(8000))) AS "x"
 FROM 
"dbo"."Adres" QVIEW1
WHERE 
QVIEW1."AdresID" IS NOT NULL
) SUB_QVIEW
OFFSET 0 ROWS
FETCH NEXT 5 ROWS ONLY

	at it.unibz.inf.ontop.owlrefplatform.owlapi.QuestOWLStatement.executeTuple(QuestOWLStatement.java:109) ~[na:na]
	at it.unibz.inf.ontop.protege.views.QueryInterfaceView$2.executeQuery(QueryInterfaceView.java:194) ~[na:na]
	at it.unibz.inf.ontop.protege.views.QueryInterfaceView$2.executeQuery(QueryInterfaceView.java:161) ~[na:na]
	at it.unibz.inf.ontop.protege.gui.action.OBDADataQueryAction$1.run(OBDADataQueryAction.java:152) ~[na:na]

```

**Comment by ghxiao** [comment]
Hi @PaulZH ,

It seems Ontop is getting confused about which DB engine is connecting to.

Can you provide the the following information:

- the version of MS SQL Server
- the JDBC driver of SQLSever and version
- what is your JDBC url

**Comment by skomlaebri** [comment]
Hi,
the problem seems to be related to our sql translation of limit in sql server.
You can temporary fix the issue adding order by to your SPARQL query.
So for example:
```
SELECT ?x
WHERE {?x a :Person.}
ORDER BY ?x
LIMIT 5
```

**Comment by PaulZH** [comment]
Thanks for the workaround.
