### ISSUE TITLE
Test ontop-cli with SQLite

### ISSUE THREAD

**Issue by arnikz** [ontop/ontop#134]
Hi,

This issue is related to #133. Similarly, the onto-cli + SQLite combination does not work for me.
I've added the sqlite-jdbc driver to CLASSPATH and executed the following command:
```
export CLASSPATH=$CLASSPATH:/jdbc/*
java -jar ontop-cli-1.18.0.jar query \
-d org.sqlite.JDBC \
-m person_r2rml.ttl \
-q query_01.q \
-l jdbc:sqlite:/onto-example/person.db \
-o person.txt \
-u dummy -p dummy
```
Note: onto-cli complains if no values provided for -u and -p options. However, SQLite does not implement/use username/passwd parameters.

Here is the log:
14:42:01.984 [main] DEBUG i.u.i.ontop.model.impl.OBDAModelImpl - OBDA model is initialized!
14:42:02.069 [main] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.semanticweb.owlapi.rio.RioFunctionalSyntaxParserFactory
14:42:02.073 [main] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.semanticweb.owlapi.rio.RioManchesterSyntaxParserFactory
14:42:02.074 [main] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.semanticweb.owlapi.rio.RioOWLXMLParserFactory
14:42:02.078 [main] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.binary.BinaryRDFParserFactory
14:42:02.081 [main] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.nquads.NQuadsParserFactory
14:42:02.084 [main] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.rdfjson.RDFJSONParserFactory
14:42:02.086 [main] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.trix.TriXParserFactory
14:42:02.088 [main] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.trig.TriGParserFactory
14:42:02.089 [main] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class com.github.jsonldjava.sesame.SesameJSONLDParserFactory
14:42:02.092 [main] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.semarglproject.sesame.rdf.rdfa.SesameRDFaParserFactory
14:42:02.094 [main] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.turtle.TurtleParserFactory
14:42:02.096 [main] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.rdfxml.RDFXMLParserFactory
14:42:02.098 [main] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.n3.N3ParserFactory
14:42:02.100 [main] DEBUG org.openrdf.rio.RDFParserRegistry - Registered service class org.openrdf.rio.ntriples.NTriplesParserFactory
14:42:02.148 [main] DEBUG o.o.rio.DatatypeHandlerRegistry - Registered service class org.openrdf.rio.datatypes.XMLSchemaDatatypeHandler
14:42:02.149 [main] DEBUG o.o.rio.DatatypeHandlerRegistry - Registered service class org.openrdf.rio.datatypes.RDFDatatypeHandler
14:42:02.150 [main] DEBUG o.o.rio.DatatypeHandlerRegistry - Registered service class org.openrdf.rio.datatypes.DBPediaDatatypeHandler
14:42:02.151 [main] DEBUG o.o.rio.DatatypeHandlerRegistry - Registered service class org.openrdf.rio.datatypes.VirtuosoGeometryDatatypeHandler
14:42:02.151 [main] DEBUG o.o.rio.DatatypeHandlerRegistry - Registered service class org.openrdf.rio.datatypes.GeoSPARQLDatatypeHandler
14:42:02.154 [main] DEBUG o.o.rio.LanguageHandlerRegistry - Registered service class org.openrdf.rio.languages.RFC3066LanguageHandler
14:42:02.266 [main] DEBUG i.u.i.ontop.model.impl.OBDAModelImpl - OBDA model is initialized!
14:42:02.269 [main] DEBUG i.u.i.o.o.owlapi3.QuestOWL - Load ontologies called. Translating ontologies.
14:42:02.271 [main] DEBUG i.u.i.o.o.OWLAPITranslatorUtility - Load ontologies called. Translating 1 ontologies.
14:42:02.287 [main] DEBUG i.u.i.o.o.OWLAPITranslatorUtility - Ontology loaded: [Ontology info. Axioms: 0 Classes: 2 Object Properties: 2 Data Properties: 2 Annotation Properties: 0]
14:42:02.290 [main] DEBUG i.u.i.o.o.owlapi3.QuestOWL - Initializing a new Quest instance...
14:42:02.301 [main] DEBUG i.u.i.o.owlrefplatform.core.Quest - Quest configuration:
14:42:02.301 [main] DEBUG i.u.i.o.owlrefplatform.core.Quest - Extensional query rewriting enabled: false
14:42:02.301 [main] DEBUG i.u.i.o.owlrefplatform.core.Quest - Optimize TBox using class/property equivalences: true
14:42:02.301 [main] DEBUG i.u.i.o.owlrefplatform.core.Quest - ABox mode: virtual
14:42:02.301 [main] DEBUG i.u.i.ontop.model.impl.OBDAModelImpl - OBDA model is initialized!
14:42:02.302 [main] DEBUG i.u.i.o.owlrefplatform.core.Quest - Initializing Quest...
14:42:02.326 [main] DEBUG i.u.i.o.owlrefplatform.core.Quest - Testing DB connection...
14:42:02.328 [main] DEBUG i.u.i.o.owlrefplatform.core.Quest - null
14:42:02.328 [main] ERROR i.u.i.o.o.owlapi3.QuestOWL - Could not initialize the Quest query answering engine. Answering queries will not be available.
14:42:02.335 [main] ERROR i.u.i.o.o.owlapi3.QuestOWL - java.sql.SQLException: No suitable driver found for jdbc:sqlite:/ontop-example/person.db
it.unibz.inf.ontop.model.OBDAException: java.sql.SQLException: No suitable driver found for jdbc:sqlite:/ontop-example/person.db
	at it.unibz.inf.ontop.owlrefplatform.core.Quest.setupRepository(Quest.java:661) ~[ontop-reformulation-core-1.18.0.jar:1.18.0]
	at it.unibz.inf.ontop.owlrefplatform.owlapi3.QuestOWL.prepareQuestInstance(QuestOWL.java:271) [ontop-quest-owlapi-1.18.0.jar:1.18.0]
	at it.unibz.inf.ontop.owlrefplatform.owlapi3.QuestOWL.prepareReasoner(QuestOWL.java:452) [ontop-quest-owlapi-1.18.0.jar:1.18.0]
	at it.unibz.inf.ontop.owlrefplatform.owlapi3.QuestOWL.init(QuestOWL.java:148) [ontop-quest-owlapi-1.18.0.jar:1.18.0]
	at it.unibz.inf.ontop.owlrefplatform.owlapi3.QuestOWL.<init>(QuestOWL.java:174) [ontop-quest-owlapi-1.18.0.jar:1.18.0]
	at it.unibz.inf.ontop.owlrefplatform.owlapi3.QuestOWLFactory.createReasoner(QuestOWLFactory.java:107) [ontop-quest-owlapi-1.18.0.jar:1.18.0]
	at it.unibz.inf.ontop.cli.OntopQuery.run(OntopQuery.java:104) [ontop-cli-1.18.0.jar:1.18.0]
	at it.unibz.inf.ontop.cli.Ontop.main(Ontop.java:21) [ontop-cli-1.18.0.jar:1.18.0]
Caused by: java.sql.SQLException: No suitable driver found for jdbc:sqlite:/ontop-example/person.db
	at java.sql.DriverManager.getConnection(DriverManager.java:689) ~[na:1.8.0_65]
	at java.sql.DriverManager.getConnection(DriverManager.java:247) ~[na:1.8.0_65]
	at it.unibz.inf.ontop.owlrefplatform.core.Quest.connect(Quest.java:387) ~[ontop-reformulation-core-1.18.0.jar:1.18.0]
	at it.unibz.inf.ontop.owlrefplatform.core.Quest.setupRepository(Quest.java:527) ~[ontop-reformulation-core-1.18.0.jar:1.18.0]
	... 7 common frames omitted
org.semanticweb.owlapi.reasoner.ReasonerInternalException: it.unibz.inf.ontop.model.OBDAException: java.sql.SQLException: No suitable driver found for jdbc:sqlite:/ontop-example/person.db
	at it.unibz.inf.ontop.owlrefplatform.owlapi3.QuestOWL.prepareReasoner(QuestOWL.java:465)
	at it.unibz.inf.ontop.owlrefplatform.owlapi3.QuestOWL.init(QuestOWL.java:148)
	at it.unibz.inf.ontop.owlrefplatform.owlapi3.QuestOWL.<init>(QuestOWL.java:174)
	at it.unibz.inf.ontop.owlrefplatform.owlapi3.QuestOWLFactory.createReasoner(QuestOWLFactory.java:107)
	at it.unibz.inf.ontop.cli.OntopQuery.run(OntopQuery.java:104)
	at it.unibz.inf.ontop.cli.Ontop.main(Ontop.java:21)
Caused by: it.unibz.inf.ontop.model.OBDAException: java.sql.SQLException: No suitable driver found for jdbc:sqlite:/ontop-example/person.db
	at it.unibz.inf.ontop.owlrefplatform.core.Quest.setupRepository(Quest.java:661)
	at it.unibz.inf.ontop.owlrefplatform.owlapi3.QuestOWL.prepareQuestInstance(QuestOWL.java:271)
	at it.unibz.inf.ontop.owlrefplatform.owlapi3.QuestOWL.prepareReasoner(QuestOWL.java:452)
	... 5 more
Caused by: java.sql.SQLException: No suitable driver found for jdbc:sqlite:/ontop-example/person.db
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at it.unibz.inf.ontop.owlrefplatform.core.Quest.connect(Quest.java:387)
	at it.unibz.inf.ontop.owlrefplatform.core.Quest.setupRepository(Quest.java:527)
	... 7 more

**Comment by seralf** [comment]
HI using ontop from java API with SQLite JDBC driver imported by maven works for me.
Apart from the obvious limitations derived from the peculiar SQLite dialect, I only have a warning:

```
2018-06-05 11:37:46 WARN  it.unibz.inf.ontop.owlrefplatform.core.queryevaluation.SQLAdapterFactory:58 - WARNING: the specified driver doesn't correspond to any of the drivers officially supported by Ontop.
```

my workaround from code was to actually declare a fictious username/password pair (I suggest use "" for both).
I suppose it should be simple to add SQLite official support, if there are test to extend.

I hope this helps.

**Comment by majidaldo** [comment]
it almost works. but i got this error for a table with a pk.

"java.lang.IllegalArgumentException: Nullable attribute "Id" INTEGER cannot be in a PK"

idk why it thinks that it's nullable.

**Comment by maximelefrancois86** [comment]
Dear all, 
Ping on this issue. It mostly seem to work for me. Any more information about what works and what doesn't, and reference sqlite in the documentation website, would be appreciated. 
My plan is to query a homeassistant database (by default sqlite)

**Comment by bcogrel** [comment]
Hi, SQLite is still missing a dialect adapter (https://ontop-vkg.org/dev/db-adapter), so it is not supported. 

Good to hear that it almost works with the default dialect (https://ontop-vkg.org/guide/databases/generic). Therefore, I presume that implementing a dialect adapter should be relatively easy. But we may have some surprises, given the originality of the SQLite design (e.g. it allows dynamic typing).

**Comment by bcogrel** [comment]
As an alternative, please consider using DuckDB. It supports SQLite files: https://duckdb.org/docs/lts/core_extensions/sqlite
