### ISSUE TITLE
saving and opening a config

### ISSUE THREAD

**Issue by PaulZH** [ontop/ontop#137]
Working in Protégé.
Having the database connection working.
Loading R2RML: no errors thrown
Instantiating the reasoner: no errors
Doing a few SPARQL queries: all working
Saving the file -> file.obda.
Closing Protégé.
Restarting Protégé.
Opening file.owl
Getting following error:

```
An exception has occurred when loading input file.
Message: Exception occurred while loading OBDA document: /Users/paul/Desktop/OSLO/R2RML/CRAB.obda


The plugin cannot load the OBDA model: (REASON: Invalid mappings)
Please fix the following mappings and reload the file.

MappingId = 'mapping-539735108'
Line 19: Invalid input: (sourceQuery = null)

MappingId = 'mapping--127114104'
Line 33: Invalid input: (sourceQuery = null)

MappingId = 'mapping-1534767216'
Line 72: Invalid input: (sourceQuery = null)



###################################################
##    Debugging information (for the authors)    ##
###################################################

	at it.unibz.inf.ontop.protege.core.OBDAModelManager$OBDAPluginOWLModelManagerListener.handleOntologyLoadedAndReLoaded(OBDAModelManager.java:695)
	at it.unibz.inf.ontop.protege.core.OBDAModelManager$OBDAPluginOWLModelManagerListener.handleChange(OBDAModelManager.java:542)
	at org.protege.editor.owl.model.OWLModelManagerImpl.lambda$fireEvent$153(OWLModelManagerImpl.java:792)
	at org.protege.editor.owl.model.OWLModelManagerImpl$$Lambda$26/1840962896.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:869)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:666)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:637)
	at org.protege.editor.owl.model.io.OntologyLoader.lambda$displayOntologiesAlreadyLoadedMessage$181(OntologyLoader.java:159)
	at org.protege.editor.owl.model.io.OntologyLoader$$Lambda$141/168340687.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1654)
	at java.awt.Component.setVisible(Component.java:1606)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at org.protege.editor.owl.ui.util.ProgressDialog.lambda$setVisible$182(ProgressDialog.java:51)
	at org.protege.editor.owl.ui.util.ProgressDialog$$Lambda$83/564094945.run(Unknown Source)
	at org.protege.editor.owl.ui.util.ProgressDialog.setVisible(ProgressDialog.java:55)
	at org.protege.editor.owl.model.io.OntologyLoader.showProgressDialog(OntologyLoader.java:93)
	at org.protege.editor.owl.model.io.OntologyLoader.loadOntologyInOtherThread(OntologyLoader.java:70)
	at org.protege.editor.owl.model.io.OntologyLoader.loadOntology(OntologyLoader.java:54)
	at org.protege.editor.owl.model.OWLModelManagerImpl.loadOntologyFromPhysicalURI(OWLModelManagerImpl.java:280)
	at org.protege.editor.owl.OWLEditorKit.handleLoadFrom(OWLEditorKit.java:201)
	at org.protege.editor.owl.OWLEditorKit.handleLoadRequest(OWLEditorKit.java:195)
	at org.protege.editor.core.ui.action.OpenAction.openInCurrentWorkspace(OpenAction.java:61)
	at org.protege.editor.core.ui.util.UIUtil.openRequest(UIUtil.java:222)
	at org.protege.editor.core.ui.action.OpenAction.actionPerformed(OpenAction.java:29)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)
	at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
	at java.awt.MenuItem.processEvent(MenuItem.java:628)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by skomlaebri** [comment]
This problem can appear if in the source part of the mapping, where you declare the select query, there is an empty line (in the middle of the query or at the end).
If you open the obda file you should see how the source of your mappings (in particular mapping-539735108, mapping--127114104, mapping-1534767216) appears and if there is an empty line.
If this is not the case, can you send us your r2rml and obda file?

**Comment by PaulZH** [comment]
Thanks. Removing the empty lines from the SQL queries solved this error. 
I get now following:
`Found an invalid target query: [http://www.w3.org/ns/locn#Address(URI("http://id.vlaanderen.be/id/adres/{}",AdresID)), http://www.opengis.net/ont/geosparql#asWKT(URI("http://id.vlaanderen.be/id/adres/{}",AdresID),Positie), http://www.w3.org/ns/locn#thoroughfare(URI("http://id.vlaanderen.be/id/adres/{}",AdresID),http://www.w3.org/2000/01/rdf-schema#Literal(straatnaam_nl,"nl")), http://www.w3.org/ns/locn#postName(URI("http://id.vlaanderen.be/id/adres/{}",AdresID),http://www.w3.org/2000/01/rdf-schema#Literal(gemeentenaam_nl,"nl")), http://www.w3.org/ns/locn#locatorDesignator(URI("http://id.vlaanderen.be/id/adres/{}",AdresID),Huisnummer), http://www.w3.org/ns/locn#postCode(URI("http://id.vlaanderen.be/id/adres/{}",AdresID),Postcode), http://www.w3.org/2000/01/rdf-schema#label(URI("http://id.vlaanderen.be/id/adres/{}",AdresID),http://www.w3.org/2000/01/rdf-schema#Literal(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(straatnaam_nl," "),Huisnummer),", "),Postcode)," "),gemeentenaam_nl))), http://purl.org/dc/terms/identifier(URI("http://id.vlaanderen.be/id/adres/{}",AdresID),http://www.w3.org/2001/XMLSchema#integer(AdresID)), http://www.opengis.net/ont/geosparql#sfTouches(URI("http://id.vlaanderen.be/id/adres/{}",AdresID),URI("http://id.vlaanderen.be/id/straat/{}",StraatID))] 
`
Any suggestion?

**Comment by skomlaebri** [comment]
Hi, I cannot see anything wrong in the mapping.
Can you turn on the debug mode (you can do that inside Protege folder Protege/conf/logback.xml and modify the root level from info to debug) and send us the complete log file?

**Comment by PaulZH** [comment]
Attached the log file. HTH.
[protege.log.zip](https://github.com/ontop/ontop/files/311826/protege.log.zip)

**Comment by skomlaebri** [comment]
This kind of error can be generated if one of the classes or properties is not defined in the ontology.
Check for example that rdfs:label has been added explicitly as an annotation property in your ontology (in Protege it will appear in bold)

**Comment by PaulZH** [comment]
Something weird going on.
After having followed your suggestions I still did get ...

`The plugin cannot load the OBDA model: (REASON: Invalid mappings)
Please fix the following mappings and reload the file.

```
MappingId = 'mapping--656471061'
Line 54: Invalid input: (sourceQuery = null)`
```

After having removed and reinjecting the empty line on line 54 followed by a save in an external editor, it works since then.

**Comment by EmileSonneveld** [comment]
I got the same error. After removing some lines in the .obdo file that contained only tabs, the problem was solved.
Thanks for pointing me in the right direction! :)
