### ISSUE TITLE
ms sql limitation

### ISSUE THREAD

**Issue by PaulZH** [ontop/ontop#140]
Is GROUP BY supported using the MS SQL driver?

If I take as testcase (slight modification on [https://www.w3.org/2009/sparql/docs/tests/summary.html#grouping-group01](https://www.w3.org/2009/sparql/docs/tests/summary.html#grouping-group01))

```
SELECT ?s
{
  ?s rdfs:label ?v .
}
GROUP BY ?s
```

I get:

```
it.unibz.inf.ontop.model.OBDAException: Error rewriting and unfolding into SQL
null 
it.unibz.inf.ontop.owlapi.OntopOWLException: it.unibz.inf.ontop.model.OBDAException: Error rewriting and unfolding into SQL
null
	at it.unibz.inf.ontop.owlrefplatform.owlapi.QuestOWLStatement.executeTuple(QuestOWLStatement.java:109) ~[na:na]
	at it.unibz.inf.ontop.protege.views.QueryInterfaceView$2.executeQuery(QueryInterfaceView.java:194) ~[na:na]
	at it.unibz.inf.ontop.protege.views.QueryInterfaceView$2.executeQuery(QueryInterfaceView.java:161) ~[na:na]
	at it.unibz.inf.ontop.protege.gui.action.OBDADataQueryAction$1.run(OBDADataQueryAction.java:152) ~[na:na]
Caused by: it.unibz.inf.ontop.model.OBDAException: Error rewriting and unfolding into SQL
null
	at it.unibz.inf.ontop.model.impl.CQIEImpl.toString(CQIEImpl.java:164) ~[na:na]
	at it.unibz.inf.ontop.model.impl.CQIEImpl.hashCode(CQIEImpl.java:142) ~[na:na]
	at it.unibz.inf.ontop.model.impl.CQIEImpl.equals(CQIEImpl.java:201) ~[na:na]
	at java.util.LinkedList.indexOf(LinkedList.java:605) ~[na:1.8.0_51]
	at java.util.LinkedList.contains(LinkedList.java:317) ~[na:1.8.0_51]
	at it.unibz.inf.ontop.model.impl.DatalogProgramImpl.appendRule(DatalogProgramImpl.java:67) ~[na:na]
	at it.unibz.inf.ontop.owlrefplatform.core.translator.SparqlAlgebraToDatalogTranslator.createRule(SparqlAlgebraToDatalogTranslator.java:225) ~[na:na]
	at it.unibz.inf.ontop.owlrefplatform.core.translator.SparqlAlgebraToDatalogTranslator.translate(SparqlAlgebraToDatalogTranslator.java:117) ~[na:na]
	at it.unibz.inf.ontop.owlrefplatform.core.QuestQueryProcessor.getSQL(QuestQueryProcessor.java:122) ~[na:na]
	at it.unibz.inf.ontop.owlrefplatform.core.QuestStatement.startExecute(QuestStatement.java:353) ~[na:na]
	at it.unibz.inf.ontop.owlrefplatform.core.QuestStatement.executeTupleQuery(QuestStatement.java:317) ~[na:na]
	at it.unibz.inf.ontop.owlrefplatform.core.QuestStatement.execute(QuestStatement.java:221) ~[na:na]
	at it.unibz.inf.ontop.owlrefplatform.owlapi.QuestOWLStatement.executeTuple(QuestOWLStatement.java:103) ~[na:na]
```

**Comment by ghxiao** [comment]
Hi, this is not a problem of MS SQL. It is a more general problem. The current version of ontop does not support GROUP BY. Proper supporting of GROUP BY and more in general aggregation functions are our ongoing work.
