### ISSUE TITLE
Capital letters in primary keys (PostgreSQL) caused NullPointerException during reasoner initialization

### ISSUE THREAD

**Issue by AllenatChina** [ontop/ontop#146]
Hello,

I am using Ontop in my project. I met some NullPointerExceptions when starting the reasoner in Protege. Through java api debugging, I found out that when my primary key was uppercase, it failed to setup repository of the Quest instance. I checked some source files like
QuotedIDFactoryLowerCase.java
QuotedID.java
I think something might be wrong with the quotation parsing, because from debugging I found two versions "ID" and ""ID""  (the name of my primary key is ID) in two QuotedID instances which needs to be matched.

Refer to those lines of code:
it.unibz.inf.ontop.sql.DBMetadataExtractor.java : 257
it.unibz.inf.ontop.sql.DBMetadataExtractor.java : 593
it.unibz.inf.ontop.sql.DBMetadataExtractor.java : 601
it.unibz.inf.ontop.sql.DatabaseRelationDefinition.java : 85      //returns null

Below are the logs:

2016-07-03 01:25:00.324 [Classification Thread] ERROR OWLReasonerManager    An error occurred during reasoning: it.unibz.inf.ontop.model.OBDAException: java.lang.NullPointerException.
org.semanticweb.owlapi.reasoner.ReasonerInternalException: it.unibz.inf.ontop.model.OBDAException: java.lang.NullPointerException
	at it.unibz.inf.ontop.owlrefplatform.owlapi.QuestOWL.prepareReasoner(QuestOWL.java:465) ~[na:na]
	at it.unibz.inf.ontop.owlrefplatform.owlapi.QuestOWL.flush(QuestOWL.java:206) ~[na:na]
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.ensureRunningReasonerInitialized(OWLReasonerManagerImpl.java:423) ~[na:na]
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.run(OWLReasonerManagerImpl.java:382) ~[na:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_40]
Caused by: it.unibz.inf.ontop.model.OBDAException: java.lang.NullPointerException
	at it.unibz.inf.ontop.owlrefplatform.core.Quest.setupRepository(Quest.java:661) ~[na:na]
	at it.unibz.inf.ontop.owlrefplatform.owlapi.QuestOWL.prepareQuestInstance(QuestOWL.java:271) ~[na:na]
	at it.unibz.inf.ontop.owlrefplatform.owlapi.QuestOWL.prepareReasoner(QuestOWL.java:452) ~[na:na]
	... 4 common frames omitted
Caused by: java.lang.NullPointerException: null
	at it.unibz.inf.ontop.sql.UniqueConstraint$Builder.add(UniqueConstraint.java:65) ~[na:na]
	at it.unibz.inf.ontop.sql.DBMetadataExtractor.getUniqueAttributes(DBMetadataExtractor.java:601) ~[na:na]
	at it.unibz.inf.ontop.sql.DBMetadataExtractor.loadMetadata(DBMetadataExtractor.java:257) ~[na:na]
	at it.unibz.inf.ontop.owlrefplatform.core.Quest.setupRepository(Quest.java:556) ~[na:na]
	... 6 common frames omitted

**Comment by ghxiao** [comment]
Hi @AllenatChina , thanks for reporting. Is it possible to provide a minimal scenario so that we can reproduce the problem more easily?

**Comment by AllenatChina** [comment]
yes.. use PostgreSQL as database, create a table with the primary key "ID" (without quotation marks), connect the database with ontop using protégé 5.0, and try to start the reasoner.

**Comment by skomlaebri** [comment]
Hi @AllenatChina  I cannot reproduce the bug. This could be due to a bug in the postgres jdbc driver, try to update your driver to the latest version https://jdbc.postgresql.org/download.html
If the problem is still not solved, please send us your owl and obda file.

**Comment by AllenatChina** [comment]
Hello @skomlaebri I tested the 9.4.1208 jdbc4 postgresql driver, still unsolved. I think the reason you couldn't find the bug is that you didn't have mappings pointing to those tables with uppercase primary key. 

You can find my project here: 
https://github.com/AllenatChina/AirportOnTop

The postgreSQL **data file** is here:
[https://github.com/AllenatChina/AirportOnTop/blob/master/airportDB.backup](url)
 _**(In order to reproduce the bug, after restoring the data, modify any one of the tables' primary key column to capital letters, I have mappings referring to all of them)**_

And here are **owl and obda files**:
https://github.com/AllenatChina/AirportOnTop/tree/master/src/main/resources/ontology

**Comment by ghxiao** [comment]
Hi @AllenatChina 

We load your data but still we could not reproduce the problem. If it possible, you can come to our office and show us the problem. That would be very helpful for us.

Cheers,

**Comment by kontchakov** [comment]
Hi 

I know what the problem is - do not use quotation marks in the PostgreSQL IDE. If you do, then the name actually includes quotation marks. 

In general, I’m trying to see how the problem with such names can be avoided.

Best
Roman

**Comment by AllenatChina** [comment]
@ghxiao I tested again with the latest jdbc driver. It works this time! The thing is even I changed the location of driver in the Preference panel, I have to restart Protégé to make it load the new driver.

Thank you for your patience 👍 ! But you should update your wiki more often!  Since here https://github.com/ontop/ontop/wiki/ObdalibPluginJDBC version 9.1-902 is still recommended for PostgreSQL! : )
