### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by roholazandie** [ontop/ontop#148]
Hi,
I have a problem with language support of ontop. How can i tell the ontop mapper to use the triples sample without error. for example i want a mapping like this:

:{Id} :hasSummary {summary}@en . 
select Id, hasSummary from table1

but in the code when i run the code i got the following error:

```
Exception in thread "main" org.semanticweb.owlapi.reasoner.ReasonerInternalException: it.unibz.inf.ontop.model.OBDAException: it.unibz.inf.ontop.model.OBDAException: Ontology datatype http://www.w3.org/2001/XMLSchema#string for http://www.semanticweb.org/blah/ontologies/2016/4/TestOntologyVer1.0#SomeRel
does not correspond to datatype http://www.w3.org/2000/01/rdf-schema#Literal in mappings
	at it.unibz.inf.ontop.owlrefplatform.owlapi.QuestOWL.prepareReasoner(QuestOWL.java:465)
	at it.unibz.inf.ontop.owlrefplatform.owlapi.QuestOWL.init(QuestOWL.java:148)
	at it.unibz.inf.ontop.owlrefplatform.owlapi.QuestOWL.<init>(QuestOWL.java:174)
	at it.unibz.inf.ontop.owlrefplatform.owlapi.QuestOWLFactory.createReasoner(QuestOWLFactory.java:107)
	at TDBManager.PopulateTDB(TDBManager.java:xxx)
	at TDBManager.Run(TDBManager.java:xxx)
```

**Comment by bcogrel** [comment]
Hi, 

In your ontology, you declared that the range of the property :hasSummary is xsd:string .
An xsd:string does not accept language tags, so that's why you have an error.

My advice would be to remove the range declaration from your ontology if you want to use a language tag.

For more info please visit https://www.w3.org/TR/rdf11-new/#literals . Please note that we still use RDF 1.0 at the present time and thus we don't support the rdf:langString datatype yet.

Best,

**Comment by roholazandie** [comment]
Thank you very much. My problem resolved.
