### ISSUE TITLE
Ontop:  Expected 'ref' parameter in request

### ISSUE THREAD

**Issue by Iranox** [ontop/ontop#170]
I want to use ontop with a query federation tool (fedex or semagrow).
But I get the following error:

```
 Jan 15, 2017 1:30:03 PM org.openrdf.workbench.proxy.ServerValidator checkServerPrefixes
 WARNING: server URL null does not have a prefix file: http: https:
 Jan 15, 2017 1:30:03 PM org.openrdf.workbench.proxy.WorkbenchServlet service
 INFO: Servicing repository: 1
 Jan 15, 2017 1:30:03 PM org.openrdf.workbench.proxy.WorkbenchServlet setCredentials
 INFO: RemoteRepositoryManager URL: http://ontop:8080/openrdf-sesame
 Jan 15, 2017 1:30:03 PM org.openrdf.workbench.proxy.WorkbenchServlet setCredentials
 INFO: Setting user 'null' and password 'null'.
 Jan 15, 2017 1:30:03 PM org.openrdf.workbench.util.CookieHandler addCookie
 INFO: name: query
 value: SELECT+*+WHERE+%7B+%3Fs+%3Fp+%3Fo+%7D+LIMIT+1
 Jan 15, 2017 1:30:03 PM org.openrdf.workbench.util.CookieHandler addCookie
 INFO: un-encoded value: SELECT * WHERE { ?s ?p ?o } LIMIT 1
 --
 Jan 15, 2017 1:30:03 PM org.openrdf.workbench.util.CookieHandler addCookie
 INFO: name: queryLn
 value: SPARQL
 Jan 15, 2017 1:30:03 PM org.openrdf.workbench.util.CookieHandler addCookie
 INFO: un-encoded value: SPARQL
 --
 Jan 15, 2017 1:30:03 PM org.openrdf.workbench.util.CookieHandler addCookie
 INFO: name: infer
 value: true
 Jan 15, 2017 1:30:03 PM org.openrdf.workbench.util.CookieHandler addCookie
 INFO: un-encoded value: true
 --
 2017-01-15 13:30:03.130:WARN:oejs.ServletHandler:
 javax.servlet.ServletException: org.openrdf.workbench.exceptions.BadRequestException: Expected 'ref' parameter in request.
 	at org.openrdf.workbench.base.TransformationServlet.service(TransformationServlet.java:116)
 	at org.openrdf.workbench.commands.QueryServlet.service(QueryServlet.java:163)
 	at org.openrdf.workbench.base.BaseServlet.service(BaseServlet.java:136)
 	at org.openrdf.workbench.proxy.ProxyRepositoryServlet.service(ProxyRepositoryServlet.java:104)
 	at org.openrdf.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:240)
 	at org.openrdf.workbench.proxy.WorkbenchServlet.handleRequest(WorkbenchServlet.java:151)
 	at org.openrdf.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:119)
 	at org.openrdf.workbench.proxy.WorkbenchGateway.service(WorkbenchGateway.java:131)
 	at org.openrdf.workbench.base.BaseServlet.service(BaseServlet.java:136)
 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:669)
 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1448)
 	at org.openrdf.workbench.proxy.CookieCacheControlFilter.doFilter(CookieCacheControlFilter.java:63)
 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)
 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)
 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
 	at org.eclipse.jetty.server.Server.handle(Server.java:368)
 	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:488)
 	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:943)
 	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1004)
 	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:861)
 	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
 	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
 	at java.lang.Thread.run(Thread.java:745)
 Caused by:
 org.openrdf.workbench.exceptions.BadRequestException: Expected 'ref' parameter in request.
 	at org.openrdf.workbench.commands.QueryServlet.canReadSavedQuery(QueryServlet.java:455)
 	at org.openrdf.workbench.commands.QueryServlet.doPost(QueryServlet.java:270)
 	at org.openrdf.workbench.base.TransformationServlet.service(TransformationServlet.java:106)
 	at org.openrdf.workbench.commands.QueryServlet.service(QueryServlet.java:163)
 	at org.openrdf.workbench.base.BaseServlet.service(BaseServlet.java:136)
 	at org.openrdf.workbench.proxy.ProxyRepositoryServlet.service(ProxyRepositoryServlet.java:104)
 	at org.openrdf.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:240)
 	at org.openrdf.workbench.proxy.WorkbenchServlet.handleRequest(WorkbenchServlet.java:151)
 	at org.openrdf.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:119)
 	at org.openrdf.workbench.proxy.WorkbenchGateway.service(WorkbenchGateway.java:131)
 	at org.openrdf.workbench.base.BaseServlet.service(BaseServlet.java:136)
 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:669)
 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1448)
 	at org.openrdf.workbench.proxy.CookieCacheControlFilter.doFilter(CookieCacheControlFilter.java:63)
 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)
 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)
 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
 	at org.eclipse.jetty.server.Server.handle(Server.java:368)
 	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:488)
 	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:943)
 	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1004)
 	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:861)
 	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
 	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
 	at java.lang.Thread.run(Thread.java:745)
 2017-01-15 13:30:03.131:WARN:oejs.ServletHandler:/openrdf-workbench/repositories/1/query
 org.openrdf.workbench.exceptions.BadRequestException: Expected 'ref' parameter in request.
 	at org.openrdf.workbench.commands.QueryServlet.canReadSavedQuery(QueryServlet.java:455)
 	at org.openrdf.workbench.commands.QueryServlet.doPost(QueryServlet.java:270)
 	at org.openrdf.workbench.base.TransformationServlet.service(TransformationServlet.java:106)
 	at org.openrdf.workbench.commands.QueryServlet.service(QueryServlet.java:163)
 	at org.openrdf.workbench.base.BaseServlet.service(BaseServlet.java:136)
 	at org.openrdf.workbench.proxy.ProxyRepositoryServlet.service(ProxyRepositoryServlet.java:104)
fedex_1                | 2017-01-15 13:30:03,135 DEBUG - << "HTTP/1.1 500 Expected 'ref' parameter in request.[\r][\n]"
 	at org.openrdf.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:240)
```

**Comment by Iranox** [comment]
I replicate the error with following curl request:

```
curl --data "action=exec&query=select%20%3Fs%20where{%20%3Fs%20%3Fo%20%3Fp}" http://ontop:8080/openrdf-workbench/repositories/1/query
```

This request  had  the same error. After adding ref=test as a parameter the request works.
So the working request is:

```
curl --data "action=exec&ref=test&query=select%20%3Fs%20where{%20%3Fs%20%3Fo%20%3Fp}" http://ontop:8080/openrdf-workbench/repositories/1/query
```

After adding this parameter in the config file the query federation tool works.
