### ISSUE TITLE
Ontop Plugin Stops Protege from Starting (on Java 9)

### ISSUE THREAD

**Issue by James-G-Hill** [ontop/ontop#215]
### Description

After installing Ontop through the Protege plugin manager, Protege refuses to restart.

### Steps to Reproduce

1. Install Ontop through the Protege plugin manager.

2. Close Protege so that you can restart.

3. Run the Protege run.sh file from terminal.

4. The terminal then shows the following (I've copied from the Protege log) and Protege fails to start:

2017-11-03 20:43:38.216 [FelixDispatchQueue] INFO  ProtegeApplication    ------------------------------------ Protege -----------------------------------
2017-11-03 20:43:38.219 [FelixDispatchQueue] INFO  ProtegeApplication    Protege Desktop
2017-11-03 20:43:38.226 [FelixDispatchQueue] INFO  ProtegeApplication    Version 5.2.0, Build 
2017-11-03 20:43:38.228 [FelixDispatchQueue] INFO  ProtegeApplication    
2017-11-03 20:43:38.228 [FelixDispatchQueue] INFO  ProtegeApplication    
2017-11-03 20:43:38.228 [FelixDispatchQueue] INFO  ProtegeApplication    ----------------------------------- Platform -----------------------------------
2017-11-03 20:43:38.229 [FelixDispatchQueue] INFO  ProtegeApplication    Java: JVM 9+181  Memory: 524M
2017-11-03 20:43:38.229 [FelixDispatchQueue] INFO  ProtegeApplication    Language: en, Country: GB
2017-11-03 20:43:38.231 [FelixDispatchQueue] INFO  ProtegeApplication    Framework: Apache Software Foundation (1.8) 
2017-11-03 20:43:38.231 [FelixDispatchQueue] INFO  ProtegeApplication    OS: linux (4.13.0.16-generic)
2017-11-03 20:43:38.231 [FelixDispatchQueue] INFO  ProtegeApplication    Processor: x86-64

2017-11-03 20:43:38.231 [FelixDispatchQueue] INFO  ProtegeApplication    
2017-11-03 20:43:38.231 [FelixDispatchQueue] INFO  ProtegeApplication    ------------------------------------ Plugins -----------------------------------
2017-11-03 20:43:38.232 [FelixDispatchQueue] INFO  ProtegeApplication    Plugin: HermiT (1.3.8.413)
2017-11-03 20:43:38.233 [FelixDispatchQueue] INFO  ProtegeApplication    Plugin: Existential Query (2.0.0)
2017-11-03 20:43:38.233 [FelixDispatchQueue] INFO  ProtegeApplication    Plugin: Explanation Workbench (3.0.0)
2017-11-03 20:43:38.233 [FelixDispatchQueue] INFO  ProtegeApplication    Plugin: SWRLTab Protege 5.0+ Plugin (1.0.3)
2017-11-03 20:43:38.234 [FelixDispatchQueue] INFO  ProtegeApplication    Plugin: DL Query (4.0.1)
2017-11-03 20:43:38.234 [FelixDispatchQueue] INFO  ProtegeApplication    Plugin: OWLAPI RDF Library (2.0.2)
2017-11-03 20:43:38.235 [FelixDispatchQueue] INFO  ProtegeApplication    Plugin: OWLViz (5.0.3)
2017-11-03 20:43:38.235 [FelixDispatchQueue] INFO  ProtegeApplication    Plugin: Browser View (OWLDoc) (3.0.3)
2017-11-03 20:43:38.236 [FelixDispatchQueue] INFO  ProtegeApplication    Plugin: OntoGraf (2.0.3)
2017-11-03 20:43:38.236 [FelixDispatchQueue] INFO  ProtegeApplication    Plugin: Cellfie Protege 5.0+ Plugin (2.1.0)
2017-11-03 20:43:38.236 [FelixDispatchQueue] INFO  ProtegeApplication    Plugin: Protege SPARQL Plugin (2.0.1)
2017-11-03 20:43:38.238 [FelixDispatchQueue] INFO  ProtegeApplication    Plugin: OWL Code Generation Plug-in (2.0.0)
2017-11-03 20:43:38.238 [FelixDispatchQueue] INFO  ProtegeApplication    Plugin: ELK Reasoner Protege Plug-in (0.4.3)
2017-11-03 20:43:38.239 [FelixDispatchQueue] INFO  ProtegeApplication    Plugin: jcel (0.24.0)
2017-11-03 20:43:38.239 [FelixDispatchQueue] INFO  ProtegeApplication    Plugin: Change Tracker (2.0.2)
2017-11-03 20:43:38.240 [FelixDispatchQueue] INFO  ProtegeApplication    Plugin: OBO Annotations Editor (0.4.0)
2017-11-03 20:43:38.240 [FelixDispatchQueue] INFO  ProtegeApplication    Plugin: CSV Export Plugin (1.0.0)
2017-11-03 20:43:38.241 [FelixDispatchQueue] INFO  ProtegeApplication    Plugin: matrix (4.0.0)
2017-11-03 20:43:38.241 [FelixDispatchQueue] INFO  ProtegeApplication    Plugin: Factplusplus Plug-in (1.6.5)
2017-11-03 20:43:38.242 [FelixDispatchQueue] INFO  ProtegeApplication    Plugin: Individual Properties Contextual Assertions (1.0.1)
2017-11-03 20:43:38.242 [FelixDispatchQueue] WARN  ProtegeApplication    Plugin: Ontop OBDA Protégé plugin (1.18.1) was not successfully started.  Please see the Protégé log for more details.
2017-11-03 20:43:38.244 [FelixDispatchQueue] INFO  ProtegeApplication    Plugin: OAF Protege Plugin (1.0.0)
2017-11-03 20:43:38.245 [FelixDispatchQueue] INFO  ProtegeApplication    
2017-11-03 20:43:38.556 [FelixDispatchQueue] INFO  ProtegeApplication    Creating and setting up empty (default) editor kit
2017-11-03 20:43:38.561 [FelixDispatchQueue] INFO  OWLEditorKit    OWL API Version: 4.2.8.20170104-2310
2017-11-03 20:43:39.001 [FelixDispatchQueue] INFO  ConfigurationFactory    Loading default configuration parameters for class org.semanticweb.elk.reasoner.config.ReasonerConfiguration
2017-11-03 20:43:39.326 [FelixDispatchQueue] ERROR ProtegeApplication    Exception caught starting Protege
java.lang.NoClassDefFoundError: java/sql/SQLException
	at it.unibz.inf.ontop.protege.core.OBDAModelManager.<init>(OBDAModelManager.java:74) ~[na:na]
	at it.unibz.inf.ontop.protege.core.OBDAEditorKitSynchronizerPlugin.initialise(OBDAEditorKitSynchronizerPlugin.java:69) ~[na:na]
	at org.protege.editor.core.editorkit.Initializers.loadEditorKitHooks(Initializers.java:25) ~[protege-editor-core.jar:na]
	at org.protege.editor.owl.OWLEditorKit.<init>(OWLEditorKit.java:93) ~[na:na]
	at org.protege.editor.owl.OWLEditorKitFactory.createEditorKit(OWLEditorKitFactory.java:45) ~[na:na]
	at org.protege.editor.core.ProtegeManager.createAndSetupNewEditorKit(ProtegeManager.java:136) ~[protege-editor-core.jar:na]
	at org.protege.editor.core.ProtegeManager.createAndSetupNewEditorKit(ProtegeManager.java:129) ~[protege-editor-core.jar:na]
	at org.protege.editor.core.ProtegeApplication.createAndSetupDefaultEditorKit(ProtegeApplication.java:488) [protege-editor-core.jar:na]
	at org.protege.editor.core.ProtegeApplication.startApplication(ProtegeApplication.java:432) [protege-editor-core.jar:na]
	at org.protege.editor.core.ProtegeApplication.reallyStart(ProtegeApplication.java:109) [protege-editor-core.jar:na]
	at org.protege.editor.core.ProtegeApplication.lambda$start$12(ProtegeApplication.java:90) [protege-editor-core.jar:na]
	at org.apache.felix.framework.EventDispatcher.invokeFrameworkListenerCallback(EventDispatcher.java:881) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:830) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.EventDispatcher.run(EventDispatcher.java:1147) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.EventDispatcher.access$000(EventDispatcher.java:54) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.EventDispatcher$1.run(EventDispatcher.java:102) ~[org.apache.felix.main.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:844) ~[na:na]
Caused by: java.lang.ClassNotFoundException: java.sql.SQLException
	at java.base/java.lang.ClassLoader.findClass(ClassLoader.java:709) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[na:na]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1507) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2018) ~[org.apache.felix.main.jar:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[na:na]
	... 17 common frames omitted
2017-11-03 20:43:51.213 [Close OSGi Session] INFO  Launcher    ----------------------- Shutting down Protege -----------------------
2017-11-03 20:43:51.293 [Close OSGi Session] INFO  Launcher    Cleaning up temporary directories

**Expected behavior:**
I expected Protege to start.

**Actual behavior:**
Protege fails to start.

**Reproduces how often:**
Every time until I manually delete the Ontop java plugin from my .Protege/plugins folder

### Versions

Ontop OBDA Protégé plugin (1.18.1)

### Additional Information

My operating system is Ubuntu 17.10.  I'm using Protege-5.2.0 platform independent version with Java 9 (JVM 9+181).

**Comment by ghxiao** [comment]
Hi, this seems to be related to modularization of Java 9. We have noticed some issues with Java 9 of Ontop and also of Protege side. We have started to investigate. In the meanwhile, please use Java 8.

**Comment by James-G-Hill** [comment]
Thanks, it's a pity because I was using Java 9 to get around the non-scaling for hidpi monitors with Java 8. Hope it can be resolved soonish.

**Comment by ghxiao** [comment]
Related issue of Protege project: protegeproject/protege#732

**Comment by ghxiao** [comment]
@James-G-Hill Hi I am not even able to start Protege on Java 9 (on both Mac and Linux); see the above issue report. Could you tell me how did you start Protege? Thanks!

**Comment by James-G-Hill** [comment]
@ghxiao Hello.  I don't believe I had to do anything special to get it to run with Java 9 on my system.  As I recall, I simply removed Java 8 and installed Java 9.  Then I think Protege ran immediately with correct scaling for my hidpi laptop. This was on Ubuntu 17.04.

Now, a week later I then updated Ubuntu to 17.10 with GNOME desktop and that stopped Protege scaling to hidpi correctly, although that's a different issue that I'm trying to resolve.  Protege with Java 9 otherwise runs fine on Ubuntu 17.10 until I try to install Ontop.

i don't know if the following will be useful, but below are the settings I pass to Java through my Protege run.sh:

java -Xmx500M -Xms200M \
     -Xss16M \
     -Dlogback.configurationFile=conf/logback.xml \
     -DentityExpansionLimit=100000000 \
     -Dfile.encoding=UTF-8 \
     -XX:CompileCommand=exclude,javax/swing/text/GlyphView,getBreakSpot \
     -classpath bundles/guava.jar:bundles/logback-classic.jar:bundles/logback-core.jar:bundles/slf4j-api.jar:bin/org.apache.felix.main.jar:bin/maven-artifact.jar:bin/protege-launcher.jar \
     $CMD_OPTIONS org.protege.osgi.framework.Launcher $1

Please let me know if there's anything else you think might be useful.

**Comment by ghxiao** [comment]
Hi, there is now a fork of protege works on Java 9. See protegeproject/protege#732

I quickly tested and it works nice for me. I just needed to compile Protege (using java 9 for sure) and drop the ontop plugin to the plugins directory. I don't need to change anything from the Ontop side.

You may experience an issue like:
```
java.lang.NullPointerException: null
	at it.unibz.inf.ontop.protege.core.OntopReasonerInfo.getConfiguration(OntopReasonerInfo.java:50) ~[na:na]
```
To solve it, just reset the preferences of Protege. 

Please give it a try and let us know how it goes.
