### ISSUE TITLE
Missing postgresql jdbc driver

### ISSUE THREAD

**Issue by reinvantveer** [ontop/ontop#246]
Hi, 

When running the jetty bundle for 1.18.1 (Ubuntu Xenial) I get an error after creating the rdf4j repo:
http://localhost:8080/openrdf-sesame/repositories/bgt-virt says:

```
org.openrdf.repository.RepositoryException: it.unibz.inf.ontop.model.OBDAException: java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost/bgt
```

I inserted the jdbc jar from 
http://search.maven.org/#artifactdetails%7Corg.postgresql%7Cpostgresql%7C9.4-1201-jdbc41%7Cjar (as seems to be instructed by https://github.com/ontop/ontop/wiki/ObdalibPluginJDBC#driver-class but this driver is ancient)
in $JETTY_HOME/lib/ext as instructed on https://github.com/ontop/ontop/wiki/Sesame-SPARQL-endpoint-installation#troubleshooting however it seems jetty or ontop isn't picking it up. I must be doing something wrong...

Full stack trace as attachment, with owl and properties file

[settings_and_trace.zip](https://github.com/ontop/ontop/files/1739510/settings_and_trace.zip)

**Comment by ghxiao** [comment]
Hi,

Thanks a lot for the detailed report. 

I noticed that you are using Java 9 from your stacktrace. The jetty bundle used by Ontop 1.18 was based on an old version of Jetty, which is not surprised to have issue with Java 9. You may want to use Java 8 if you want to stick to the old version of Ontop and Jetty.

Meanwhile, I would strongly recommend you to switch to Ontop version3-beta-1, which provides both tomcat and jetty bundle. I just did a quick test, both tomcat and jetty bundles work well under Java 9.
There are many improvement of the SPARQL endpoint in v3-beta-1 . In particular, the workbench is based on the recent version of RDF4J (as supposed to Sesame v2 used in Ontop 1.18). The bundles also use new versions of tomcat and jetty.

Please give it a try and let us know how it goes.

**Comment by reinvantveer** [comment]
Hi @ghxiao I didn't get 3-beta-1 tomcat to work with java 9, but it does start with java 8. However, I still get:
`javax.servlet.ServletException: org.eclipse.rdf4j.repository.RepositoryException: org.eclipse.rdf4j.repository.RepositoryException: it.unibz.inf.ontop.exception.DBMetadataExtractionException: No suitable driver found for jdbc:postgresql://localhost/bgt`
on http://localhost:8080/rdf4j-workbench/repositories/bgt-virt/namespaces

Could you share some pointers on how to install/uses the postgres driver?

**Comment by ghxiao** [comment]
You just need to put the the JDBC library to $TOMCAT_HOME/lib directly and restart the tomcat.

**Comment by ghxiao** [comment]
@reinvantveer Also send me the error message of ontop under Java 9. It should work.

**Comment by reinvantveer** [comment]
Sorry, no joy just copying to lib/ and restarting under java 8...
Working on the java 9 errors

**Comment by reinvantveer** [comment]
The stacktrace for java 9:

```
20-Feb-2018 13:37:22.632 INFO [main] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["http-nio-8080"]
20-Feb-2018 13:37:22.632 INFO [main] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["ajp-nio-8009"]
20-Feb-2018 13:38:03.838 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.9
20-Feb-2018 13:38:03.841 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Dec 5 2016 20:18:12 UTC
20-Feb-2018 13:38:03.841 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.9.0
20-Feb-2018 13:38:03.841 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
20-Feb-2018 13:38:03.841 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.13.0-32-generic
20-Feb-2018 13:38:03.841 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
20-Feb-2018 13:38:03.841 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-9-openjdk-amd64
20-Feb-2018 13:38:03.841 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           9-internal+0-2016-04-14-195246.buildd.src
20-Feb-2018 13:38:03.841 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
20-Feb-2018 13:38:03.841 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /home/reinv/Documents/BGT-Hi5/ontop/3.0.0-beta1/apache-tomcat-8.5.9
20-Feb-2018 13:38:03.842 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /home/reinv/Documents/BGT-Hi5/ontop/3.0.0-beta1/apache-tomcat-8.5.9
20-Feb-2018 13:38:03.844 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/home/reinv/Documents/BGT-Hi5/ontop/3.0.0-beta1/apache-tomcat-8.5.9/conf/logging.properties
20-Feb-2018 13:38:03.844 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
20-Feb-2018 13:38:03.844 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
20-Feb-2018 13:38:03.844 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
20-Feb-2018 13:38:03.844 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/home/reinv/Documents/BGT-Hi5/ontop/3.0.0-beta1/apache-tomcat-8.5.9
20-Feb-2018 13:38:03.844 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/home/reinv/Documents/BGT-Hi5/ontop/3.0.0-beta1/apache-tomcat-8.5.9
20-Feb-2018 13:38:03.844 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/home/reinv/Documents/BGT-Hi5/ontop/3.0.0-beta1/apache-tomcat-8.5.9/temp
20-Feb-2018 13:38:03.844 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /usr/local/cuda-8.0/lib64/:/usr/lib/nvidia-384:/usr/lib/x86_64-linux-gnu:/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
20-Feb-2018 13:38:03.877 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
20-Feb-2018 13:38:03.895 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
20-Feb-2018 13:38:03.897 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
20-Feb-2018 13:38:03.898 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
20-Feb-2018 13:38:03.898 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 353 ms
20-Feb-2018 13:38:03.922 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
20-Feb-2018 13:38:03.922 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.9
20-Feb-2018 13:38:03.944 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive /home/reinv/Documents/BGT-Hi5/ontop/3.0.0-beta1/apache-tomcat-8.5.9/webapps/rdf4j-server.war
20-Feb-2018 13:38:04.262 SEVERE [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start: 
 org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/rdf4j-server]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@9-internal/Executors.java:514)
	at java.util.concurrent.FutureTask.run(java.base@9-internal/FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9-internal/ThreadPoolExecutor.java:1158)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9-internal/ThreadPoolExecutor.java:632)
	at java.lang.Thread.run(java.base@9-internal/Thread.java:804)
Caused by: javax.xml.parsers.FactoryConfigurationError: Provider for class javax.xml.parsers.SAXParserFactory cannot be created
	at javax.xml.parsers.FactoryFinder.findServiceProvider(java.xml@9-internal/FactoryFinder.java:311)
	at javax.xml.parsers.FactoryFinder.find(java.xml@9-internal/FactoryFinder.java:267)
	at javax.xml.parsers.SAXParserFactory.newInstance(java.xml@9-internal/SAXParserFactory.java:132)
	at org.apache.tomcat.util.digester.Digester.getFactory(Digester.java:432)
	at org.apache.tomcat.util.digester.Digester.getParser(Digester.java:617)
	at org.apache.tomcat.util.descriptor.web.WebXmlParser.<init>(WebXmlParser.java:62)
	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1104)
	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:775)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:299)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5087)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 10 more
Caused by: java.lang.RuntimeException: Provider for class javax.xml.parsers.SAXParserFactory cannot be created
	at javax.xml.parsers.FactoryFinder.findServiceProvider(java.xml@9-internal/FactoryFinder.java:308)
	... 21 more
Caused by: java.util.ServiceConfigurationError: javax.xml.parsers.SAXParserFactory: Provider org.apache.xerces.jaxp.SAXParserFactoryImpl not a subtype
	at java.util.ServiceLoader.fail(java.base@9-internal/ServiceLoader.java:388)
	at java.util.ServiceLoader.access$600(java.base@9-internal/ServiceLoader.java:220)
	at java.util.ServiceLoader$LazyClassPathIterator.nextService(java.base@9-internal/ServiceLoader.java:828)
	at java.util.ServiceLoader$RestrictedIterator.next(java.base@9-internal/ServiceLoader.java:540)
	at java.util.ServiceLoader$2.next(java.base@9-internal/ServiceLoader.java:940)
	at javax.xml.parsers.FactoryFinder$1.run(java.xml@9-internal/FactoryFinder.java:294)
	at java.security.AccessController.doPrivileged(java.base@9-internal/Native Method)
	at javax.xml.parsers.FactoryFinder.findServiceProvider(java.xml@9-internal/FactoryFinder.java:289)
	... 21 more

20-Feb-2018 13:38:04.264 SEVERE [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Error deploying web application archive /home/reinv/Documents/BGT-Hi5/ontop/3.0.0-beta1/apache-tomcat-8.5.9/webapps/rdf4j-server.war
 java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/rdf4j-server]]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:756)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@9-internal/Executors.java:514)
	at java.util.concurrent.FutureTask.run(java.base@9-internal/FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9-internal/ThreadPoolExecutor.java:1158)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9-internal/ThreadPoolExecutor.java:632)
	at java.lang.Thread.run(java.base@9-internal/Thread.java:804)

20-Feb-2018 13:38:04.265 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive /home/reinv/Documents/BGT-Hi5/ontop/3.0.0-beta1/apache-tomcat-8.5.9/webapps/rdf4j-server.war has finished in 320 ms
20-Feb-2018 13:38:04.266 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive /home/reinv/Documents/BGT-Hi5/ontop/3.0.0-beta1/apache-tomcat-8.5.9/webapps/rdf4j-workbench.war
20-Feb-2018 13:38:04.363 SEVERE [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start: 
 org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/rdf4j-workbench]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@9-internal/Executors.java:514)
	at java.util.concurrent.FutureTask.run(java.base@9-internal/FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9-internal/ThreadPoolExecutor.java:1158)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9-internal/ThreadPoolExecutor.java:632)
	at java.lang.Thread.run(java.base@9-internal/Thread.java:804)
Caused by: javax.xml.parsers.FactoryConfigurationError: Provider for class javax.xml.parsers.SAXParserFactory cannot be created
	at javax.xml.parsers.FactoryFinder.findServiceProvider(java.xml@9-internal/FactoryFinder.java:311)
	at javax.xml.parsers.FactoryFinder.find(java.xml@9-internal/FactoryFinder.java:267)
	at javax.xml.parsers.SAXParserFactory.newInstance(java.xml@9-internal/SAXParserFactory.java:132)
	at org.apache.tomcat.util.digester.Digester.getFactory(Digester.java:432)
	at org.apache.tomcat.util.digester.Digester.getParser(Digester.java:617)
	at org.apache.tomcat.util.descriptor.web.WebXmlParser.<init>(WebXmlParser.java:62)
	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1104)
	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:775)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:299)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5087)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 10 more
Caused by: java.lang.RuntimeException: Provider for class javax.xml.parsers.SAXParserFactory cannot be created
	at javax.xml.parsers.FactoryFinder.findServiceProvider(java.xml@9-internal/FactoryFinder.java:308)
	... 21 more
Caused by: java.util.ServiceConfigurationError: javax.xml.parsers.SAXParserFactory: Provider org.apache.xerces.jaxp.SAXParserFactoryImpl not a subtype
	at java.util.ServiceLoader.fail(java.base@9-internal/ServiceLoader.java:388)
	at java.util.ServiceLoader.access$600(java.base@9-internal/ServiceLoader.java:220)
	at java.util.ServiceLoader$LazyClassPathIterator.nextService(java.base@9-internal/ServiceLoader.java:828)
	at java.util.ServiceLoader$RestrictedIterator.next(java.base@9-internal/ServiceLoader.java:540)
	at java.util.ServiceLoader$2.next(java.base@9-internal/ServiceLoader.java:940)
	at javax.xml.parsers.FactoryFinder$1.run(java.xml@9-internal/FactoryFinder.java:294)
	at java.security.AccessController.doPrivileged(java.base@9-internal/Native Method)
	at javax.xml.parsers.FactoryFinder.findServiceProvider(java.xml@9-internal/FactoryFinder.java:289)
	... 21 more

20-Feb-2018 13:38:04.363 SEVERE [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Error deploying web application archive /home/reinv/Documents/BGT-Hi5/ontop/3.0.0-beta1/apache-tomcat-8.5.9/webapps/rdf4j-workbench.war
 java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/rdf4j-workbench]]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:756)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@9-internal/Executors.java:514)
	at java.util.concurrent.FutureTask.run(java.base@9-internal/FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9-internal/ThreadPoolExecutor.java:1158)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9-internal/ThreadPoolExecutor.java:632)
	at java.lang.Thread.run(java.base@9-internal/Thread.java:804)

20-Feb-2018 13:38:04.364 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive /home/reinv/Documents/BGT-Hi5/ontop/3.0.0-beta1/apache-tomcat-8.5.9/webapps/rdf4j-workbench.war has finished in 98 ms
20-Feb-2018 13:38:04.364 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /home/reinv/Documents/BGT-Hi5/ontop/3.0.0-beta1/apache-tomcat-8.5.9/webapps/ROOT
20-Feb-2018 13:38:04.598 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
20-Feb-2018 13:38:09.621 INFO [localhost-startStop-1] org.apache.catalina.util.SessionIdGeneratorBase.createSecureRandom Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [5,011] milliseconds.
20-Feb-2018 13:38:09.638 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /home/reinv/Documents/BGT-Hi5/ontop/3.0.0-beta1/apache-tomcat-8.5.9/webapps/ROOT has finished in 5,274 ms
20-Feb-2018 13:38:09.638 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /home/reinv/Documents/BGT-Hi5/ontop/3.0.0-beta1/apache-tomcat-8.5.9/webapps/docs
20-Feb-2018 13:38:09.717 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
20-Feb-2018 13:38:09.719 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /home/reinv/Documents/BGT-Hi5/ontop/3.0.0-beta1/apache-tomcat-8.5.9/webapps/docs has finished in 81 ms
20-Feb-2018 13:38:09.719 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /home/reinv/Documents/BGT-Hi5/ontop/3.0.0-beta1/apache-tomcat-8.5.9/webapps/examples
20-Feb-2018 13:38:09.893 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
20-Feb-2018 13:38:09.920 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /home/reinv/Documents/BGT-Hi5/ontop/3.0.0-beta1/apache-tomcat-8.5.9/webapps/examples has finished in 201 ms
20-Feb-2018 13:38:09.920 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /home/reinv/Documents/BGT-Hi5/ontop/3.0.0-beta1/apache-tomcat-8.5.9/webapps/host-manager
20-Feb-2018 13:38:09.969 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
20-Feb-2018 13:38:09.972 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /home/reinv/Documents/BGT-Hi5/ontop/3.0.0-beta1/apache-tomcat-8.5.9/webapps/host-manager has finished in 52 ms
20-Feb-2018 13:38:09.972 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /home/reinv/Documents/BGT-Hi5/ontop/3.0.0-beta1/apache-tomcat-8.5.9/webapps/manager
20-Feb-2018 13:38:10.057 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
20-Feb-2018 13:38:10.059 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /home/reinv/Documents/BGT-Hi5/ontop/3.0.0-beta1/apache-tomcat-8.5.9/webapps/manager has finished in 87 ms
20-Feb-2018 13:38:10.062 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler [http-nio-8080]
20-Feb-2018 13:38:10.067 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler [ajp-nio-8009]
20-Feb-2018 13:38:10.068 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 6169 ms
```

**Comment by skomlaebri** [comment]
Hi @reinvantveer, I managed to reproduce your issue using java-9-openjdk. 
For the moment, the suggestion I can give you is to use oracle-java9 instead.

**Comment by skomlaebri** [comment]
I did not have problem using openjdk 8 and tomcat. 
I used postgresql-42.1.4.jar and added it to apache-tomcat/lib

**Comment by reinvantveer** [comment]
@skomlaebri thanks the issue is not exactly with java 9 (i can easily switch to java 8), I'll try the postgresql-42.1.4.jar tomorrow.

@ghxiao are there docker images or dockerfiles that have a working setup including postgresql driver? I'm using postgresql 9.6, is this a problem? Which versions of postgresql are supported?

**Comment by ghxiao** [comment]
There is a docker setup around but unfortunately it is not up to date.  https://github.com/ontop/docker-ontop. I won't recommend to use it now.

We officially support PostgreSQL 9.6. Currently 9.6.2 is the version we used for unit test. Other recent versions should also work.

**Comment by reinvantveer** [comment]
Just tried postgresql-42.1.4.jar driver (the ODBC 4.2 version, from https://jdbc.postgresql.org/download/postgresql-42.1.4.jar) but it is still giving me the same error. I tried it on a clean unzip of the ontop tomcat bundle, but it is still giving me the error. Is there any way to supply a dockerfile with a good setup or if I supply one myself can you check its workings?

**Comment by reinvantveer** [comment]
Hi, I managed to re-create the missing postgresql driver issue with a dockerized setup. I hope this will clarify some things. The error is the exact same. Create a new repository using the Ontop virtual RDF store, with paths /ontop/bgt.owl, /ontop/bgt.obda and /ontop/bgt.properties as config paths (as mounted in the container). You will need all the files in the zip - including the docker-compose file.

Not included is data in the postgis image. You'll have to create it. There is a postgresql data dump here:
https://data.nlextract.nl/bgt/postgis/
Beware: the data is open but the dump is nearly 10 Gb in size. Download and backup restore will take about half an hour combined if you have good network connection and a fast machine.

[ontop.zip](https://github.com/ontop/ontop/files/1744325/ontop.zip)

**Comment by skomlaebri** [comment]
Hi, thanks for the docker image.
The problem is given by a missing jdbc.driver property in the bgt.properties file. If you add this information (org.postgresql.Driver) it will work properly.

**Comment by reinvantveer** [comment]
Wow, now I see it, it's pretty obvious, I have a working (even dockerized) setup now. Thanks!
However, it may be helpful for others as well to have more clear instructions in the wiki. The term "jdbc.driver" occurs only in https://github.com/ontop/ontop/wiki/MigrationGuideV1toV3 and not in connection with "org.postgresql.Driver". Perhaps it's useful for others as well?

Thanks @skomlaebri @ghxiao !

**Comment by ghxiao** [comment]
Hi @reinvantveer 

I am happy that now you have a running ontop-powered SPARQL endpoint.

Some technical details for future reference. The property "jdbc.driver" should be optional in normal usage of ontop because the standard way of using JDBC does not require the JDBC driver class (https://docs.oracle.com/javase/8/docs/api/java/sql/DriverManager.html#getConnection-java.lang.String-java.lang.String-java.lang.String-). However, we noticed that in a web container like tomcat or jetty, calling Class.forName(driverClass) before getting the connection is often necessary, otherwise we will see the error message like yours. 

To avoid this kind of issue, we will improve the documentation and force the user to put the driverClass in Protege.

Btw, we are always curious to know how our users are using ontop. it would nice if you could drop a line here:
https://github.com/ontop/ontop/wiki/UseCases

Cheers,
Guohui

**Comment by reinvantveer** [comment]
Tnx!
