### ISSUE TITLE
wkt Literal datatype problem

### ISSUE THREAD

**Issue by agnieszkalawrynowicz** [ontop/ontop#256]
### Description

Given an R2RML file content presented below (which contains mappings to wkt Literals) I am getting errors materializing ontology.

**Expected behavior:** [What you expect to see]
Correct transformation of data from a database to RDF including wktLiterals.

**Actual behavior:** [What actually happens]
Errors:

`it.unibz.inf.ontop.owlapi.exception.OntopOWLException: it.unibz.inf.ontop.exception.UnknownDatatypeException: Impossible to determine the expected datatype for the column the_geomwkt
Possible solutions: 
- Add an explicit datatype in the mapping 
- Add in the .properties file the setting: ontop.inferDefaultDatatype = true
 and we will infer the default datatype (xsd:string)
	at it.unibz.inf.ontop.owlapi.impl.DefaultOntopOWLAPIMaterializer.materialize(DefaultOntopOWLAPIMaterializer.java:54)
	at it.unibz.inf.ontop.cli.OntopMaterialize.runWithSingleFile(OntopMaterialize.java:325)
	at it.unibz.inf.ontop.cli.OntopMaterialize.run(OntopMaterialize.java:97)
	at it.unibz.inf.ontop.cli.Ontop.main(Ontop.java:18)
Caused by: it.unibz.inf.ontop.exception.UnknownDatatypeException: Impossible to determine the expected datatype for the column the_geomwkt
Possible solutions: 
- Add an explicit datatype in the mapping 
- Add in the .properties file the setting: ontop.inferDefaultDatatype = true
 and we will infer the default datatype (xsd:string)
	at it.unibz.inf.ontop.spec.mapping.transformer.impl.MappingDataTypeCompletion.lambda$getDataType$44(MappingDataTypeCompletion.java:212)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at it.unibz.inf.ontop.spec.mapping.transformer.impl.MappingDataTypeCompletion.getDataType(MappingDataTypeCompletion.java:212)
	at it.unibz.inf.ontop.spec.mapping.transformer.impl.MappingDataTypeCompletion.insertVariableDataTyping(MappingDataTypeCompletion.java:104)
	at it.unibz.inf.ontop.spec.mapping.transformer.impl.MappingDataTypeCompletion.insertDataTyping(MappingDataTypeCompletion.java:71)
	at it.unibz.inf.ontop.spec.mapping.transformer.impl.LegacyMappingDatatypeFiller.inferMissingDatatypes(LegacyMappingDatatypeFiller.java:64)
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convertPPMapping(SQLMappingExtractor.java:82)
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convertPPMapping(SQLMappingExtractor.java:36)
	at it.unibz.inf.ontop.spec.mapping.impl.AbstractMappingExtractor.extract(AbstractMappingExtractor.java:72)
	at it.unibz.inf.ontop.spec.mapping.impl.AbstractMappingExtractor.extract(AbstractMappingExtractor.java:43)
	at it.unibz.inf.ontop.spec.impl.DefaultOBDASpecificationExtractor.extract(DefaultOBDASpecificationExtractor.java:38)
	at it.unibz.inf.ontop.injection.impl.OntopMappingConfigurationImpl.loadSpecification(OntopMappingConfigurationImpl.java:129)
	at it.unibz.inf.ontop.injection.impl.OntopMappingSQLConfigurationImpl.loadSpecification(OntopMappingSQLConfigurationImpl.java:85)
	at it.unibz.inf.ontop.injection.impl.OntopMappingSQLAllConfigurationImpl.loadSpecification(OntopMappingSQLAllConfigurationImpl.java:48)
	at it.unibz.inf.ontop.injection.impl.OntopSQLOWLAPIConfigurationImpl.loadOBDASpecification(OntopSQLOWLAPIConfigurationImpl.java:34)
	at it.unibz.inf.ontop.injection.impl.OntopOBDAConfigurationImpl.loadSpecification(OntopOBDAConfigurationImpl.java:44)
	at it.unibz.inf.ontop.materialization.impl.DefaultOntopRDFMaterializer.materialize(DefaultOntopRDFMaterializer.java:93)
	at it.unibz.inf.ontop.owlapi.impl.DefaultOntopOWLAPIMaterializer.materialize(DefaultOntopOWLAPIMaterializer.java:52)
	... 3 more_
`

### Attached material

Mapping file content: 

@prefix dc: <http://purl.org/dc/elements/1.1/> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix rr: <http://www.w3.org/ns/r2rml#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix ontohgis: <http://purl.org/ontohgis#> .
@prefix oc: <http://ontologies.makolab.com/oc/> .
@prefix sf: <http://www.opengis.net/ont/sf#> .
@prefix obo: <http://purl.obolibrary.org/obo/> .

<http://purl.org/ontohgis#Manifestations> a rr:TriplesMap ;
    rr:logicalTable [ rr:sqlQuery """SELECT \"SettlementManifestations\".\"Identifiers\", \"SettlementManifestations\".\"Mereology\" from ontology."SettlementManifestations" LIMIT 10 """ ] ;
    rr:subjectMap [
         rr:template "http://purl.org/ontohgis#SettlementManifestation_{Identifiers}";
    rr:class ontohgis:object_40;  
   ].

<http://purl.org/ontohgis#Manifestations2> a rr:TriplesMap ;
    rr:logicalTable [ rr:sqlQuery """SELECT \"SettlementManifestations\".\"Identifiers\", \"SettlementManifestations\".\"Types\" from ontology."SettlementManifestations" WHERE \"SettlementManifestations\".\"Types\" IS NOT NULL LIMIT 10""" ] ;
   rr:subjectMap [
         rr:template "http://purl.org/ontohgis#SettlementManifestation_{Identifiers}";
    rr:class ontohgis:object_40; 
  ];
   rr:predicateObjectMap [
        rr:predicate rdf:type;
        rr:objectMap [ rr:template "http://purl.org/ontohgis#settlement_unit{Types}" ];
   ].

<http://purl.org/ontohgis#Manifestations3> a rr:TriplesMap ;
    rr:logicalTable [ rr:sqlQuery """SELECT \"SettlementManifestations\".\"Identifiers\", \"SettlementManifestations\".\"Names\" from ontology."SettlementManifestations" WHERE \"SettlementManifestations\".\"Names\" IS NOT NULL LIMIT 10""" ] ;
   rr:subjectMap [
         rr:template "http://purl.org/ontohgis#SettlementManifestation_{Identifiers}";
    rr:class ontohgis:object_40; 
  ];
   rr:predicateObjectMap [
        rr:predicate rdfs:label;
        rr:objectMap [ rr:column "Names"; rr:language "pl" ];
   ].

<http://purl.org/ontohgis#Manifestations4> a rr:TriplesMap ;
    rr:logicalTable [ rr:sqlQuery """SELECT \"SettlementManifestations\".\"Identifiers\", \"SettlementManifestations\".\"StartsAt\" from ontology."SettlementManifestations" WHERE \"SettlementManifestations\".\"StartsAt\" IS NOT NULL LIMIT 10""" ] ;
   rr:subjectMap [
         rr:template "http://purl.org/ontohgis#SettlementManifestation_{Identifiers}";
    rr:class ontohgis:object_40; 
  ];
   rr:predicateObjectMap [
        rr:predicate oc:hasBeginning;
        rr:objectMap [ rr:column "StartsAt"; rr:datatype xsd:date ];
   ].

<http://purl.org/ontohgis#Manifestations5> a rr:TriplesMap ;
    rr:logicalTable [ rr:sqlQuery """SELECT \"SettlementManifestations\".\"Identifiers\", \"SettlementManifestations\".\"EndsAt\" from ontology."SettlementManifestations" WHERE \"SettlementManifestations\".\"EndsAt\" IS NOT NULL LIMIT 10""" ] ;
   rr:subjectMap [
         rr:template "http://purl.org/ontohgis#SettlementManifestation_{Identifiers}";
    rr:class ontohgis:object_40; 
  ];
   rr:predicateObjectMap [
        rr:predicate oc:hasEnd;
        rr:objectMap [ rr:column "EndsAt"; rr:datatype xsd:date ];
   ]. 

<http://purl.org/ontohgis#Geometries> a rr:TriplesMap ;
    rr:logicalTable [ rr:sqlQuery """SELECT \"SettlementLocations\".\"Identifiers\", St_AsText(\"SettlementLocations\".\"the_geom\") as the_geomWkt  from ontology."SettlementLocations" LIMIT 10""" ] ;
   rr:subjectMap [
         rr:template "http://purl.org/ontohgis#Geometry_{Identifiers}";
    rr:class sf:Point; 
  ];
   rr:predicateObjectMap [
        rr:predicate \<http://www.opengis.net/ont/geosparql#asWkt\>;
        rr:objectMap [ 
        rdf:type rr:TermMap, rr:ObjectMap;
        rr:datatype \<http://www.opengis.net/ont/geosparql#wktLiteral\>;
        rr:column "the_geomWkt";
        rr:termType rr:Literal ];
   ]. 

### Versions

Cli, ontop-3.0.0-beta-2

**Comment by bcogrel** [comment]
Thanks for reporting (and sorry for the delay, we were very busy these weeks). 

Your last predicateObjectMap specifies the datatype, so such an exception should normally not be thrown. At first glance, it looks like a bug coming from our R2RML parser, we will investigate what is going on.

**Comment by bcogrel** [comment]
Hi,
So, the problem is not coming from our R2RML parser but from the way we handle RDF datatypes internally. Currently, in the main branch, we are not supporting arbitrary RDF datatypes but a predefined set of them only (unfortunately http://www.opengis.net/ont/geosparql#asWkt is not part of it).  

We are currently refactoring our code so as to support arbitrary datatypes (among others).

**Comment by agnieszkalawrynowicz** [comment]
Hi, 

Thank you for your response. It would be great if ontop covered even wktLiteral only (not even saying about arbitrary datatypes), it would solve my problem and enable its use in various GIS applications.


Cheers,
Agnieszka

**Comment by p1d1d1** [comment]
what about https://github.com/ConstantB/ontop-spatial ?

**Comment by p1d1d1** [comment]
@bcogrel any news here?

**Comment by bcogrel** [comment]
I added `geo:wkt` to the list of predefined internal datatypes, so it seems to work now (see `WktTest` in the `ontop-owlapi` module).

These commits are available in the `version3` branch and will be released with the beta-3.

Cheers,
Benjamin

**Comment by agnieszkalawrynowicz** [comment]
Thank you!
