### ISSUE TITLE
Ontop plugin - Error 

### ISSUE THREAD

**Issue by karanthpallavi** [ontop/ontop#257]
Hi,

Tried opening movieontology.owl which also has .obda file,
Gave this error:

An exception has occurred when loading input file.
Message: Exception occurred while loading OBDA document: E:\Pallavi\movieontology.obda

ERROR reading .obda file at line: 20 
MESSAGE: 1

###################################################
###################################################

	at it.unibz.inf.ontop.protege.core.OBDAModelManager$OBDAPluginOWLModelManagerListener.handleOntologyLoadedAndReLoaded(OBDAModelManager.java:695)
	at it.unibz.inf.ontop.protege.core.OBDAModelManager$OBDAPluginOWLModelManagerListener.handleChange(OBDAModelManager.java:542)
	at org.protege.editor.owl.model.OWLModelManagerImpl.lambda$fireEvent$153(OWLModelManagerImpl.java:792)
	at org.protege.editor.owl.model.OWLModelManagerImpl$$Lambda$36/1082994901.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1654)
	at java.awt.Component.setVisible(Component.java:1606)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at org.protege.editor.owl.ui.util.ProgressDialog.lambda$setVisible$182(ProgressDialog.java:51)
	at org.protege.editor.owl.ui.util.ProgressDialog$$Lambda$90/201646767.run(Unknown Source)
	at org.protege.editor.owl.ui.util.ProgressDialog.setVisible(ProgressDialog.java:55)
	at org.protege.editor.owl.model.io.OntologyLoader.showProgressDialog(OntologyLoader.java:93)
	at org.protege.editor.owl.model.io.OntologyLoader.loadOntologyInOtherThread(OntologyLoader.java:70)
	at org.protege.editor.owl.model.io.OntologyLoader.loadOntology(OntologyLoader.java:54)
	at org.protege.editor.owl.model.OWLModelManagerImpl.loadOntologyFromPhysicalURI(OWLModelManagerImpl.java:280)
	at org.protege.editor.owl.OWLEditorKit.handleLoadFrom(OWLEditorKit.java:201)
	at org.protege.editor.owl.OWLEditorKit.handleLoadRequest(OWLEditorKit.java:195)
	at org.protege.editor.core.ProtegeManager.openAndSetupEditorKit(ProtegeManager.java:209)
	at org.protege.editor.core.ui.action.OpenAction.openInNewWorkspace(OpenAction.java:53)
	at org.protege.editor.core.ui.util.UIUtil.openRequest(UIUtil.java:211)
	at org.protege.editor.core.ui.action.OpenAction.actionPerformed(OpenAction.java:29)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Kindly help,
 i need to populate my ontology with data from postgresql imdbobda table,
Please help,
Thanks in advance

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to see]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [Does it happen every time?]

### Attached material

Informations about the attachments (ontology, mappings and queries that are necessary to reproduce the problem)
Provide the log file (more information on how to obtain it in the guidelines)

### Versions

Which version of Ontop are you using and in which setting (Protege, SPARQL endpoint, Cli, Java API, ...)

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by juliencorman** [comment]
Hello,

You need to specify values for the "userName" and "password" parameters in the .obda file (the credentials for your postgresql DB).

Note also that for Ontop Version 3 (as opposed to Version 1), these parameters are not stored in the .obda file anymore, but in a distinct property file.
If you use Protege, this property file will be created automatically the first time you modify and save the mapping.
For more information, you can consult this page: http://github.com/ontop/ontop/wiki/MigrationGuideV1toV3

Regards,
Julien

**Comment by karanthpallavi** [comment]
Thanks! am using Protege...
Shall check this
