### ISSUE TITLE
SQLAdapterFactory for Maria DB

### ISSUE THREAD

**Issue by fraaur** [ontop/ontop#271]
Hi ,
I'm using the library **ontop-reformulation-core-1.18.1.jar** and  I'm having a issue to map data with Maria DB. In the following i show the Error:
I noticed that in the class SQLAdapterFactory , it's really missing SQlDialectAdapter for Maria DB.

In the following i show the query performed during the process (  In bold maybe I highlight the anomaly that I find in the query ):
SELECT 
   1 AS "sQuestType", NULL AS "sLang", ('https://w3id.org/italia/controlled-vocabulary/identifiers/' 
**|| QVIEW1.`id`**) AS "s", 
   1 AS "pQuestType", NULL AS "pLang", 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type' AS "p", 
   1 AS "oQuestType", NULL AS "oLang", 'http://www.w3.org/2004/02/skos/core#Concept' AS "o"

Using the same configuration by MySql the library works fine!!!

Can you help me? 
can you tell me the the exact configuration in object **QuestPreferences**

preferences.setCurrentValueOf(QuestPreferences.ABOX_MODE, QuestConstants.VIRTUAL);
preferences.setCurrentValueOf(QuestPreferences.SQL_GENERATE_REPLACE,QuestConstants.FALSE);
preferences.setCurrentValueOf(QuestPreferences.DBTYPE, "semantic");
preferences.setCurrentValueOf(QuestPreferences.DBNAME, db_name);
preferences.setCurrentValueOf(QuestPreferences.JDBC_DRIVER, db_driver);
preferences.setCurrentValueOf(QuestPreferences.JDBC_URL, dsn);
 preferences.setCurrentValueOf(QuestPreferences.DBUSER, usr);
preferences.setCurrentValueOf(QuestPreferences.DBPASSWORD, pwd);       preferences.setCurrentValueOf("org.obda.owlreformulationplatform.queryingAnnotationsInOntology", "true")
        
thanks

-------------------------------------------------
The error is: 

Exception in thread "main" java.lang.IllegalArgumentException: Not a valid (absolute) URI: 1
	at org.openrdf.model.impl.URIImpl.setURIString(URIImpl.java:79)
	at org.openrdf.model.impl.URIImpl.<init>(URIImpl.java:68)
	at org.openrdf.model.impl.ValueFactoryImpl.createURI(ValueFactoryImpl.java:50)
	at it.unibz.inf.ontop.sesame.SesameHelper.getResource(SesameHelper.java:19)
	at it.unibz.inf.ontop.sesame.SesameStatement.<init>(SesameStatement.java:76)
	at it.unibz.inf.ontop.sesame.SesameGraphQuery.createStatement(SesameGraphQuery.java:59)
	at it.unibz.inf.ontop.sesame.SesameGraphQuery.evaluate(SesameGraphQuery.java:80)
	at it.unibz.inf.ontop.sesame.RepositoryConnection.getStatements(RepositoryConnection.java:590)
	at it.almawave.sel.inps.rdf.TestWrapperR2ML$.main(TestWrapperR2ML.scala:150)
	at it.almawave.sel.inps.rdf.TestWrapperR2ML.main(TestWrapperR2ML.scala)

**Comment by bcogrel** [comment]
Hi,
Ontop does not have an adapter yet for MariaDB, but we are thinking about adding one in a future version (probably derived from the MySQL one).

Pipes do not seem to be interpreted as concat by default. Have you consider adding the following options to your JDBC url: `sessionVariables=sql_mode='PIPES_AS_CONCAT'`  ?

**Comment by bcogrel** [comment]
Another request: https://github.com/ontop/ontop/issues/462#issuecomment-1029020258

**Comment by bcogrel** [comment]
Implemented by https://github.com/ontop/ontop/commit/5f4ff82f00b3ac84b3014a17c73db8a9f7ea0e17 . Will take part of the next major release.
