### ISSUE TITLE
Cannot create an Ontop Virtual RDF Store

### ISSUE THREAD

**Issue by smoretti** [ontop/ontop#281]
Hi

I cannot create an Ontop Virtual RDF Store, when I click on the **Create** button nothing happens.

In tomcat log I can find this error message:
```
06-Feb-2019 16:29:29.613 SEVERE [ajp-nio-8009-exec-3] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [workbench] in context with path [/rdf4j-workbench] threw exception [No such repository: lite_v14_0] with root cause
 org.eclipse.rdf4j.workbench.exceptions.BadRequestException: No such repository: lite_v14_0
	at org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:222)
	at org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.handleRequest(WorkbenchServlet.java:142)
	at org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:110)
	at org.eclipse.rdf4j.workbench.proxy.WorkbenchGateway.service(WorkbenchGateway.java:120)
	at org.eclipse.rdf4j.workbench.base.AbstractServlet.service(AbstractServlet.java:129)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.eclipse.rdf4j.workbench.proxy.CacheFilter.doFilter(CacheFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.eclipse.rdf4j.workbench.proxy.CookieCacheControlFilter.doFilter(CookieCacheControlFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:487)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1463)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

I use
- OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.202-b08, mixed mode)
- Tomcat 8.5.30
- Linux Ubuntu 18.04.1 LTS
- Firefox 65.0 or Chrome 72.0.3626.81 (Official Build) (64-bit) or Opera 58.0.3135.53

**Comment by ghxiao** [comment]
Hi, the log does not include the error message of the creation.

Which version of Ontop are you using? 

You can try to re-create the repository with the same id to see if the error persists. If yes, in order to debug we need your files to reproduce your problem.

Btw, the next release of Ontop will include a lightweight cli for endpoint, which will hopefully reduce the effort of setting up a SPARQL endpoint.
See https://groups.google.com/forum/#!topic/ontop4obda/5tUys5yX1ps

**Comment by smoretti** [comment]
I use ontop 3.0.0-beta-2.

The error persists with the same id, and with other ids.
Which files do you need?

**Comment by ghxiao** [comment]
We will need owl, mapping, and property files, and jdbc driver, and a dump of the SQL file to replicate your problem.

**Comment by smoretti** [comment]
Here are the file links:
- https://raw.githubusercontent.com/biosoda/genex/master/genex.owl
- https://raw.githubusercontent.com/biosoda/bioquery/master/Bgee_OBDA_mappings/bgee_genex.obda
- [bgee_connection.properties.txt](https://github.com/ontop/ontop/files/2851011/bgee_connection.properties.txt)
- http://central.maven.org/maven2/mysql/mysql-connector-java/8.0.13/mysql-connector-java-8.0.13.jar
- ftp://ftp.bgee.org/bgee_v14/sql_lite_dump.tar.gz


I added the MySQL java connector in the *rdf4j-workbench/WEB-INF/lib/* and *rdf4j-server/WEB-INF/lib/* folders without success for the repository creation.


I forgot to mention I use an apache proxy in front of tomcat, with JkMount.

**Comment by juliencorman** [comment]
Hello,

Seems like RDF4J Workbench is not deployed or not launched (at least, I get the same error message if I interrupt it). 
You may try to open http://localhost:8080/manager/, and make sure that:
- both "RDF4J Server" and "RDF4J Workbench" appear in the list of applications (if not, you can add them from the same page, "Deploy/WAR file to deploy").
- both "RDF4J Server" and "RDF4J Workbench" are launched (i.e. you cannot click on the corresponding "Start" buttons).

Regards,
Julien

**Comment by smoretti** [comment]
Both "RDF4J Server" and "RDF4J Workbench" are launched according to tomcat manager.

And I can reach the *New Repository* page from where I cannot create the Ontop Virtual RDF Store

**Comment by khanhnvo** [comment]
Any update on this? I have a similar problem.

Thanks

**Comment by ghxiao** [comment]
Hi,

We have introduced a new CLI based endpoint in v3. This new endpoint and its Docker image are the recommended ways to set up SPARQL endpoints, because they are more powerful and reliable.
See https://ontop-vkg.org/tutorial/endpoint/

The old "RDF4J Server" and "RDF4J Workbench" are not recommended anymore and will be deprecated in v4 and eventually removed in future versions.
