### ISSUE TITLE
OntopConnectionException: Unable to fetch a connection in 30 seconds, none available

### ISSUE THREAD

**Issue by KMax** [ontop/ontop#299]
### Description

Ontop fails to execute more than 20 consecutive queries. I guess, it's the connection leaking.

### Steps to Reproduce

Perform more than 20 different queries one by one, not in parallel.

**Expected behavior:**

All the queries are completed.

**Actual behavior:**

The 21th query fails.

**Reproduces how often:**

Happens every time.

### Attached material

The exception on the 21th query:

```
jbpm_1      | 10:46:32,046 INFO  [stdout] (default task-16) QUERY: PREFIX  :     <http://mkk.datafabric.cc/>
jbpm_1      | 10:46:32,046 INFO  [stdout] (default task-16) PREFIX  sh:   <http://www.w3.org/ns/shacl#>
jbpm_1      | 10:46:32,046 INFO  [stdout] (default task-16) PREFIX  owl:  <http://www.w3.org/2002/07/owl#>
jbpm_1      | 10:46:32,046 INFO  [stdout] (default task-16) PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
jbpm_1      | 10:46:32,046 INFO  [stdout] (default task-16) PREFIX  dcterms: <http://purl.org/dc/terms/>
jbpm_1      | 10:46:32,046 INFO  [stdout] (default task-16) PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
jbpm_1      | 10:46:32,046 INFO  [stdout] (default task-16) PREFIX  vcard: <http://www.w3.org/2006/vcard/ns#>
jbpm_1      | 10:46:32,046 INFO  [stdout] (default task-16) PREFIX  foaf: <http://xmlns.com/foaf/0.1/>
jbpm_1      | 10:46:32,046 INFO  [stdout] (default task-16) 
jbpm_1      | 10:46:32,046 INFO  [stdout] (default task-16) SELECT  ?uri ?id
jbpm_1      | 10:46:32,046 INFO  [stdout] (default task-16) WHERE
jbpm_1      | 10:46:32,046 INFO  [stdout] (default task-16)   { ?uri  a                     :Region ;
jbpm_1      | 10:46:32,046 INFO  [stdout] (default task-16)           :id                   ?id . 
jbpm_1      | 10:46:32,046 INFO  [stdout] (default task-16)     <http://mkk.datafabric.cc/creditrequest/268769>
jbpm_1      | 10:46:32,047 INFO  [stdout] (default task-16)               :region  ?uri
jbpm_1      | 10:46:32,047 INFO  [stdout] (default task-16)   }
jbpm_1      | 10:46:32,047 INFO  [stdout] (default task-16) 
ontop_1     | 2019-08-15 10:47:02.068 ERROR 1 --- [nio-8080-exec-1] i.u.i.o.r.r.impl.OntopVirtualRepository  : Error creating repo connection: it.unibz.inf.ontop.exception.OntopConnectionException: org.apache.tomcat.jdbc.pool.PoolExhaustedException: [http-nio-8080-exec-1] Timeout: Pool empty. Unable to fetch a connection in 30 seconds, none available[size:20; busy:20; idle:0; lastwait:30000].
ontop_1     | org.eclipse.rdf4j.repository.RepositoryException: org.eclipse.rdf4j.repository.RepositoryException: it.unibz.inf.ontop.exception.OntopConnectionException: org.apache.tomcat.jdbc.pool.PoolExhaustedException: [http-nio-8080-exec-1] Timeout: Pool empty. Unable to fetch a connection in 30 seconds, none available[size:20; busy:20; idle:0; lastwait:30000].
ontop_1     | 	at it.unibz.inf.ontop.rdf4j.repository.impl.OntopVirtualRepository.getConnection(OntopVirtualRepository.java:69)
ontop_1     | 	at it.unibz.inf.ontop.endpoint.SparqlQueryController.execQuery(SparqlQueryController.java:135)
ontop_1     | 	at it.unibz.inf.ontop.endpoint.SparqlQueryController.query_get(SparqlQueryController.java:94)
ontop_1     | 	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
ontop_1     | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
ontop_1     | 	at java.lang.reflect.Method.invoke(Method.java:498)
ontop_1     | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
ontop_1     | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
ontop_1     | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
ontop_1     | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
ontop_1     | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
ontop_1     | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
ontop_1     | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
ontop_1     | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
ontop_1     | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
ontop_1     | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
ontop_1     | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
ontop_1     | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
ontop_1     | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
ontop_1     | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
ontop_1     | 	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)
ontop_1     | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
ontop_1     | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
ontop_1     | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
ontop_1     | 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
ontop_1     | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
ontop_1     | 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
ontop_1     | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
ontop_1     | 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117)
ontop_1     | 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106)
ontop_1     | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
ontop_1     | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
ontop_1     | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
ontop_1     | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
ontop_1     | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
ontop_1     | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
ontop_1     | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
ontop_1     | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
ontop_1     | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
ontop_1     | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
ontop_1     | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
ontop_1     | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
ontop_1     | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:791)
ontop_1     | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
ontop_1     | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
ontop_1     | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
ontop_1     | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
ontop_1     | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
ontop_1     | 	at java.lang.Thread.run(Thread.java:748)
ontop_1     | Caused by: org.eclipse.rdf4j.repository.RepositoryException: it.unibz.inf.ontop.exception.OntopConnectionException: org.apache.tomcat.jdbc.pool.PoolExhaustedException: [http-nio-8080-exec-1] Timeout: Pool empty. Unable to fetch a connection in 30 seconds, none available[size:20; busy:20; idle:0; lastwait:30000].
ontop_1     | 	at it.unibz.inf.ontop.rdf4j.repository.impl.OntopVirtualRepository.getOntopConnection(OntopVirtualRepository.java:102)
ontop_1     | 	at it.unibz.inf.ontop.rdf4j.repository.impl.OntopVirtualRepository.getConnection(OntopVirtualRepository.java:66)
ontop_1     | 	... 64 more
ontop_1     | Caused by: it.unibz.inf.ontop.exception.OntopConnectionException: org.apache.tomcat.jdbc.pool.PoolExhaustedException: [http-nio-8080-exec-1] Timeout: Pool empty. Unable to fetch a connection in 30 seconds, none available[size:20; busy:20; idle:0; lastwait:30000].
ontop_1     | 	at it.unibz.inf.ontop.answering.connection.impl.JDBCConnector.getSQLPoolConnection(JDBCConnector.java:106)
ontop_1     | 	at it.unibz.inf.ontop.answering.connection.impl.JDBCConnector.getConnection(JDBCConnector.java:127)
ontop_1     | 	at it.unibz.inf.ontop.answering.impl.OntopQueryEngineImpl.getConnection(OntopQueryEngineImpl.java:41)
ontop_1     | 	at it.unibz.inf.ontop.rdf4j.repository.impl.OntopVirtualRepository.getOntopConnection(OntopVirtualRepository.java:100)
ontop_1     | 	... 65 more
ontop_1     | Caused by: org.apache.tomcat.jdbc.pool.PoolExhaustedException: [http-nio-8080-exec-1] Timeout: Pool empty. Unable to fetch a connection in 30 seconds, none available[size:20; busy:20; idle:0; lastwait:30000].
ontop_1     | 	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:708)
ontop_1     | 	at org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:198)
ontop_1     | 	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:132)
ontop_1     | 	at it.unibz.inf.ontop.answering.connection.pool.impl.TomcatConnectionPool.getConnection(TomcatConnectionPool.java:81)
ontop_1     | 	at it.unibz.inf.ontop.answering.connection.impl.JDBCConnector.getSQLPoolConnection(JDBCConnector.java:104)
ontop_1     | 	... 68 more
```

### Versions

The version is v3.0.0-beta-3-SNAPSHOT. The docker image pulled from hub.docker.com is used. It was pulled less than 12 days ago.

### Additional Information

The underlaying database is Postgres 10.5. The JDBC driver's version is 42.2.5.

**Comment by ghxiao** [comment]
Thanks for reporting this.

Could you try if the tomcat bundle https://github.com/ontop/ontop/releases/tag/ontop-3.0.0-beta-3 has the same issue?

**Comment by KMax** [comment]
@ghxiao Thanks for a quick reply!

As I see, I already use the tomcat version. See the exception:

```
org.apache.tomcat.jdbc.pool.PoolExhaustedException: [http-nio-8080-exec-1] Timeout: Pool empty. Unable to fetch a connection in 30 seconds, none available[size:20; busy:20; idle:0; lastwait:30000].
```

I use [ontop/ontop-endpoint](https://hub.docker.com/r/ontop/ontop-endpoint).

**Comment by ghxiao** [comment]
Great! Thanks for your quick confirmation. This can help us narrow down the problem.

**Comment by ghxiao** [comment]
@KMax Actually it is different. The error message is from tomcat jdbc pool, which is used separately than the Tomcat web server.

**Comment by KMax** [comment]
@ghxiao Hmm, I can't reproduce it with the Tomcat bundle.

Where is the Dockerfile which is used to build the ontop/ontop-endpoint image?

**Comment by ghxiao** [comment]
I have almost fixed it. It was sth stupid in my code. I will push the changes soon.

**Comment by ghxiao** [comment]
It should work now. The fix is  07a115bad0cca66ad7aad061a80cc11d905678bd
Docker related files are at https://github.com/ontop/ontop/tree/version3/client/docker
I have also pushed a new build to docker hub.  Please give it a try.

**Comment by KMax** [comment]
Awesome! Works now. @ghxiao Thank you for such a quick fix!

**Comment by ghxiao** [comment]
Thanks again for reporting this critical issue. We are about to make a release very soon, which will include this fix.
