### ISSUE TITLE
Can't query triples from ontology? Result: OntopResultConversionException: typeCode unknown: -1

### ISSUE THREAD

**Issue by KMax** [ontop/ontop#302]
### Description

I have some triples in the ontology which aren't mentioned in the mappings. A query which mentions them fails with the following exception:

```
ontop_1     | java.lang.RuntimeException: it.unibz.inf.ontop.exception.OntopResultConversionException: it.unibz.inf.ontop.exception.OntopResultConversionException: typeCode unknown: -1
ontop_1     | 	at it.unibz.inf.ontop.rdf4j.query.impl.OntopRDF4JBindingSet.convertBinding(OntopRDF4JBindingSet.java:98)
ontop_1     | 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
ontop_1     | 	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
ontop_1     | 	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
ontop_1     | 	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
ontop_1     | 	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:169)
ontop_1     | 	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
ontop_1     | 	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
ontop_1     | 	at org.eclipse.rdf4j.query.resultio.sparqljson.AbstractSPARQLJSONWriter.handleSolution(AbstractSPARQLJSONWriter.java:170)
ontop_1     | 	at org.eclipse.rdf4j.query.resultio.sparqljson.SPARQLResultsJSONWriter.handleSolution(SPARQLResultsJSONWriter.java:19)
ontop_1     | 	at it.unibz.inf.ontop.rdf4j.query.impl.OntopTupleQuery.evaluate(OntopTupleQuery.java:87)
ontop_1     | 	at it.unibz.inf.ontop.endpoint.SparqlQueryController.execQuery(SparqlQueryController.java:145)
ontop_1     | 	at it.unibz.inf.ontop.endpoint.SparqlQueryController.query_post_URL_encoded(SparqlQueryController.java:106)
ontop_1     | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
ontop_1     | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
ontop_1     | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
ontop_1     | 	at java.lang.reflect.Method.invoke(Method.java:498)
ontop_1     | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
ontop_1     | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
ontop_1     | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
ontop_1     | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
ontop_1     | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
ontop_1     | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
ontop_1     | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
ontop_1     | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
ontop_1     | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
ontop_1     | 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
ontop_1     | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
ontop_1     | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
ontop_1     | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
ontop_1     | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
ontop_1     | 	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)
ontop_1     | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
ontop_1     | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
ontop_1     | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
ontop_1     | 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
ontop_1     | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
ontop_1     | 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
ontop_1     | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
ontop_1     | 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117)
ontop_1     | 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106)
ontop_1     | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
ontop_1     | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
ontop_1     | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
ontop_1     | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
ontop_1     | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
ontop_1     | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
ontop_1     | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
ontop_1     | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
ontop_1     | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
ontop_1     | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
ontop_1     | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
ontop_1     | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
ontop_1     | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
ontop_1     | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:791)
ontop_1     | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
ontop_1     | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
ontop_1     | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
ontop_1     | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
ontop_1     | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
ontop_1     | 	at java.lang.Thread.run(Thread.java:748)
ontop_1     | Caused by: it.unibz.inf.ontop.exception.OntopResultConversionException: it.unibz.inf.ontop.exception.OntopResultConversionException: typeCode unknown: -1
ontop_1     | 	at it.unibz.inf.ontop.answering.resultset.impl.JDBC2ConstantConverter.getConstantFromJDBC(JDBC2ConstantConverter.java:246)
ontop_1     | 	at it.unibz.inf.ontop.answering.resultset.impl.SQLOntopBinding.getValue(SQLOntopBinding.java:26)
ontop_1     | 	at it.unibz.inf.ontop.rdf4j.query.impl.OntopRDF4JBindingSet.convertBinding(OntopRDF4JBindingSet.java:95)
ontop_1     | 	... 75 more
ontop_1     | Caused by: it.unibz.inf.ontop.exception.OntopResultConversionException: typeCode unknown: -1
ontop_1     | 	at it.unibz.inf.ontop.answering.resultset.impl.JDBC2ConstantConverter.getConstantFromJDBC(JDBC2ConstantConverter.java:136)
ontop_1     | 	... 77 more
```

### Steps to Reproduce

I have defined some SKOS concepts in the ontology, e.g.:

```
:Region
  rdf:type skos:ConceptScheme ;
  rdfs:label "Регион" .

<http://mkk.datafabric.cc/Region/40>
  rdf:type skos:Concept ;
  rdfs:label "Санкт-Петербург" ;
  skos:inScheme :Region ;
  skos:notation "RU_SPE" .
```

**Expected behavior:**

Query:

```
SELECT  * { <http://mkk.datafabric.cc/Region/40> ?p ?o  }
```

should return all the relevant triples from the ontology.

**Actual behavior:**

The result set is empty, but the log has the exception from above.

**Reproduces how often:**

Always.

### Versions

Ontop CLI 3.0.0 from Docker Hub.
JDBC driver: Postgres 42.2.6

**Comment by JBPressac** [comment]
Hello,
It might because you did not specified the [XML Schema datatypes](https://github.com/ontop/ontop/wiki/OntopDatatypes) in your mappings or specified a wrong datatype. For instance: 

`:Region rdfs:label {label}^^xsd:string`

I had the same error while using `xsd:Year` instead `xsd:gYear` in a mapping.
