### ISSUE TITLE
ntriples format does not work on version 3

### ISSUE THREAD

**Issue by seralf** [ontop/ontop#313]
### Description

The dump can't be generated as N-TRIPLES format.

### Steps to Reproduce

Execute ontop (version 3) like in the following example:

```bash
$ ontop materialize -m my_mapping.r2rml.ttl --format "ntriples" -o my_dump.nt-p my_configuration.properties
```

**Expected behavior:**

the file `my_dump.nt` should be created in ntriples format

**Actual behavior:** 

the execution returns an error `Unknown output format: ntriples` 

**Reproduces how often:**
it happens all the time

### Attached material

this an example of the returned exception:

```bash
it.unibz.inf.ontop.answering.reformulation.impl.QuestQueryProcessor - Ontop has completed the setup and it is ready for query answering!
java.lang.RuntimeException: java.lang.RuntimeException: Unknown output format: ntriples
        at it.unibz.inf.ontop.cli.OntopMaterialize.runWithSingleFile(OntopMaterialize.java:175)
        at it.unibz.inf.ontop.cli.OntopMaterialize.run(OntopMaterialize.java:124)
        at it.unibz.inf.ontop.cli.Ontop.main(Ontop.java:18)
Caused by: java.lang.RuntimeException: Unknown output format: ntriples
        at it.unibz.inf.ontop.cli.OntopMaterialize$OutputSpec.createRDFHandler(OntopMaterialize.java:338)
...
```

### Versions

Version 3

### Additional Information

We should be able to add a configuration here:
[SQL99DialectAdapter#L42-L56](https://github.com/ontop/ontop/blob/version3/engine/reformulation/sql/src/main/java/it/unibz/inf/ontop/answering/reformulation/generation/dialect/impl/SQL99DialectAdapter.java#L42-L56)

in order to control this specific behaviour

**Comment by juliencorman** [comment]
Dear Alfredo,

Thank you for notifying the bug.
We will fix this asap.

Regards,
Julien

**Comment by seralf** [comment]
Hi Julien thanks very much!
we look forward for the next release then!
