### ISSUE TITLE
ONTOP CLI Materialization throwing InvalidMappingException: IRI included an unencoded space: '32'

### ISSUE THREAD

**Issue by robertowillrich** [ontop/ontop#322]
### Description

I want to generate RDF data out of your database, but a "InvalidMappingException: IRI included an unencoded space: '32' [line 1]" always occurs even with the exampleBook. I'm using.

./ontop query -m exampleBooks.obda   -t exampleBooks.owl   -q q.txt   -p exampleBooks.properties is working!

### Steps to Reproduce

1. Run ./ontop materialize -m exampleBooks.owl  -f turtle -o materializedBooks.ttl  -p exampleBooks.properties 

**Actual behavior:** [What actually happens]
java.lang.RuntimeException: it.unibz.inf.ontop.exception.InvalidMappingException: IRI included an unencoded space: '32' [line 1]
        at it.unibz.inf.ontop.cli.OntopMaterialize.createMaterializer(OntopMaterialize.java:143)
        at it.unibz.inf.ontop.cli.OntopMaterialize.run(OntopMaterialize.java:117)
        at it.unibz.inf.ontop.cli.Ontop.main(Ontop.java:18)
Caused by: it.unibz.inf.ontop.exception.InvalidMappingException: IRI included an unencoded space: '32' [line 1]
        at it.unibz.inf.ontop.spec.mapping.parser.impl.R2RMLMappingParser.parse(R2RMLMappingParser.java:60)
        at it.unibz.inf.ontop.spec.mapping.parser.impl.R2RMLMappingParser.parse(R2RMLMappingParser.java:33)
        at it.unibz.inf.ontop.spec.mapping.impl.AbstractMappingExtractor.extractPPMapping(AbstractMappingExtractor.java:51)
        at it.unibz.inf.ontop.spec.mapping.impl.AbstractMappingExtractor.extract(AbstractMappingExtractor.java:41)
        at it.unibz.inf.ontop.spec.impl.DefaultOBDASpecificationExtractor.extract(DefaultOBDASpecificationExtractor.java:38)
        at it.unibz.inf.ontop.injection.impl.OntopMappingConfigurationImpl.loadSpecification(OntopMappingConfigurationImpl.java:129)
        at it.unibz.inf.ontop.injection.impl.OntopMappingSQLConfigurationImpl.loadSpecification(OntopMappingSQLConfigurationImpl.java:85)
        at it.unibz.inf.ontop.injection.impl.OntopMappingSQLAllConfigurationImpl.loadSpecification(OntopMappingSQLAllConfigurationImpl.java:48)
        at it.unibz.inf.ontop.injection.impl.OntopSQLOWLAPIConfigurationImpl.loadOBDASpecification(OntopSQLOWLAPIConfigurationImpl.java:34)
        at it.unibz.inf.ontop.injection.impl.OntopOBDAConfigurationImpl.loadSpecification(OntopOBDAConfigurationImpl.java:44)
        at it.unibz.inf.ontop.materialization.impl.DefaultOntopRDFMaterializer.<init>(DefaultOntopRDFMaterializer.java:94)
        at it.unibz.inf.ontop.rdf4j.materialization.impl.DefaultRDF4JMaterializer.<init>(DefaultRDF4JMaterializer.java:58)
        at it.unibz.inf.ontop.rdf4j.materialization.RDF4JMaterializer.defaultMaterializer(RDF4JMaterializer.java:34)
        at it.unibz.inf.ontop.cli.OntopMaterialize.createMaterializer(OntopMaterialize.java:136)
        ... 2 more

**Reproduces how often:** [Does it happen every time?]

Every time.

### Versions
OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-0ubuntu1~18.04.1-b09) 
mysqld  Ver 5.7.28-0ubuntu0.18.04.4 for Linux on x86_64 ((Ubuntu))
OntoPCLI 3.0.1
OntoPWebApps 3.0.1
Apache Tomcat/9.0.27

**Comment by juliencorman** [comment]
Dear Roberto,

The command:
```
./ontop materialize -m exampleBooks.owl -f turtle -o materializedBooks.ttl -p exampleBooks.properties
```
is incorrect.

Option `-m` should precede the mapping file name (like in the command that you gave for ontop query).
So the command to materialize should be:
```
./ontop materialize -m exampleBooks.obda -t  exampleBooks.owl -f turtle -o materializedBooks.ttl -p exampleBooks.properties
```

Can you tell us if you still encounter issues?

Regards,
Julien

**Comment by robertowillrich** [comment]
Thank you !!. It works now

Regards,

Roberto

Em dom., 22 de dez. de 2019 às 20:03, Julien Corman <
notifications@github.com> escreveu:
