### ISSUE TITLE
Ontop with MySql DB Error

### ISSUE THREAD

**Issue by rac021** [ontop/ontop#330]
Hi, 

I have the following  odba file 

```
[SourceDeclaration]
sourceUri	dbEcotronMptMapping
connectionUrl	jdbc:mysql://localhost/earthworm
username	root
password	root
driverClass	com.mysql.jdbc.Driver

[MappingDeclaration] @collection [[

mappingId	MAPPING_TEST
target		<http://ecotronMtp/meas/experimentalProject/name/earthworms> a oboe-core:Measurement .
source		SELECT champ FROM earthworm.tmp;

]]
```

The following SPARQL Query : 
```
SELECT ?S ?P ?O { ?S ?P ?O }
```

Gives me the the follwing error : 

```

java.lang.IllegalArgumentException: Projection source of ProjectionElem "O"
 not found in Extension
   ExtensionElem (O)
      Var (name=O)
   StatementPattern
      Var (name=S)
      Var (name=S)
      Var (name=P)

	at it.unibz.inf.ontop.owlrefplatform.core.translator.SparqlAlgebraToDatalogTranslator.translate(SparqlAlgebraToDatalogTranslator.java:331)
	at it.unibz.inf.ontop.owlrefplatform.core.translator.SparqlAlgebraToDatalogTranslator.translate(SparqlAlgebraToDatalogTranslator.java:103)
	at it.unibz.inf.ontop.owlrefplatform.core.QuestQueryProcessor.getSQL(QuestQueryProcessor.java:134)
	at it.unibz.inf.ontop.owlrefplatform.core.QuestStatement.startExecute(QuestStatement.java:354)
	at it.unibz.inf.ontop.owlrefplatform.core.QuestStatement.executeTupleQuery(QuestStatement.java:318)
	at it.unibz.inf.ontop.owlrefplatform.core.QuestStatement.execute(QuestStatement.java:222)
	at it.unibz.inf.ontop.owlrefplatform.owlapi.QuestOWLStatement.executeTuple(QuestOWLStatement.java:104)
	at ontop.Processor.run(Processor.java:107)
	at ontop.Manager.processMappingOnto(Manager.java:295)
	at ontop.Manager.process(Manager.java:170)
	at entry.Main_1_18.main(Main_1_18.java:134)
Exception in thread "main" it.unibz.inf.ontop.owlapi.OntopOWLException: it.unibz.inf.ontop.model.OBDAException: Error rewriting and unfolding into SQL
Projection source of ProjectionElem "O"
 not found in Extension
   ExtensionElem (O)
      Var (name=O)
   StatementPattern
      Var (name=S)
      Var (name=S)
      Var (name=P)

	at it.unibz.inf.ontop.owlrefplatform.owlapi.QuestOWLStatement.executeTuple(QuestOWLStatement.java:110)
	at ontop.Processor.run(Processor.java:107)
	at ontop.Manager.processMappingOnto(Manager.java:295)
	at ontop.Manager.process(Manager.java:170)
	at entry.Main_1_18.main(Main_1_18.java:134)
Caused by: it.unibz.inf.ontop.model.OBDAException: Error rewriting and unfolding into SQL
Projection source of ProjectionElem "O"
 not found in Extension
   ExtensionElem (O)
      Var (name=O)
   StatementPattern
      Var (name=S)
      Var (name=S)
      Var (name=P)

	at it.unibz.inf.ontop.owlrefplatform.core.translator.SparqlAlgebraToDatalogTranslator.translate(SparqlAlgebraToDatalogTranslator.java:331)
	at it.unibz.inf.ontop.owlrefplatform.core.translator.SparqlAlgebraToDatalogTranslator.translate(SparqlAlgebraToDatalogTranslator.java:103)
	at it.unibz.inf.ontop.owlrefplatform.core.QuestQueryProcessor.getSQL(QuestQueryProcessor.java:134)
	at it.unibz.inf.ontop.owlrefplatform.core.QuestStatement.startExecute(QuestStatement.java:354)
	at it.unibz.inf.ontop.owlrefplatform.core.QuestStatement.executeTupleQuery(QuestStatement.java:318)
	at it.unibz.inf.ontop.owlrefplatform.core.QuestStatement.execute(QuestStatement.java:222)
	at it.unibz.inf.ontop.owlrefplatform.owlapi.QuestOWLStatement.executeTuple(QuestOWLStatement.java:104)
	... 4 more
```

**Comment by juliencorman** [comment]
Hello Rachid,

Could you tell us if the problem persists after adding the "WHERE" keyword to the SPARQL query?
I.e.:
```
SELECT ?S ?P ?O WHERE { ?S ?P ?O .}
```

Thanks,
Julien

**Comment by bcogrel** [comment]
Hello Rachid,

Which version of Ontop are you using? 3.0.1?

Note that the SPARQL translator has been rewritten in Ontop v4. I quickly tested your query on the version4 branch and it was correctly parsed.

Best,
Benjamin

**Comment by rac021** [comment]
Benjamin, I'm using the version 3.0.1 version. I tested the 4.0.0-beta-1 version ( in a java project ) and this gives me the following error : 

```
Exception in thread "main" java.lang.NoClassDefFoundError: Lcom/github/jsonldjava/shaded/com/google/common/collect/ImmutableList;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2611)
	at java.lang.Class.getDeclaredFields(Class.java:1944)
	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:675)
	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:380)
	at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:165)
	at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:616)
	at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:572)
	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:558)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:887)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:808)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:285)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:217)
	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:893)
	at com.google.inject.internal.FactoryProxy.notify(FactoryProxy.java:46)
	at com.google.inject.internal.ProcessedBindingData.runCreationListeners(ProcessedBindingData.java:50)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:134)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at it.unibz.inf.ontop.injection.impl.OntopModelConfigurationImpl.getInjector(OntopModelConfigurationImpl.java:95)
	at it.unibz.inf.ontop.injection.OntopSystemConfiguration.loadQueryEngine(OntopSystemConfiguration.java:18)
	at it.unibz.inf.ontop.owlapi.impl.QuestOWL.<init>(QuestOWL.java:134)
	at it.unibz.inf.ontop.owlapi.impl.QuestOWLFactory.createReasoner(QuestOWLFactory.java:80)
	at it.unibz.inf.ontop.owlapi.impl.QuestOWLFactory.createReasoner(QuestOWLFactory.java:93)
	at ontop.Processor.run(Processor.java:98)
	at ontop.Manager.processMappingOnto(Manager.java:282)
	at ontop.Manager.process(Manager.java:180)
	at entry.Main_4.main(Main_4.java:140)
Caused by: java.lang.ClassNotFoundException: com.github.jsonldjava.shaded.com.google.common.collect.ImmutableList
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 29 more
``` 
It seems alors that the **LIMIT OFFSET** doesn't works with **MYSQL** !!

Thank's 

Rac

**Comment by bcogrel** [comment]
Hi,

Regarding the initial issue, we just figured it out that the SPARQL tree actually corresponds to the following query:
```sql
SELECT ?S ?P ?O { ?S ?S ?P }
```
Before version 4, such query was rejected because ?O is not projected by the WHERE clause. This query is now supported in version 4 as the SPARQL standard allows it (?O will simply never get a value).

#### Dependency issue
Thanks for reporting it, this was due to "dirty" imports in few classes, where a shaded version of the Guava library was used instead of the regular one. It has been cleaned a bit after the beta-1 release. 

Until beta-2 is released, you can use our snapshot Maven modules if you want:
https://oss.sonatype.org/content/repositories/snapshots/it/unibz/inf/ontop/ontop/4.0.0-beta-2-SNAPSHOT/

#### LIMIT OFFSET issue with MySQL
Since the dialect adapters have been rewritten in version 4, the way LIMIT and OFFSET are handled for MySQL may have changed. We will have a look at it.

**Comment by rac021** [comment]
Tank you Benjamin for your reponse,

I tested the version **4.0.0-beta-2-SNAPSHOT** with the following obda file ( **MySql** DB )

```
[PrefixDeclaration]
rdf:                              http://www.w3.org/1999/02/22-rdf-syntax-ns#
oboe-core:                  http://ecoinformatics.org/oboe/oboe.1.0/oboe-core.owl#
xsd:                             http://www.w3.org/2001/XMLSchema#
oboe-temporal:            http://ecoinformatics.org/oboe/oboe.1.0/oboe-temporal.owl#
:                                   http://www.anaee-france.fr/ontology/anaee-france_ontology#
oboe-characteristics:  http://ecoinformatics.org/oboe/oboe.1.0/oboe-characteristics.owl#
oboe-spatial:               http://ecoinformatics.org/oboe/oboe.1.0/oboe-spatial.owl#
oboe-standards:         http://ecoinformatics.org/oboe/oboe.1.0/oboe-standards.owl#
rdfs:                            http://www.w3.org/2000/01/rdf-schema#

[MappingDeclaration] @collection [[

mappingId	Mapping Test
target		<http://ecotronMtp/meas/experimentalProject/name/earthworms> a oboe-core:Measurement .
source		SELECT champ FROM tmp LIMIT 0,10 ; 

]]

```

and the following SPARQL QUERY 

```
SELECT ?S ?P ?O { ?S ?P ?O }
```

But this gives me the following ERROR : 

```

it.unibz.inf.ontop.owlapi.exception.OntopOWLException: it.unibz.inf.ontop.exception.OntopInvalidInputQueryException: org.eclipse.rdf4j.query.MalformedQueryException: Encountered " "." ". "" at line 1, column 36.
Was expecting one of:
    <EOF> 
    "order" ...
    "group" ...
    "limit" ...
    "offset" ...
    "having" ...
    "bindings" ...
    "values" ...
    
	at it.unibz.inf.ontop.owlapi.connection.impl.DefaultOntopOWLStatement.executeSelectQuery(DefaultOntopOWLStatement.java:90)
	at ontop.Processor.run(Processor.java:107)
	at ontop.Manager.process(Manager.java:114)
	at entry.Main_4.main(Main_4.java:140)
Caused by: it.unibz.inf.ontop.exception.OntopInvalidInputQueryException: org.eclipse.rdf4j.query.MalformedQueryException: Encountered " "." ". "" at line 1, column 36.
Was expecting one of:
    <EOF> 
    "order" ...
    "group" ...
    "limit" ...
    "offset" ...
    "having" ...
    "bindings" ...
    "values" ...
    
	at it.unibz.inf.ontop.answering.reformulation.input.impl.InputQueryFactoryImpl.parseQueryString(InputQueryFactoryImpl.java:96)
	at it.unibz.inf.ontop.answering.reformulation.input.impl.InputQueryFactoryImpl.createSelectQuery(InputQueryFactoryImpl.java:24)
	at it.unibz.inf.ontop.owlapi.connection.impl.DefaultOntopOWLStatement.executeSelectQuery(DefaultOntopOWLStatement.java:84)
	... 3 more
Caused by: org.eclipse.rdf4j.query.MalformedQueryException: Encountered " "." ". "" at line 1, column 36.
Was expecting one of:
    <EOF> 
    "order" ...
    "group" ...
    "limit" ...
    "offset" ...
    "having" ...
    "bindings" ...
    "values" ...
    
	at org.eclipse.rdf4j.query.parser.sparql.SPARQLParser.parseQuery(SPARQLParser.java:183)
	at org.eclipse.rdf4j.query.parser.QueryParserUtil.parseQuery(QueryParserUtil.java:93)
	at it.unibz.inf.ontop.answering.reformulation.input.impl.InputQueryFactoryImpl.parseQueryString(InputQueryFactoryImpl.java:94)
	... 5 more
Caused by: org.eclipse.rdf4j.query.parser.sparql.ast.ParseException: Encountered " "." ". "" at line 1, column 36.
Was expecting one of:
    <EOF> 
    "order" ...
    "group" ...
    "limit" ...
    "offset" ...
    "having" ...
    "bindings" ...
    "values" ...
    
	at org.eclipse.rdf4j.query.parser.sparql.ast.SyntaxTreeBuilder.generateParseException(SyntaxTreeBuilder.java:10298)
	at org.eclipse.rdf4j.query.parser.sparql.ast.SyntaxTreeBuilder.jj_consume_token(SyntaxTreeBuilder.java:10148)
	at org.eclipse.rdf4j.query.parser.sparql.ast.SyntaxTreeBuilder.QueryContainer(SyntaxTreeBuilder.java:225)
	at org.eclipse.rdf4j.query.parser.sparql.ast.SyntaxTreeBuilder.parseQuery(SyntaxTreeBuilder.java:37)
	at org.eclipse.rdf4j.query.parser.sparql.SPARQLParser.parseQuery(SPARQLParser.java:144)
	... 7 more
 
 Elapsed seconds : 5 s

```

**Comment by kontchakov** [comment]
Hi

Remove the . after the query. It should literally be "SELECT ?S ?P ?O { ?S ?P ?O }", without any quotation marks and without any dots around.

Best
Roman

**Comment by rac021** [comment]
Perfect, **works fine** with the **4.0.0-beta-2-SNAPSHOT** version

I have an other issue : 

Sometimes, I don't need to retrieve data from the database, for that, I would just like to execute simple sql query like ( **SELECT '1' AS ID** ) but it doesn't work

```
[MappingDeclaration] @collection [[

mappingId	MAPPING_TEST
target		<http://ecotronMtp/meas/experimentalProject/name/earthworms> a oboe-core:Measurement .
source		SELECT '1' AS  _id_

]]

```
Error : 

```
Error in mapping with id: MAPPING_TEST 
 Description: null 
Mapping: [id: MAPPING_TEST
target atoms: triple(s,p,o) with s/<http://ecotronMtp/meas/experimentalProject/name/earthworms>, p/<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>, o/<http://ecoinformatics.org/oboe/oboe.1.0/oboe-core.owl#Measurement>
source query: SELECT '1' AS _id_ ]

	at it.unibz.inf.ontop.spec.dbschema.impl.SQLTableNameExtractor.getRealTables(SQLTableNameExtractor.java:83)
	at it.unibz.inf.ontop.spec.dbschema.impl.DefaultRDBMetadataExtractor.extract(DefaultRDBMetadataExtractor.java:90)
	at it.unibz.inf.ontop.spec.dbschema.impl.DefaultRDBMetadataExtractor.extract(DefaultRDBMetadataExtractor.java:56)
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.extractDBMetadata(SQLMappingExtractor.java:161)
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convertPPMapping(SQLMappingExtractor.java:93)
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convertPPMapping(SQLMappingExtractor.java:41)
	at it.unibz.inf.ontop.spec.mapping.impl.AbstractMappingExtractor.extract(AbstractMappingExtractor.java:72)
	at it.unibz.inf.ontop.spec.mapping.impl.AbstractMappingExtractor.extract(AbstractMappingExtractor.java:43)
	at it.unibz.inf.ontop.spec.impl.DefaultOBDASpecificationExtractor.extract(DefaultOBDASpecificationExtractor.java:38)
	at it.unibz.inf.ontop.injection.impl.OntopMappingConfigurationImpl.loadSpecification(OntopMappingConfigurationImpl.java:129)
	at it.unibz.inf.ontop.injection.impl.OntopMappingSQLConfigurationImpl.loadSpecification(OntopMappingSQLConfigurationImpl.java:85)
	at it.unibz.inf.ontop.injection.impl.OntopMappingSQLAllConfigurationImpl.loadSpecification(OntopMappingSQLAllConfigurationImpl.java:48)
	at it.unibz.inf.ontop.injection.impl.OntopSQLOWLAPIConfigurationImpl.loadOBDASpecification(OntopSQLOWLAPIConfigurationImpl.java:34)
	at it.unibz.inf.ontop.injection.impl.OntopOBDAConfigurationImpl.loadSpecification(OntopOBDAConfigurationImpl.java:44)
	at it.unibz.inf.ontop.injection.OntopSystemConfiguration.loadQueryEngine(OntopSystemConfiguration.java:20)
	at it.unibz.inf.ontop.owlapi.impl.QuestOWL.<init>(QuestOWL.java:134)
	at it.unibz.inf.ontop.owlapi.impl.QuestOWLFactory.createReasoner(QuestOWLFactory.java:80)
	at it.unibz.inf.ontop.owlapi.impl.QuestOWLFactory.createReasoner(QuestOWLFactory.java:93)
	at ontop.Processor.run(Processor.java:98)
	at ontop.Manager.processMapping(Manager.java:331)
	at ontop.Manager.process(Manager.java:218)
	at entry.Main_4.main(Main_4.java:140)


```

Nb: This works fine with **postgresql** using : **SELECT __id__ FROM (VALUES ('1')**

**Comment by juliencorman** [comment]
Hello Rachid,

A simpler option may be to add the desired RDF triples to your ontology.
E.g. add to your owl file the triple:
```
<http://ecotronMtp/meas/experimentalProject/name/earthworms> a oboe-core:Measurement .
```

Regards,
Julien
