### ISSUE TITLE
ORA-00933: SQL command not properly ended

### ISSUE THREAD

**Issue by Jimflip** [ontop/ontop#341]
I thought I would upgrade to the 4.0 rc1 plugin for Protege.
Now even the simplest mapping used in Ontop SPARQL view produces:

```
ERROR OBDADataQueryAction    it.unibz.inf.ontop.exception.OntopQueryEvaluationException: java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

it.unibz.inf.ontop.owlapi.exception.OntopOWLException: it.unibz.inf.ontop.exception.OntopQueryEvaluationException: java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended
```
I'm unable to see what the actual SQL generated by Ontop is.
This is for an Oracle 11 database, which all works fine with Ontop 3.0.1 Protege Plugin.

Thanks,
James.

**Comment by bcogrel** [comment]
Hi James,

Could you please provide us some elements of the log in debug mode? In particular, the generated SQL query would be interesting. Instructions can be found at https://ontop-vkg.org/community/contributing/bug-report.html#how-to-generate-the-log-file

By chance, are you putting a semicolon character at the end of some queries in the mapping file?

Best,
Benjamin

**Comment by Jimflip** [comment]
Hi @bcogrel 

Not adding a semicolon to the mapping files, the UI reports that as invalid (I did try to see if it would help).

So this issue seems to occur only when I add a LIMIT to the SPARQL query.
i.e.
```
SELECT * WHERE
{
	?s ?p ?o .
} LIMIT 100
```
Fails, but
```
SELECT * WHERE
{
	?s ?p ?o .
}
```
works.

Log output:
```
PREFIX : <https://ont.itv.com/>

SELECT * WHERE
{
	?s ?p ?o .
} LIMIT 100
  DEBUG  23:13:54  Executing the query and get the result...
  ERROR  23:13:54  java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

it.unibz.inf.ontop.exception.OntopQueryEvaluationException: java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

	at it.unibz.inf.ontop.answering.connection.impl.SQLQuestStatement.executeSelectQuery(SQLQuestStatement.java:197) ~[na:na]
	at it.unibz.inf.ontop.answering.connection.impl.QuestStatement.executeSelectQuery(QuestStatement.java:135) ~[na:na]
	at it.unibz.inf.ontop.answering.connection.impl.QuestStatement$QueryExecutionThread.run(QuestStatement.java:115) ~[na:na]
Caused by: java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509) ~[na:na]
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461) ~[na:na]
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104) ~[na:na]
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:553) ~[na:na]
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:269) ~[na:na]
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655) ~[na:na]
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:229) ~[na:na]
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:41) ~[na:na]
	at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:765) ~[na:na]
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:983) ~[na:na]
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1168) ~[na:na]
	at oracle.jdbc.driver.OracleStatement.executeQuery(OracleStatement.java:1362) ~[na:na]
	at oracle.jdbc.driver.OracleStatementWrapper.executeQuery(OracleStatementWrapper.java:369) ~[na:na]
	at it.unibz.inf.ontop.answering.connection.impl.SQLQuestStatement.executeSelectQuery(SQLQuestStatement.java:191) ~[na:na]
	... 2 common frames omitted
Caused by: oracle.jdbc.OracleDatabaseException: ORA-00933: SQL command not properly ended

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:513) ~[na:na]
	... 15 common frames omitted
  ERROR  23:13:54  it.unibz.inf.ontop.exception.OntopQueryEvaluationException: java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

it.unibz.inf.ontop.owlapi.exception.OntopOWLException: it.unibz.inf.ontop.exception.OntopQueryEvaluationException: java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

	at it.unibz.inf.ontop.owlapi.connection.impl.DefaultOntopOWLStatement.executeSelectQuery(DefaultOntopOWLStatement.java:90) ~[na:na]
	at it.unibz.inf.ontop.protege.views.QueryInterfaceView$2.executeQuery(QueryInterfaceView.java:217) ~[na:na]
	at it.unibz.inf.ontop.protege.views.QueryInterfaceView$2.executeQuery(QueryInterfaceView.java:170) ~[na:na]
	at it.unibz.inf.ontop.protege.gui.action.OBDADataQueryAction.lambda$runAction$0(OBDADataQueryAction.java:157) ~[na:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
Caused by: it.unibz.inf.ontop.exception.OntopQueryEvaluationException: java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

	at it.unibz.inf.ontop.answering.connection.impl.SQLQuestStatement.executeSelectQuery(SQLQuestStatement.java:197) ~[na:na]
	at it.unibz.inf.ontop.answering.connection.impl.QuestStatement.executeSelectQuery(QuestStatement.java:135) ~[na:na]
	at it.unibz.inf.ontop.answering.connection.impl.QuestStatement$QueryExecutionThread.run(QuestStatement.java:115) ~[na:na]
Caused by: java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509) ~[na:na]
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461) ~[na:na]
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104) ~[na:na]
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:553) ~[na:na]
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:269) ~[na:na]
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655) ~[na:na]
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:229) ~[na:na]
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:41) ~[na:na]
	at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:765) ~[na:na]
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:983) ~[na:na]
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1168) ~[na:na]
	at oracle.jdbc.driver.OracleStatement.executeQuery(OracleStatement.java:1362) ~[na:na]
	at oracle.jdbc.driver.OracleStatementWrapper.executeQuery(OracleStatementWrapper.java:369) ~[na:na]
	at it.unibz.inf.ontop.answering.connection.impl.SQLQuestStatement.executeSelectQuery(SQLQuestStatement.java:191) ~[na:na]
	... 2 common frames omitted
Caused by: oracle.jdbc.OracleDatabaseException: ORA-00933: SQL command not properly ended

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:513) ~[na:na]
	... 15 common frames omitted

```

**Comment by Jimflip** [comment]
Here is the SQL Translation
```
ans1(s,p,o)
CONSTRUCT [s, p, o] [p/RDF(v1,IRI), s/RDF(https://ont.itv.com/paris/Person/LAU-{}(NUMBERToVARCHAR2(SYSTEM_KEY1m0)),IRI), o/RDF(CONTACT1m3,RDF_TYPE{1=xsd:string,0=IRI}(v0))]
   NATIVE [CONTACT1m3, SYSTEM_KEY1m0, v0, v1]
SELECT V5."CONTACT1m3" AS "CONTACT1m3", V5."SYSTEM_KEY1m0" AS "SYSTEM_KEY1m0", V5."v0" AS "v0", V5."v1" AS "v1"
FROM (SELECT 'https://ont.itv.com/Person' AS "CONTACT1m3", V1."SYSTEM_KEY" AS "SYSTEM_KEY1m0", 0 AS "v0", 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type' AS "v1"
FROM "PARIS_SCHEMA"."LICENCE_ADDRESS_USAGES" V1
WHERE (V1."CONTACT" <> 'X' AND V1."CONTACT" <> '-' AND V1."CONTACT" <> '_' AND V1."CONTACT" IS NOT NULL)
UNION ALL 
SELECT V3."CONTACT" AS "CONTACT1m3", V3."SYSTEM_KEY" AS "SYSTEM_KEY1m0", 1 AS "v0", 'https://ont.itv.com/givenName' AS "v1"
FROM "PARIS_SCHEMA"."LICENCE_ADDRESS_USAGES" V3
WHERE (V3."CONTACT" IS NOT NULL AND V3."CONTACT" <> 'X' AND V3."CONTACT" <> '-' AND V3."CONTACT" <> '_')
) V5
```

**Comment by bcogrel** [comment]
Hi James,

Thanks for your feedback, it helped us to spot the issue.

The problem seems to come from the way Ontop currently translates LIMIT (and OFFSET), which is supported by Oracle since its 12th version. In previous versions (including 11), one had to use the special ROWNUM as a filter condition (https://blogs.oracle.com/oraclemagazine/on-rownum-and-limiting-results).

For Ontop 4.0.0, we gave priority to the recent and supported versions of the DB systems. Even if the latest release of Oracle 11 is almost 11 years old, we would like to support it, as its installation base seems to remain important. I will open a dedicated issue.

Best,
Benjamin

**Comment by Jimflip** [comment]
Thanks @bcogrel 
Good to hear you would like to support older versions, I suspect using OBDA has a lot to offer by helping transform heritage systems.
