### ISSUE TITLE
Mapping fails on SQL - union

### ISSUE THREAD

**Issue by qootec** [ontop/ontop#366]
### Description

Unable to create a single triple template that load individuals from the union of three tables. 

### Steps to Reproduce

1. Ontology contains Class "Rotor" having one data property rotorID of type xsd::string
2. Rotor instances can be found in several tables, so I want to join them.
3. Edit the desired mapping
target
:asset/rotor/{rotorID} a :Rotor ; :rotorID {rotorID}^^xsd:string .
source
select distinct rotorID from 
(select zpolrotorid as rotorID from LinkData
union
select abomSerialNumberMale as rotorID from AssemblyData
union
select abomSerialNumberFemale as rotorID from AssemblyData) as R
`

**Expected behavior:**

Rotor instances are collected from the two tables (and two columns on the latter table).

**Actual behavior:**

When starting the Ontop Reasoner in Ontop, the following exception occurs:

``Caused by: it.unibz.inf.ontop.exception.InvalidMappingSourceQueriesException: The placeholder(s) rotorID in the target do(es) not occur in source query of the mapping assertion
[id: mapAssetRotor
target atom: triple(s,p,o) with s/RDF(http://www.flandersmake.be/dtdesign/sbooven#asset/rotor/{}(TmpToTEXT(rotorID)),IRI), p/<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>, o/<http://www.flandersmake.be/dtdesign/sbooven#Rotor>``

source query: select distinct rotorID from
(select zpolrotorid as rotorID from LinkData
union
select abomSerialNumberMale as rotorID from AssemblyData
union
select abomSerialNumberFemale as rotorID from AssemblyData) as R]
        at it.unibz.inf.ontop.spec.mapping.pp.impl.SQLPPMappingConverterImpl.convert(SQLPPMappingConverterImpl.java:120) ~[na:na]
        at it.unibz.inf.ontop.spec.mapping.pp.impl.SQLPPMappingConverterImpl.convert(SQLPPMappingConverterImpl.java:83) ~[na:na]
        at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convert(SQLMappingExtractor.java:185) ~[na:na]
        at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convertPPMapping(SQLMappingExtractor.java:146) ~[na:na]
        at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.extract(SQLMappingExtractor.java:111) ~[na:na]
        at it.unibz.inf.ontop.spec.impl.DefaultOBDASpecificationExtractor.extract(DefaultOBDASpecificationExtractor.java:55) ~[na:na]
        at it.unibz.inf.ontop.injection.impl.OntopMappingConfigurationImpl.loadSpecification(OntopMappingConfigurationImpl.java:116) ~[na:na]
        at it.unibz.inf.ontop.injection.impl.OntopMappingSQLConfigurationImpl.loadSpecification(OntopMappingSQLConfigurationImpl.java:84) ~[na:na]
        at it.unibz.inf.ontop.injection.impl.OntopMappingSQLAllConfigurationImpl.loadSpecification(OntopMappingSQLAllConfigurationImpl.java:47) ~[na:na]
        at it.unibz.inf.ontop.injection.impl.OntopSQLOWLAPIConfigurationImpl.loadOBDASpecification(OntopSQLOWLAPIConfigurationImpl.java:34) ~[na:na]
        at it.unibz.inf.ontop.injection.impl.OntopOBDAConfigurationImpl.loadSpecification(OntopOBDAConfigurationImpl.java:44) ~[na:na]
        at it.unibz.inf.ontop.injection.OntopSystemConfiguration.loadQueryEngine(OntopSystemConfiguration.java:20) ~[na:na]
        at it.unibz.inf.ontop.owlapi.impl.QuestOWL.<init>(QuestOWL.java:134) ~[na:na]
        ... 8 common frames omitted

**Reproduces how often:**

Every time

### Versions

* Protégé 5.5.0
* Ontop Protégé plugin 4.0.3

**Comment by kontchakov** [comment]
I suggest you split the mapping into 3:
target
:asset/rotor/{rotorID} a :Rotor ; :rotorID {rotorID}^^xsd:string .
source
select zpolrotorid as rotorID from LinkData

target
:asset/rotor/{rotorID} a :Rotor ; :rotorID {rotorID}^^xsd:string .
source
select abomSerialNumberMale as rotorID from AssemblyData

target
:asset/rotor/{rotorID} a :Rotor ; :rotorID {rotorID}^^xsd:string .
source
select abomSerialNumberFemale as rotorID from AssemblyData

Ontop treats any complex SQL queries (for example, containing union or distinct) as black boxes and does not apply any optimizations.

**Comment by qootec** [comment]
That is what I did as a workaround, but I still consider this inability as a bug, no?

**Comment by qootec** [comment]
By the way, at the risk of hijacking my own issue. I have the impression that the slightly modified version of your suggestion would not work (see below). 
It seems that if the tables LinkData and AssemblyData would both contain an instance 'rotor1', Ontop would still consider both created individuals as different, although the resulting IRIs would be identical. 
If we rename the fields (... as rotorID), then the IRIs are considered identical. 
Is that expected?

:asset/rotor/{zpolrotorid } a :Rotor ; :rotorID {zpolrotorid }^^xsd:string .
source
select zpolrotorid from LinkData

target
:asset/rotor/{abomSerialNumberMale } a :Rotor ; :rotorID {abomSerialNumberMale }^^xsd:string .
source
select abomSerialNumberMale from AssemblyData

target
:asset/rotor/{abomSerialNumberFemale } a :Rotor ; :rotorID {abomSerialNumberFemale }^^xsd:string .
source
select abomSerialNumberFemale from AssemblyData

**Comment by kontchakov** [comment]
Well, you original query is not terribly efficient - it eliminates duplicates once with UNION (UNION ALL would avoid that), and then again with DISTINCT. In fact, any mapping query is "given" a DISTINCT anyway by Ontop because RDF graphs are sets of RDF triples, and so duplicates from queries need to be eliminated.

**Comment by kontchakov** [comment]
Can you please elaborate on "consider both created individuals as different, although the resulting IRIs would be identical"?

**Comment by kontchakov** [comment]
The bug (not recognizing DISTINCT in black-box views) is fixed by commit 4edfa7052be8f42a215a5f261520a0f7f5ce03d6.

**Comment by qootec** [comment]
> Can you please elaborate on "consider both created individuals as different, although the resulting IRIs would be identical"?

It has cost me some time to clearly pinpoint this problem. 
It feels inappropriate though to hijack this issue for that purpose.
You fixed the original issue, so I'll close this issue.
For the 'hijack', I've opened #367.
