### ISSUE TITLE
Ontop cli materialize gives InvalidMappingSourceQueriesException for MySQL database

### ISSUE THREAD

**Issue by Omer95** [ontop/ontop#369]
### Description

I want to dump RDF triples into a .nt file using ontop materialize for a MySQL database. I've used the tool [MIRROR ](https://github.com/oeg-upm/MIRROR) to generate the R2RML mappings and created a simple properties file to connect to the MySQL database. When I run the ontop.bat materialize command, I get the following error:

```
C:\...\r2rml-ontop>ontop.bat materialize -m demo2.ttl -f ntriples -o materialized-demo.nt -p basic.properties
Picked up _JAVA_OPTIONS: -Djavax.net.ssl.trustStore=C:\Windows\Sun\Java\Deployment\trusted.certs
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/C:/.../r2rml-ontop/lib/guice-4.1.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.RuntimeException: it.unibz.inf.ontop.exception.InvalidMappingSourceQueriesException: Error: Relation IDs mismatch: `student` v `demo`.`student`(null v `demo`) `student`
Problem location: source query of triplesMap
[id: mapping--1907035582
target atoms: triple(s,p,o) with s/RDF(http://example.com/{}(TmpToTEXT("Name")),IRI), p/<http://xmlns.com/foaf/0.1/name>, o/RDF(TmpToTEXT("Name"),rdfs:Literal)
source query: SELECT * FROM "student"]
        at it.unibz.inf.ontop.cli.OntopMaterialize.createMaterializer(OntopMaterialize.java:124)
        at it.unibz.inf.ontop.cli.OntopMaterialize.run(OntopMaterialize.java:99)
        at it.unibz.inf.ontop.cli.Ontop.main(Ontop.java:18)
Caused by: it.unibz.inf.ontop.exception.InvalidMappingSourceQueriesException: Error: Relation IDs mismatch: `student` v `demo`.`student`(null v `demo`) `student`
Problem location: source query of triplesMap
[id: mapping--1907035582
target atoms: triple(s,p,o) with s/RDF(http://example.com/{}(TmpToTEXT("Name")),IRI), p/<http://xmlns.com/foaf/0.1/name>, o/RDF(TmpToTEXT("Name"),rdfs:Literal)
source query: SELECT * FROM "student"]
        at it.unibz.inf.ontop.spec.mapping.pp.impl.SQLPPMappingConverterImpl.getRAExpression(SQLPPMappingConverterImpl.java:188)
        at it.unibz.inf.ontop.spec.mapping.pp.impl.SQLPPMappingConverterImpl.convert(SQLPPMappingConverterImpl.java:72)
        at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convert(SQLMappingExtractor.java:185)
        at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convertPPMapping(SQLMappingExtractor.java:146)
        at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.extract(SQLMappingExtractor.java:102)
        at it.unibz.inf.ontop.spec.impl.DefaultOBDASpecificationExtractor.extract(DefaultOBDASpecificationExtractor.java:40)
        at it.unibz.inf.ontop.injection.impl.OntopMappingConfigurationImpl.loadSpecification(OntopMappingConfigurationImpl.java:127)
        at it.unibz.inf.ontop.injection.impl.OntopMappingSQLConfigurationImpl.loadSpecification(OntopMappingSQLConfigurationImpl.java:84)
        at it.unibz.inf.ontop.injection.impl.OntopMappingSQLAllConfigurationImpl.loadSpecification(OntopMappingSQLAllConfigurationImpl.java:47)
        at it.unibz.inf.ontop.injection.impl.OntopSQLOWLAPIConfigurationImpl.loadOBDASpecification(OntopSQLOWLAPIConfigurationImpl.java:34)
        at it.unibz.inf.ontop.injection.impl.OntopOBDAConfigurationImpl.loadSpecification(OntopOBDAConfigurationImpl.java:44)
        at it.unibz.inf.ontop.materialization.impl.DefaultOntopRDFMaterializer.<init>(DefaultOntopRDFMaterializer.java:48)
        at it.unibz.inf.ontop.rdf4j.materialization.impl.DefaultRDF4JMaterializer.<init>(DefaultRDF4JMaterializer.java:57)
        at it.unibz.inf.ontop.rdf4j.materialization.RDF4JMaterializer.defaultMaterializer(RDF4JMaterializer.java:34)
        at it.unibz.inf.ontop.cli.OntopMaterialize.createMaterializer(OntopMaterialize.java:118)
        ... 2 more
```

### Steps to Reproduce

1. The demo2.ttl R2RML mapping file looks like this:
```
@prefix rr: <http://www.w3.org/ns/r2rml#> .
@prefix rev: <http://purl.org/stuff/rev#> .
@prefix bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix foaf: <http://xmlns.com/foaf/0.1#> .
@prefix dc: <http://purl.org/stuff/rev#> .
@prefix bsbm-inst: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/> .
@prefix ex: <http://example.com/> .

@base <http://mappingpedia.org/rdb2rdf/r2rml/tc/> .

<#TriplesMap1>
	a rr:TriplesMap;

	rr:logicalTable [ 
		rr:tableName "\"student\""; 
	];

	rr:subjectMap [
		rr:template "example.com//student/Name={\"Name\"}";
		rr:termType rr:BlankNode;
		rr:class <http://example.com/student>;
	];

	rr:predicateObjectMap [
		rr:predicate <http://example.com/student#name>;
		rr:objectMap [ rr:column "\"Name\""; rr:datatype xsd:string; ];
	].

<#TriplesMap2>
	a rr:TriplesMap;

	rr:logicalTable [ 
		rr:sqlQuery "SELECT 1 FROM INFORMATION_SCHEMA.TABLES LIMIT 1" 
	];

	rr:subjectMap [
		rr:constant <http://example.com/student>;
		rr:termType rr:IRI;
		rr:class owl:Class;
	];

	rr:predicateObjectMap [
		rr:predicate rdfs:subClassOf;
		rr:objectMap [ rr:constant owl:Thing ];
	].

<#TriplesMap3>
	a rr:TriplesMap;

	rr:logicalTable [ 
		rr:sqlQuery "SELECT 1 FROM INFORMATION_SCHEMA.TABLES LIMIT 1" 
	];

	rr:subjectMap [
		rr:constant <http://example.com/student#name>;
		rr:termType rr:IRI;
		rr:class owl:DatatypeProperty;
	];

	rr:predicateObjectMap [
		rr:predicate rdfs:domain;
		rr:objectMap [ rr:constant <http://example.com/student> ];
	];

	rr:predicateObjectMap [
		rr:predicate rdfs:range;
		rr:objectMap [ rr:constant xsd:string ];
	].
```
2. The basic.properties files:
```
jdbc.name=demo

jdbc.url=jdbc:mysql://127.0.0.1/
jdbc.user=root

jdbc.password=omer
```
3. The command I run:
`ontop.bat materialize -m demo2.ttl -f ntriples -o materialized-demo.nt -p basic.properties`

**Expected behavior:**
I expect to see the materialized-demo.nt file with generated n-triples

**Actual behavior:**
I get the error in the description

**Reproduces how often:**
Everytime

### Attached material

SQL query to generate the student table:
```
CREATE TABLE student (
Name varchar(50)
);
INSERT INTO student VALUES ("Venus");
```

### Versions

Ontop CLI 4.0.3

**Comment by kontchakov** [comment]
Hi Omer

What is the version of MySQL connector?

Thanks
Roman

**Comment by Omer95** [comment]
@kontchakov sorry I'm using MySQL Community Server v 8.0.22 for Windows

**Comment by kontchakov** [comment]
Try specifying the database component of your connection URL:

jdbc.url=jdbc:mysql://127.0.0.1/demo

**Comment by Omer95** [comment]
@kontchakov that worked thanks!
