### ISSUE TITLE
DISTINCT with ORDER BY (Spark SQL)

### ISSUE THREAD

**Issue by LorenzBuehmann** [ontop/ontop#411]
Hi,

as the title indicates, I do have a question regarding the behaviour of the SQL generator. 
Given a SPARQL query
```
PREFIX  :     <http://example.org/>

SELECT DISTINCT  ?s
WHERE
  { ?s  :p4  ?o }
ORDER BY DESC(?s)
```
applied to a schema with a single table `t1 (s [String], o [String])` only

I'm getting the following SQL query
```
SELECT DISTINCT `v1`.`s` AS `s1m4`, `v1`.`s` AS `v0`
FROM `t1` `v1`
ORDER BY `v1`.`s` DESC NULLS LAST
```

The problem with this query is that - as far as I know - some databases might fail because of the extended sort key here. At least, Apache Spark SQL isn't smart enough to get that the alias `v0` is equal to `v1.s` - I know this is dumb but I also know that some databases do have those restrictions. ( a nice article regarding this is [here](https://blog.jooq.org/2018/07/13/how-sql-distinct-and-order-by-are-related/) )
So my question, is there any existing implementation that does project the sort key?

I'm also wondering why the generated SQL query does project the same column twice?

I'll provide the query reformulation here, maybe it's relevant:

```
DEBUG [ScalaTest-run-running-QuotationTests] (QuestQueryProcessor.java:93) - SPARQL query:
PREFIX  :     <http://example.org/>

SELECT DISTINCT  ?s
WHERE
  { ?s  :p4  ?o }
ORDER BY DESC(?s)

DEBUG [ScalaTest-run-running-QuotationTests] (QuestQueryProcessor.java:95) - Parsed query converted into IQ (after normalization):
ans1(s)
DISTINCT
   CONSTRUCT [s] []
      ORDER BY [DESC(s)]
         INTENSIONAL triple(s,<http://example.org/p4>,o)

DEBUG [ScalaTest-run-running-QuotationTests] (QuestQueryProcessor.java:100) - Start the rewriting process...
DEBUG [ScalaTest-run-running-QuotationTests] (QuestQueryProcessor.java:104) - Rewritten IQ:
ans1(s)
DISTINCT
   CONSTRUCT [s] []
      ORDER BY [DESC(s)]
         INTENSIONAL triple(s,<http://example.org/p4>,o)

DEBUG [ScalaTest-run-running-QuotationTests] (QuestQueryProcessor.java:106) - Start the unfolding...
DEBUG [ScalaTest-run-running-QuotationTests] (QuestQueryProcessor.java:117) - Unfolded query: 
ans1(s)
DISTINCT
   CONSTRUCT [s] []
      ORDER BY [DESC(s)]
         CONSTRUCT [s, o] [s/RDF(VARCHARToSTRING(s1m4),IRI), o/RDF(VARCHARToSTRING(o1m4),xsd:string)]
            DISTINCT
               EXTENSIONAL "t1"(0:s1m4,1:o1m4)

DEBUG [ScalaTest-run-running-QuotationTests] (QuestQueryProcessor.java:122) - Planned query: 
ans1(s)
CONSTRUCT [s] [s/RDF(VARCHARToSTRING(s1m4),IRI)]
   DISTINCT
      ORDER BY [DESC(VARCHARToSTRING(s1m4))]
         EXTENSIONAL "t1"(0:s1m4)

DEBUG [ScalaTest-run-running-QuotationTests] (QuestQueryProcessor.java:152) - Producing the native query string...
DEBUG [ScalaTest-run-running-QuotationTests] (QuestQueryProcessor.java:157) - Resulting native query: 
ans1(s)
CONSTRUCT [s] [s/RDF(VARCHARToSTRING(s1m4),IRI)]
   NATIVE [s1m4, v0]
SELECT DISTINCT `v1`.`s` AS `s1m4`, `v1`.`s` AS `v0`
FROM `t1` `v1`
ORDER BY `v1`.`s` DESC NULLS LAST
```

Cheers

**Comment by bcogrel** [comment]
Hi Lorenz,

Yes, it is indeed common for SQL dialects to have restrictions on the simultaneous usage of DISTINCT and ORDER BY. To handle this kind of restrictions, we usually use a `DialectExtraNormalizer` (see https://ontop-vkg.org/dev/db-adapter#normalizer).

We are having two variants for projecting extra variables: `AlwaysProjectOrderByTermsNormalizer` (used for SQL server, H2 and Denodo) or `OnlyInPresenceOfDistinctProjectOrderByTermsNormalizer` (used for MySQL and PostgreSQL).

Regarding the second variable, it could indeed have been avoided (probably introduced during the normalization done by `SQLGeneratorImpl` or when splitting the top `ConstructionNode` from the rest). Do you think its presence is causing problem?

How shall the generated SQL query be modified so as to please Spark?

Best,
Benjamin

**Comment by LorenzBuehmann** [comment]
Hi Benjamin,

well currently the Spark execution plan look like this:

```
org.apache.spark.sql.AnalysisException: cannot resolve '`v1.s`' given input columns: [s1m4, v0]; line 3 pos 9;
'Sort ['v1.s DESC NULLS LAST], true
+- Distinct
   +- Project [s#47 AS s1m4#177, s#47 AS v0#178]
      +- SubqueryAlias v1
         +- SubqueryAlias t1
            +- LogicalRDD [s#47, o#48, l#49], false
```
so it doesn't look for the origin of the alias. On the other hand, it does work if I manually change the query to use one of the resolved projected variables, i.e. either `s1m4` or `v0`.
For example

``` sql
SELECT DISTINCT `v1`.`s` AS `s1m4`, `v1`.`s` AS `v0`
FROM `t1` `v1`
ORDER BY `v0` DESC NULLS LAST
```
works.
From my point of view that's a rather odd limitation of the Spark SQL analyzer, though, to be fair I do not know the ideas and implications behind.

Not sure if you have already something to force using the alias of projected variables or where I should start. Currently, we do have a workaround in our `SelectFromWhereSerializer` and in `serializeOrderBy` method we do replace all sort conditions with the alias of projected variables (if exist) - this indeed feels rather hackish and might be error prone. At least I do not have tested much and wanted to ask you for possibly existing implementations. If not, I'll go with the workaround I guess.

Regarding the second variable, I don't think it does cause problems, it just looks redundant.

I dug into the `ProjectOrderByTermsNormalizer` class, and it looks like the second variable is introduced here in the `normalize` method because:
- the `analysis.sortConditions` does contain a term `VARCHARToSTRING(s1m4)`, so it wraps the variable `s1m4`
- the `alreadyDefinedTerms` contains `s1m4` as a `Variable`
- this mismatch between the types leads to the `newBindings` being not empty
So I guess, it could be avoided if during containment check those single var `NonGroundFunctionalTerm` objects can be taken into account. For non-expression sort-conditions this should work fine. But it's just a guess ...

**Comment by LorenzBuehmann** [comment]
Hi,

just a follow up issue (feel free to put it into a new issue). 
So, while getting my workaround running (I did modify the the serialization of the sort part by pushing the term serializer to use the var name instead of the `QualifiedAttributeID`) I also tried it with a more complex query with subquery. This leads to a somewhat similar exception to my previously reported issue:

Here the debug output (testMode is enabled):

```
INFO [ScalaTest-run-running-QuotationTests] (QueryEngineOntop.scala:274) - SPARQL query:
PREFIX  :     <http://example.org/>

SELECT DISTINCT  ?o
WHERE
  { ?s  :p3  ?o
    { SELECT DISTINCT  ?s
      WHERE
        { ?s  :p4  ?o }
      ORDER BY DESC(?s)
      LIMIT   1
    }
  }
ORDER BY ?o

DEBUG [ScalaTest-run-running-QuotationTests] (QuestQueryProcessor.java:93) - SPARQL query:
PREFIX  :     <http://example.org/>

SELECT DISTINCT  ?o
WHERE
  { ?s  :p3  ?o
    { SELECT DISTINCT  ?s
      WHERE
        { ?s  :p4  ?o }
      ORDER BY DESC(?s)
      LIMIT   1
    }
  }
ORDER BY ?o

 WARN [ScalaTest-run-running-QuotationTests] (QuestQueryProcessor.java:143) - Unexpected exception: The following non-projected variables [o] are appearing in different children of JOIN: 
[
INTENSIONAL triple(s,<http://example.org/p3>,o), 
SLICE limit=1
   DISTINCT
      CONSTRUCT [s] []
         ORDER BY [DESC(s)]
            INTENSIONAL triple(s,<http://example.org/p4>,o)
]
it.unibz.inf.ontop.iq.exception.InvalidIntermediateQueryException: The following non-projected variables [o] are appearing in different children of JOIN: 
[
INTENSIONAL triple(s,<http://example.org/p3>,o), 
SLICE limit=1
   DISTINCT
      CONSTRUCT [s] []
         ORDER BY [DESC(s)]
            INTENSIONAL triple(s,<http://example.org/p4>,o)
]
	at it.unibz.inf.ontop.iq.node.impl.JoinLikeNodeImpl.checkNonProjectedVariables(JoinLikeNodeImpl.java:80)
	at it.unibz.inf.ontop.iq.node.impl.InnerJoinNodeImpl.validateNode(InnerJoinNodeImpl.java:335)
	at it.unibz.inf.ontop.iq.impl.NaryIQTreeImpl.validateNode(NaryIQTreeImpl.java:64)
	at it.unibz.inf.ontop.iq.impl.AbstractCompositeIQTree.validate(AbstractCompositeIQTree.java:235)
	at it.unibz.inf.ontop.iq.impl.NaryIQTreeImpl.<init>(NaryIQTreeImpl.java:50)
	at it.unibz.inf.ontop.iq.impl.NaryIQTreeImpl.<init>(NaryIQTreeImpl.java:59)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.google.inject.internal.DefaultConstructionProxyFactory$2.newInstance(DefaultConstructionProxyFactory.java:86)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at com.google.inject.assistedinject.FactoryProvider2.invoke(FactoryProvider2.java:770)
	at com.sun.proxy.$Proxy48.createNaryIQTree(Unknown Source)
	at it.unibz.inf.ontop.answering.reformulation.input.translation.impl.RDF4JInputQueryTranslatorImpl.getJoinTree(RDF4JInputQueryTranslatorImpl.java:763)
	at it.unibz.inf.ontop.answering.reformulation.input.translation.impl.RDF4JInputQueryTranslatorImpl.buildJoinQuery(RDF4JInputQueryTranslatorImpl.java:735)
	at it.unibz.inf.ontop.answering.reformulation.input.translation.impl.RDF4JInputQueryTranslatorImpl.translateJoinLikeNode(RDF4JInputQueryTranslatorImpl.java:633)
	at it.unibz.inf.ontop.answering.reformulation.input.translation.impl.RDF4JInputQueryTranslatorImpl.translate(RDF4JInputQueryTranslatorImpl.java:161)
	at it.unibz.inf.ontop.answering.reformulation.input.translation.impl.RDF4JInputQueryTranslatorImpl.translateOrder(RDF4JInputQueryTranslatorImpl.java:379)
	at it.unibz.inf.ontop.answering.reformulation.input.translation.impl.RDF4JInputQueryTranslatorImpl.translate(RDF4JInputQueryTranslatorImpl.java:200)
	at it.unibz.inf.ontop.answering.reformulation.input.translation.impl.RDF4JInputQueryTranslatorImpl.translateProjection(RDF4JInputQueryTranslatorImpl.java:774)
	at it.unibz.inf.ontop.answering.reformulation.input.translation.impl.RDF4JInputQueryTranslatorImpl.translate(RDF4JInputQueryTranslatorImpl.java:176)
	at it.unibz.inf.ontop.answering.reformulation.input.translation.impl.RDF4JInputQueryTranslatorImpl.translateDistinctOrReduced(RDF4JInputQueryTranslatorImpl.java:486)
	at it.unibz.inf.ontop.answering.reformulation.input.translation.impl.RDF4JInputQueryTranslatorImpl.translate(RDF4JInputQueryTranslatorImpl.java:182)
	at it.unibz.inf.ontop.answering.reformulation.input.translation.impl.RDF4JInputQueryTranslatorImpl.translate(RDF4JInputQueryTranslatorImpl.java:85)
	at it.unibz.inf.ontop.answering.reformulation.input.impl.RDF4JInputQueryImpl.translate(RDF4JInputQueryImpl.java:37)
	at it.unibz.inf.ontop.answering.reformulation.impl.QuestQueryProcessor.reformulateIntoNativeQuery(QuestQueryProcessor.java:94)
```

I know I can disable the test mode, but when doing this here, it leads to an empty query. See the debug output
```
DEBUG [ScalaTest-run-running-QuotationTests] (QuestQueryProcessor.java:93) - SPARQL query:
PREFIX  :     <http://example.org/>

SELECT DISTINCT  ?o
WHERE
  { ?s  :p3  ?o
    { SELECT DISTINCT  ?s
      WHERE
        { ?s  :p4  ?o }
      ORDER BY DESC(?s)
      LIMIT   1
    }
  }
ORDER BY ?o

DEBUG [ScalaTest-run-running-QuotationTests] (QuestQueryProcessor.java:95) - Parsed query converted into IQ (after normalization):
ans1(o)
DISTINCT
   CONSTRUCT [o] []
      ORDER BY [ASC(o)]
         JOIN
            INTENSIONAL triple(s,<http://example.org/p3>,o)
            SLICE limit=1
               ORDER BY [DESC(s)]
                  INTENSIONAL triple(s,<http://example.org/p4>,o)

DEBUG [ScalaTest-run-running-QuotationTests] (QuestQueryProcessor.java:100) - Start the rewriting process...
DEBUG [ScalaTest-run-running-QuotationTests] (QuestQueryProcessor.java:104) - Rewritten IQ:
ans1(o)
DISTINCT
   CONSTRUCT [o] []
      ORDER BY [ASC(o)]
         JOIN
            INTENSIONAL triple(s,<http://example.org/p3>,o)
            SLICE limit=1
               ORDER BY [DESC(s)]
                  INTENSIONAL triple(s,<http://example.org/p4>,o)

DEBUG [ScalaTest-run-running-QuotationTests] (QuestQueryProcessor.java:106) - Start the unfolding...
DEBUG [ScalaTest-run-running-QuotationTests] (QuestQueryProcessor.java:117) - Unfolded query: 
ans1(o)
DISTINCT
   CONSTRUCT [o] []
      ORDER BY [ASC(o)]
         JOIN
            CONSTRUCT [s, o] [s/RDF(VARCHARToSTRING(s1m3),IRI), o/RDF(VARCHARToSTRING(o1m3),IRI)]
               EXTENSIONAL "t1"(0:s1m3,1:o1m3)
            SLICE limit=1
               ORDER BY [DESC(s)]
                  CONSTRUCT [s, o] [s/RDF(VARCHARToSTRING(s1m4),IRI), o/RDF(VARCHARToSTRING(o1m4),xsd:string)]
                     DISTINCT
                        EXTENSIONAL "t1"(0:s1m4,1:o1m4)

DEBUG [ScalaTest-run-running-QuotationTests] (QuestQueryProcessor.java:122) - Planned query: 
ans1(o)
EMPTY [o]
DEBUG [ScalaTest-run-running-QuotationTests] (QuestQueryProcessor.java:152) - Producing the native query string...
DEBUG [ScalaTest-run-running-QuotationTests] (QuestQueryProcessor.java:157) - Resulting native query: 
ans1(o)
EMPTY [o]
DEBUG [ScalaTest-run-running-QuotationTests] (QuestQueryProcessor.java:128) - Reformulation time: 148 ms
```

Any ideas what's going wrong here?

**Comment by bcogrel** [comment]
Hi Lorenz,

Thanks for adding the query plan and the modified SQL query that works.

From it, my impression is that Spark SQL probably does not support extended sort key columns, but only consider columns returned by the Project node. We would probably need to adapt the current logic of the `SelectFromWhereSerializer` to handle that case.

@kontchakov , do you have some ideas how to handle that case nicely?

Best,
Benjamin

PS: Lorenz, could you please delete your last comment as it is now tracked by #417 ?

**Comment by apano-on** [comment]
The sample SPARQL query provided can be executed by the current version (5.0.1) without any problems with Spark.
