### ISSUE TITLE
Bootstrapper may create invalid column identifiers with dashes but no quotes

### ISSUE THREAD

**Issue by bcogrel** [ontop/ontop#435]
Reported issue with H2 1.4.196 and the uni DB of the [Ontop tutorial](https://ontop-vkg.org/tutorial/).
Ontop 4.1.0.

```bash
ontop > ./ontop bootstrap -m ../mapping.obda -p ../basic.properties -t ../ontology.ttl -b http://example.org/
ontop > ./ontop materialize -m ../mapping.obda -p ../basic.properties -t ../ontology.ttl -o ../rdf-dataset.ttl -f turtle
FAILED TO PARSE: SELECT "uni1"."course-registration"."c_id" AS course-registration_c_id, "uni1"."course-registration"."s_id" AS course-registration_s_id, "uni1"."course"."c_id" AS course_c_id FROM "uni1"."course-registration", "uni1"."course" WHERE "uni1"."course-registration"."c_id" = "uni1"."course"."c_id" net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "-" "-"
    at line 1, column 53.

Was expecting one of:

    ","
    ";"
    "CONNECT"
    "EXCEPT"
    "FOR"
    "FROM"
    "GROUP"
    "HAVING"
    "INTERSECT"
    "INTO"
    "MINUS"
    "ORDER"
    "START"
    "UNION"
    "WHERE"
    "WINDOW"
    <EOF>

PARSER VIEW FOR SELECT "uni1"."course-registration"."c_id" AS course-registration_c_id, "uni1"."course-registration"."s_id" AS course-registration_s_id, "uni1"."course"."c_id" AS course_c_id FROM "uni1"."course-registration", "uni1"."course" WHERE "uni1"."course-registration"."c_id" = "uni1"."course"."c_id"
FAILED TO PARSE: SELECT "uni1"."course-registration"."c_id" AS course-registration_c_id, "uni1"."course-registration"."s_id" AS course-registration_s_id, "uni1"."student"."s_id" AS student_s_id FROM "uni1"."course-registration", "uni1"."student" WHERE "uni1"."course-registration"."s_id" = "uni1"."student"."s_id" net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "-" "-"
    at line 1, column 53.

Was expecting one of:

    ","
    ";"
    "CONNECT"
    "EXCEPT"
    "FOR"
    "FROM"
    "GROUP"
    "HAVING"
    "INTERSECT"
    "INTO"
    "MINUS"
    "ORDER"
    "START"
    "UNION"
    "WHERE"
    "WINDOW"
    <EOF>

PARSER VIEW FOR SELECT "uni1"."course-registration"."c_id" AS course-registration_c_id, "uni1"."course-registration"."s_id" AS course-registration_s_id, "uni1"."student"."s_id" AS student_s_id FROM "uni1"."course-registration", "uni1"."student" WHERE "uni1"."course-registration"."s_id" = "uni1"."student"."s_id"
CQC-REMOVED: EXTENSIONAL "uni1"."academic"(0:a_id2) FROM [EXTENSIONAL "uni1"."teaching"(0:c_id1,1:a_id2), EXTENSIONAL "uni1"."academic"(0:a_id2)]
CQC-REMOVED: EXTENSIONAL "uni1"."course"(0:c_id2) FROM [EXTENSIONAL "uni1"."teaching"(0:c_id2,1:a_id1), EXTENSIONAL "uni1"."course"(0:c_id2)]
CQC-REMOVED: EXTENSIONAL "uni2"."person"(0:pid2) FROM [EXTENSIONAL "uni2"."course"(0:cid1,1:pid2), EXTENSIONAL "uni2"."person"(0:pid2)]
CQC-REMOVED: EXTENSIONAL "uni2"."person"(0:pid2) FROM [EXTENSIONAL "uni2"."course"(0:cid1,2:pid2), EXTENSIONAL "uni2"."person"(0:pid2)]
CQC-REMOVED: EXTENSIONAL "uni2"."course"(0:cid2) FROM [EXTENSIONAL "uni2"."registration"(0:pid1,1:cid2), EXTENSIONAL "uni2"."course"(0:cid2)]
CQC-REMOVED: EXTENSIONAL "uni2"."person"(0:pid2) FROM [EXTENSIONAL "uni2"."registration"(0:pid2,1:cid1), EXTENSIONAL "uni2"."person"(0:pid2)]
13:11:40.405 |-INFO  in i.u.i.o.a.r.impl.QuestQueryProcessor - Ontop has completed the setup and it is ready for query answering!
13:11:40.714 |-ERROR in i.u.i.o.a.c.impl.QuestStatement - org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT DISTINCT CAST(V1.COURSE-REGISTRATION_C_ID AS TEXT) AS ""v0"", CAST(V1.COURSE-REGISTRATION_S_ID AS TEXT) AS ""v1"", CAST(V1.COURSE_C_ID AS TEXT) AS ""v2""
FROM (SELECT ""uni1"".""course-registration"".""c_id"" AS COURSE-[*]REGISTRATION_C_ID, ""uni1"".""course-registration"".""s_id"" AS COURSE-REGISTRATION_S_ID, ""uni1"".""course"".""c_id"" AS COURSE_C_ID FROM ""uni1"".""course-registration"", ""uni1"".""course"" WHERE ""uni1"".""course-registration"".""c_id"" = ""uni1"".""course"".""c_id"") V1
WHERE (V1.COURSE-REGISTRATION_C_ID IS NOT NULL AND V1.COURSE-REGISTRATION_S_ID IS NOT NULL AND V1.COURSE_C_ID IS NOT NULL)
 "; expected ",, FROM, WHERE, GROUP, HAVING, UNION, MINUS, EXCEPT, INTERSECT, ORDER, OFFSET, FETCH, LIMIT, FOR, )"; SQL statement:
SELECT DISTINCT CAST(V1.COURSE-REGISTRATION_C_ID AS TEXT) AS "v0", CAST(V1.COURSE-REGISTRATION_S_ID AS TEXT) AS "v1", CAST(V1.COURSE_C_ID AS TEXT) AS "v2"
FROM (SELECT "uni1"."course-registration"."c_id" AS course-registration_c_id, "uni1"."course-registration"."s_id" AS course-registration_s_id, "uni1"."course"."c_id" AS course_c_id FROM "uni1"."course-registration", "uni1"."course" WHERE "uni1"."course-registration"."c_id" = "uni1"."course"."c_id") V1
WHERE (V1.COURSE-REGISTRATION_C_ID IS NOT NULL AND V1.COURSE-REGISTRATION_S_ID IS NOT NULL AND V1.COURSE_C_ID IS NOT NULL)
 [42001-196]
at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
at org.h2.message.DbException.getSyntaxError(DbException.java:205)
at org.h2.command.Parser.getSyntaxError(Parser.java:541)
at org.h2.command.Parser.read(Parser.java:3258)
at org.h2.command.Parser.readTableFilter(Parser.java:1191)
at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1946)
at org.h2.command.Parser.parseSelectSimple(Parser.java:2095)
at org.h2.command.Parser.parseSelectSub(Parser.java:1940)
at org.h2.command.Parser.parseSelectUnion(Parser.java:1755)
at org.h2.command.Parser.parseSelect(Parser.java:1743)
at org.h2.command.Parser.parsePrepared(Parser.java:449)
at org.h2.command.Parser.parse(Parser.java:321)
at org.h2.command.Parser.parse(Parser.java:297)
at org.h2.command.Parser.prepareCommand(Parser.java:258)
at org.h2.engine.Session.prepareLocal(Session.java:578)
at org.h2.server.TcpServerThread.process(TcpServerThread.java:264)
at org.h2.server.TcpServerThread.run(TcpServerThread.java:158)
at java.base/java.lang.Thread.run(Thread.java:832)

it.unibz.inf.ontop.exception.OntopQueryEvaluationException: org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT DISTINCT CAST(V1.COURSE-REGISTRATION_C_ID AS TEXT) AS ""v0"", CAST(V1.COURSE-REGISTRATION_S_ID AS TEXT) AS ""v1"", CAST(V1.COURSE_C_ID AS TEXT) AS ""v2""
FROM (SELECT ""uni1"".""course-registration"".""c_id"" AS COURSE-[*]REGISTRATION_C_ID, ""uni1"".""course-registration"".""s_id"" AS COURSE-REGISTRATION_S_ID, ""uni1"".""course"".""c_id"" AS COURSE_C_ID FROM ""uni1"".""course-registration"", ""uni1"".""course"" WHERE ""uni1"".""course-registration"".""c_id"" = ""uni1"".""course"".""c_id"") V1
WHERE (V1.COURSE-REGISTRATION_C_ID IS NOT NULL AND V1.COURSE-REGISTRATION_S_ID IS NOT NULL AND V1.COURSE_C_ID IS NOT NULL)
 "; expected ",, FROM, WHERE, GROUP, HAVING, UNION, MINUS, EXCEPT, INTERSECT, ORDER, OFFSET, FETCH, LIMIT, FOR, )"; SQL statement:
SELECT DISTINCT CAST(V1.COURSE-REGISTRATION_C_ID AS TEXT) AS "v0", CAST(V1.COURSE-REGISTRATION_S_ID AS TEXT) AS "v1", CAST(V1.COURSE_C_ID AS TEXT) AS "v2"
FROM (SELECT "uni1"."course-registration"."c_id" AS course-registration_c_id, "uni1"."course-registration"."s_id" AS course-registration_s_id, "uni1"."course"."c_id" AS course_c_id FROM "uni1"."course-registration", "uni1"."course" WHERE "uni1"."course-registration"."c_id" = "uni1"."course"."c_id") V1
WHERE (V1.COURSE-REGISTRATION_C_ID IS NOT NULL AND V1.COURSE-REGISTRATION_S_ID IS NOT NULL AND V1.COURSE_C_ID IS NOT NULL)
 [42001-196]
at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
at org.h2.message.DbException.getSyntaxError(DbException.java:205)
at org.h2.command.Parser.getSyntaxError(Parser.java:541)
at org.h2.command.Parser.read(Parser.java:3258)
at org.h2.command.Parser.readTableFilter(Parser.java:1191)
at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1946)
at org.h2.command.Parser.parseSelectSimple(Parser.java:2095)
at org.h2.command.Parser.parseSelectSub(Parser.java:1940)
at org.h2.command.Parser.parseSelectUnion(Parser.java:1755)
at org.h2.command.Parser.parseSelect(Parser.java:1743)
at org.h2.command.Parser.parsePrepared(Parser.java:449)
at org.h2.command.Parser.parse(Parser.java:321)
at org.h2.command.Parser.parse(Parser.java:297)
at org.h2.command.Parser.prepareCommand(Parser.java:258)
at org.h2.engine.Session.prepareLocal(Session.java:578)
at org.h2.server.TcpServerThread.process(TcpServerThread.java:264)
at org.h2.server.TcpServerThread.run(TcpServerThread.java:158)
at java.base/java.lang.Thread.run(Thread.java:832)

at it.unibz.inf.ontop.answering.connection.impl.SQLQuestStatement.executeSelectQuery(SQLQuestStatement.java:205)
at it.unibz.inf.ontop.answering.connection.impl.QuestStatement.executeSelectQuery(QuestStatement.java:122)
at it.unibz.inf.ontop.answering.connection.impl.QuestStatement.executeSelectQuery(QuestStatement.java:114)
at it.unibz.inf.ontop.answering.connection.impl.QuestStatement$QueryExecutionThread.run(QuestStatement.java:97)
Caused by: org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT DISTINCT CAST(V1.COURSE-REGISTRATION_C_ID AS TEXT) AS ""v0"", CAST(V1.COURSE-REGISTRATION_S_ID AS TEXT) AS ""v1"", CAST(V1.COURSE_C_ID AS TEXT) AS ""v2""
FROM (SELECT ""uni1"".""course-registration"".""c_id"" AS COURSE-[*]REGISTRATION_C_ID, ""uni1"".""course-registration"".""s_id"" AS COURSE-REGISTRATION_S_ID, ""uni1"".""course"".""c_id"" AS COURSE_C_ID FROM ""uni1"".""course-registration"", ""uni1"".""course"" WHERE ""uni1"".""course-registration"".""c_id"" = ""uni1"".""course"".""c_id"") V1
WHERE (V1.COURSE-REGISTRATION_C_ID IS NOT NULL AND V1.COURSE-REGISTRATION_S_ID IS NOT NULL AND V1.COURSE_C_ID IS NOT NULL)
 "; expected ",, FROM, WHERE, GROUP, HAVING, UNION, MINUS, EXCEPT, INTERSECT, ORDER, OFFSET, FETCH, LIMIT, FOR, )"; SQL statement:
SELECT DISTINCT CAST(V1.COURSE-REGISTRATION_C_ID AS TEXT) AS "v0", CAST(V1.COURSE-REGISTRATION_S_ID AS TEXT) AS "v1", CAST(V1.COURSE_C_ID AS TEXT) AS "v2"
FROM (SELECT "uni1"."course-registration"."c_id" AS course-registration_c_id, "uni1"."course-registration"."s_id" AS course-registration_s_id, "uni1"."course"."c_id" AS course_c_id FROM "uni1"."course-registration", "uni1"."course" WHERE "uni1"."course-registration"."c_id" = "uni1"."course"."c_id") V1
WHERE (V1.COURSE-REGISTRATION_C_ID IS NOT NULL AND V1.COURSE-REGISTRATION_S_ID IS NOT NULL AND V1.COURSE_C_ID IS NOT NULL)
 [42001-196]
at org.h2.engine.SessionRemote.done(SessionRemote.java:629)
at org.h2.command.CommandRemote.prepare(CommandRemote.java:83)
at org.h2.command.CommandRemote.<init>(CommandRemote.java:49)
at org.h2.engine.SessionRemote.prepareCommand(SessionRemote.java:499)
at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:73)
at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
at com.sun.proxy.$Proxy44.executeQuery(Unknown Source)
at it.unibz.inf.ontop.answering.connection.impl.SQLQuestStatement.executeSelectQuery(SQLQuestStatement.java:197)
... 3 common frames omitted
13:11:40.715 |-ERROR in i.u.i.o.m.i.DefaultMaterializedGraphResultSet - Problem materializing the class/property http://example.org/course-registration#ref-c_id/2
java.lang.RuntimeException: org.eclipse.rdf4j.query.QueryEvaluationException: it.unibz.inf.ontop.exception.OntopQueryEvaluationException: org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT DISTINCT CAST(V1.COURSE-REGISTRATION_C_ID AS TEXT) AS ""v0"", CAST(V1.COURSE-REGISTRATION_S_ID AS TEXT) AS ""v1"", CAST(V1.COURSE_C_ID AS TEXT) AS ""v2""
FROM (SELECT ""uni1"".""course-registration"".""c_id"" AS COURSE-[*]REGISTRATION_C_ID, ""uni1"".""course-registration"".""s_id"" AS COURSE-REGISTRATION_S_ID, ""uni1"".""course"".""c_id"" AS COURSE_C_ID FROM ""uni1"".""course-registration"", ""uni1"".""course"" WHERE ""uni1"".""course-registration"".""c_id"" = ""uni1"".""course"".""c_id"") V1
WHERE (V1.COURSE-REGISTRATION_C_ID IS NOT NULL AND V1.COURSE-REGISTRATION_S_ID IS NOT NULL AND V1.COURSE_C_ID IS NOT NULL)
 "; expected ",, FROM, WHERE, GROUP, HAVING, UNION, MINUS, EXCEPT, INTERSECT, ORDER, OFFSET, FETCH, LIMIT, FOR, )"; SQL statement:
SELECT DISTINCT CAST(V1.COURSE-REGISTRATION_C_ID AS TEXT) AS "v0", CAST(V1.COURSE-REGISTRATION_S_ID AS TEXT) AS "v1", CAST(V1.COURSE_C_ID AS TEXT) AS "v2"
FROM (SELECT "uni1"."course-registration"."c_id" AS course-registration_c_id, "uni1"."course-registration"."s_id" AS course-registration_s_id, "uni1"."course"."c_id" AS course_c_id FROM "uni1"."course-registration", "uni1"."course" WHERE "uni1"."course-registration"."c_id" = "uni1"."course"."c_id") V1
WHERE (V1.COURSE-REGISTRATION_C_ID IS NOT NULL AND V1.COURSE-REGISTRATION_S_ID IS NOT NULL AND V1.COURSE_C_ID IS NOT NULL)
 [42001-196]
at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
at org.h2.message.DbException.getSyntaxError(DbException.java:205)
at org.h2.command.Parser.getSyntaxError(Parser.java:541)
at org.h2.command.Parser.read(Parser.java:3258)
at org.h2.command.Parser.readTableFilter(Parser.java:1191)
at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1946)
at org.h2.command.Parser.parseSelectSimple(Parser.java:2095)
at org.h2.command.Parser.parseSelectSub(Parser.java:1940)
at org.h2.command.Parser.parseSelectUnion(Parser.java:1755)
at org.h2.command.Parser.parseSelect(Parser.java:1743)
at org.h2.command.Parser.parsePrepared(Parser.java:449)
at org.h2.command.Parser.parse(Parser.java:321)
at org.h2.command.Parser.parse(Parser.java:297)
at org.h2.command.Parser.prepareCommand(Parser.java:258)
at org.h2.engine.Session.prepareLocal(Session.java:578)
at org.h2.server.TcpServerThread.process(TcpServerThread.java:264)
at org.h2.server.TcpServerThread.run(TcpServerThread.java:158)
at java.base/java.lang.Thread.run(Thread.java:832)

at it.unibz.inf.ontop.cli.OntopMaterialize.runWithSingleFile(OntopMaterialize.java:159)
at it.unibz.inf.ontop.cli.OntopMaterialize.run(OntopMaterialize.java:109)
at it.unibz.inf.ontop.cli.Ontop.main(Ontop.java:20)
Caused by: org.eclipse.rdf4j.query.QueryEvaluationException: it.unibz.inf.ontop.exception.OntopQueryEvaluationException: org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT DISTINCT CAST(V1.COURSE-REGISTRATION_C_ID AS TEXT) AS ""v0"", CAST(V1.COURSE-REGISTRATION_S_ID AS TEXT) AS ""v1"", CAST(V1.COURSE_C_ID AS TEXT) AS ""v2""
FROM (SELECT ""uni1"".""course-registration"".""c_id"" AS COURSE-[*]REGISTRATION_C_ID, ""uni1"".""course-registration"".""s_id"" AS COURSE-REGISTRATION_S_ID, ""uni1"".""course"".""c_id"" AS COURSE_C_ID FROM ""uni1"".""course-registration"", ""uni1"".""course"" WHERE ""uni1"".""course-registration"".""c_id"" = ""uni1"".""course"".""c_id"") V1
WHERE (V1.COURSE-REGISTRATION_C_ID IS NOT NULL AND V1.COURSE-REGISTRATION_S_ID IS NOT NULL AND V1.COURSE_C_ID IS NOT NULL)
 "; expected ",, FROM, WHERE, GROUP, HAVING, UNION, MINUS, EXCEPT, INTERSECT, ORDER, OFFSET, FETCH, LIMIT, FOR, )"; SQL statement:
SELECT DISTINCT CAST(V1.COURSE-REGISTRATION_C_ID AS TEXT) AS "v0", CAST(V1.COURSE-REGISTRATION_S_ID AS TEXT) AS "v1", CAST(V1.COURSE_C_ID AS TEXT) AS "v2"
FROM (SELECT "uni1"."course-registration"."c_id" AS course-registration_c_id, "uni1"."course-registration"."s_id" AS course-registration_s_id, "uni1"."course"."c_id" AS course_c_id FROM "uni1"."course-registration", "uni1"."course" WHERE "uni1"."course-registration"."c_id" = "uni1"."course"."c_id") V1
WHERE (V1.COURSE-REGISTRATION_C_ID IS NOT NULL AND V1.COURSE-REGISTRATION_S_ID IS NOT NULL AND V1.COURSE_C_ID IS NOT NULL)
 [42001-196]
at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
at org.h2.message.DbException.getSyntaxError(DbException.java:205)
at org.h2.command.Parser.getSyntaxError(Parser.java:541)
at org.h2.command.Parser.read(Parser.java:3258)
at org.h2.command.Parser.readTableFilter(Parser.java:1191)
at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1946)
at org.h2.command.Parser.parseSelectSimple(Parser.java:2095)
at org.h2.command.Parser.parseSelectSub(Parser.java:1940)
at org.h2.command.Parser.parseSelectUnion(Parser.java:1755)
at org.h2.command.Parser.parseSelect(Parser.java:1743)
at org.h2.command.Parser.parsePrepared(Parser.java:449)
at org.h2.command.Parser.parse(Parser.java:321)
at org.h2.command.Parser.parse(Parser.java:297)
at org.h2.command.Parser.prepareCommand(Parser.java:258)
at org.h2.engine.Session.prepareLocal(Session.java:578)
at org.h2.server.TcpServerThread.process(TcpServerThread.java:264)
at org.h2.server.TcpServerThread.run(TcpServerThread.java:158)
at java.base/java.lang.Thread.run(Thread.java:832)

at it.unibz.inf.ontop.rdf4j.materialization.impl.DefaultRDF4JMaterializer$GraphMaterializationIteration.hasNext(DefaultRDF4JMaterializer.java:249)
at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:63)
at it.unibz.inf.ontop.cli.OntopMaterialize.serializeTripleBatch(OntopMaterialize.java:242)
at it.unibz.inf.ontop.cli.OntopMaterialize.runWithSingleFile(OntopMaterialize.java:152)
... 2 more
Caused by: it.unibz.inf.ontop.exception.OntopQueryEvaluationException: org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT DISTINCT CAST(V1.COURSE-REGISTRATION_C_ID AS TEXT) AS ""v0"", CAST(V1.COURSE-REGISTRATION_S_ID AS TEXT) AS ""v1"", CAST(V1.COURSE_C_ID AS TEXT) AS ""v2""
FROM (SELECT ""uni1"".""course-registration"".""c_id"" AS COURSE-[*]REGISTRATION_C_ID, ""uni1"".""course-registration"".""s_id"" AS COURSE-REGISTRATION_S_ID, ""uni1"".""course"".""c_id"" AS COURSE_C_ID FROM ""uni1"".""course-registration"", ""uni1"".""course"" WHERE ""uni1"".""course-registration"".""c_id"" = ""uni1"".""course"".""c_id"") V1
WHERE (V1.COURSE-REGISTRATION_C_ID IS NOT NULL AND V1.COURSE-REGISTRATION_S_ID IS NOT NULL AND V1.COURSE_C_ID IS NOT NULL)
 "; expected ",, FROM, WHERE, GROUP, HAVING, UNION, MINUS, EXCEPT, INTERSECT, ORDER, OFFSET, FETCH, LIMIT, FOR, )"; SQL statement:
SELECT DISTINCT CAST(V1.COURSE-REGISTRATION_C_ID AS TEXT) AS "v0", CAST(V1.COURSE-REGISTRATION_S_ID AS TEXT) AS "v1", CAST(V1.COURSE_C_ID AS TEXT) AS "v2"
FROM (SELECT "uni1"."course-registration"."c_id" AS course-registration_c_id, "uni1"."course-registration"."s_id" AS course-registration_s_id, "uni1"."course"."c_id" AS course_c_id FROM "uni1"."course-registration", "uni1"."course" WHERE "uni1"."course-registration"."c_id" = "uni1"."course"."c_id") V1
WHERE (V1.COURSE-REGISTRATION_C_ID IS NOT NULL AND V1.COURSE-REGISTRATION_S_ID IS NOT NULL AND V1.COURSE_C_ID IS NOT NULL)
 [42001-196]
at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
at org.h2.message.DbException.getSyntaxError(DbException.java:205)
at org.h2.command.Parser.getSyntaxError(Parser.java:541)
at org.h2.command.Parser.read(Parser.java:3258)
at org.h2.command.Parser.readTableFilter(Parser.java:1191)
at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1946)
at org.h2.command.Parser.parseSelectSimple(Parser.java:2095)
at org.h2.command.Parser.parseSelectSub(Parser.java:1940)
at org.h2.command.Parser.parseSelectUnion(Parser.java:1755)
at org.h2.command.Parser.parseSelect(Parser.java:1743)
at org.h2.command.Parser.parsePrepared(Parser.java:449)
at org.h2.command.Parser.parse(Parser.java:321)
at org.h2.command.Parser.parse(Parser.java:297)
at org.h2.command.Parser.prepareCommand(Parser.java:258)
at org.h2.engine.Session.prepareLocal(Session.java:578)
at org.h2.server.TcpServerThread.process(TcpServerThread.java:264)
at org.h2.server.TcpServerThread.run(TcpServerThread.java:158)
at java.base/java.lang.Thread.run(Thread.java:832)

at it.unibz.inf.ontop.answering.connection.impl.SQLQuestStatement.executeSelectQuery(SQLQuestStatement.java:205)
at it.unibz.inf.ontop.answering.connection.impl.QuestStatement.executeSelectQuery(QuestStatement.java:122)
at it.unibz.inf.ontop.answering.connection.impl.QuestStatement.executeSelectQuery(QuestStatement.java:114)
at it.unibz.inf.ontop.answering.connection.impl.QuestStatement$QueryExecutionThread.run(QuestStatement.java:97)
Caused by: org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT DISTINCT CAST(V1.COURSE-REGISTRATION_C_ID AS TEXT) AS ""v0"", CAST(V1.COURSE-REGISTRATION_S_ID AS TEXT) AS ""v1"", CAST(V1.COURSE_C_ID AS TEXT) AS ""v2""
FROM (SELECT ""uni1"".""course-registration"".""c_id"" AS COURSE-[*]REGISTRATION_C_ID, ""uni1"".""course-registration"".""s_id"" AS COURSE-REGISTRATION_S_ID, ""uni1"".""course"".""c_id"" AS COURSE_C_ID FROM ""uni1"".""course-registration"", ""uni1"".""course"" WHERE ""uni1"".""course-registration"".""c_id"" = ""uni1"".""course"".""c_id"") V1
WHERE (V1.COURSE-REGISTRATION_C_ID IS NOT NULL AND V1.COURSE-REGISTRATION_S_ID IS NOT NULL AND V1.COURSE_C_ID IS NOT NULL)
 "; expected ",, FROM, WHERE, GROUP, HAVING, UNION, MINUS, EXCEPT, INTERSECT, ORDER, OFFSET, FETCH, LIMIT, FOR, )"; SQL statement:
SELECT DISTINCT CAST(V1.COURSE-REGISTRATION_C_ID AS TEXT) AS "v0", CAST(V1.COURSE-REGISTRATION_S_ID AS TEXT) AS "v1", CAST(V1.COURSE_C_ID AS TEXT) AS "v2"
FROM (SELECT "uni1"."course-registration"."c_id" AS course-registration_c_id, "uni1"."course-registration"."s_id" AS course-registration_s_id, "uni1"."course"."c_id" AS course_c_id FROM "uni1"."course-registration", "uni1"."course" WHERE "uni1"."course-registration"."c_id" = "uni1"."course"."c_id") V1
WHERE (V1.COURSE-REGISTRATION_C_ID IS NOT NULL AND V1.COURSE-REGISTRATION_S_ID IS NOT NULL AND V1.COURSE_C_ID IS NOT NULL)
 [42001-196]
at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
at org.h2.message.DbException.getSyntaxError(DbException.java:205)
at org.h2.command.Parser.getSyntaxError(Parser.java:541)
at org.h2.command.Parser.read(Parser.java:3258)
at org.h2.command.Parser.readTableFilter(Parser.java:1191)
at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1946)
at org.h2.command.Parser.parseSelectSimple(Parser.java:2095)
at org.h2.command.Parser.parseSelectSub(Parser.java:1940)
at org.h2.command.Parser.parseSelectUnion(Parser.java:1755)
at org.h2.command.Parser.parseSelect(Parser.java:1743)
at org.h2.command.Parser.parsePrepared(Parser.java:449)
at org.h2.command.Parser.parse(Parser.java:321)
at org.h2.command.Parser.parse(Parser.java:297)
at org.h2.command.Parser.prepareCommand(Parser.java:258)
at org.h2.engine.Session.prepareLocal(Session.java:578)
at org.h2.server.TcpServerThread.process(TcpServerThread.java:264)
at org.h2.server.TcpServerThread.run(TcpServerThread.java:158)
at java.base/java.lang.Thread.run(Thread.java:832)

at org.h2.engine.SessionRemote.done(SessionRemote.java:629)
at org.h2.command.CommandRemote.prepare(CommandRemote.java:83)
at org.h2.command.CommandRemote.<init>(CommandRemote.java:49)
at org.h2.engine.SessionRemote.prepareCommand(SessionRemote.java:499)
at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:73)
at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
at com.sun.proxy.$Proxy44.executeQuery(Unknown Source)
at it.unibz.inf.ontop.answering.connection.impl.SQLQuestStatement.executeSelectQuery(SQLQuestStatement.java:197)
... 3 more
Exception in thread "main" java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.fail(Assert.java:96)
at it.unibz.inf.ontop.cli.Ontop.main(Ontop.java:32)
ontop > 
```

Both the internal SQL parser of Ontop and H2 do no parse the SQL query generated by the bootstrapper.

**Comment by bcogrel** [comment]
Closed by 4e31ade402f9ed831090e7e12a6b1fa743ffe7fb
