### ISSUE TITLE
Mapping Assertion Error 

### ISSUE THREAD

**Issue by Modeuss** [ontop/ontop#469]
### Description

Could not infer the type of rs1 and the option "ontop.inferDefaultDatatype" is disabled

### Steps to Reproduce

1.  A mapping assertion which includes an sql query: 
SELECT propertyid, CAST(regr_slope(stressvalue, strainvalue) as decimal) as rs
FROM property_ym0001
group by propertyid

2. Getting an error message: Could not infer the type of rs and the option "ontop.inferDefaultDatatype" is disabled.
when I start the ontop reasoner 

### Attached material

Mapping assertion:
id: Property_ym0001
target atom: triple(s,p,o) with s/RDF(urn:absolute/smo-core#smartmaterials/property/{}(TmpToTEXT(propertyid)),IRI), p/<urn:absolute/smo-core#PropertyValue>, o/RDF(TmpToTEXT(rs),rdfs:Literal)
source query: SELECT propertyid, CAST(regr_slope(stressvalue, strainvalue) as decimal) as rs
FROM property_ym0001
group by propertyid
	at it.unibz.inf.ontop.spec.mapping.transformer.impl.MappingDatatypeFillerImpl.transform(MappingDatatypeFillerImpl.java:54) ~[na:na]
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convertPPMapping(SQLMappingExtractor.java:166) ~[na:na]
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.extract(SQLMappingExtractor.java:115) ~[na:na]
	at it.unibz.inf.ontop.spec.impl.DefaultOBDASpecificationExtractor.extract(DefaultOBDASpecificationExtractor.java:56) ~[na:na]
	at it.unibz.inf.ontop.injection.impl.OntopMappingConfigurationImpl.loadSpecification(OntopMappingConfigurationImpl.java:132) ~[na:na]
	at it.unibz.inf.ontop.injection.impl.OntopMappingSQLConfigurationImpl.loadSpecification(OntopMappingSQLConfigurationImpl.java:89) ~[na:na]
	at it.unibz.inf.ontop.injection.impl.OntopMappingSQLAllConfigurationImpl.loadSpecification(OntopMappingSQLAllConfigurationImpl.java:47) ~[na:na]
	at it.unibz.inf.ontop.injection.impl.OntopSQLOWLAPIConfigurationImpl.loadOBDASpecification(OntopSQLOWLAPIConfigurationImpl.java:34) ~[na:na]
	at it.unibz.inf.ontop.injection.impl.OntopOBDAConfigurationImpl.loadSpecification(OntopOBDAConfigurationImpl.java:44) ~[na:na]
	at it.unibz.inf.ontop.injection.OntopSystemConfiguration.loadQueryEngine(OntopSystemConfiguration.java:20) ~[na:na]
	at it.unibz.inf.ontop.owlapi.impl.QuestOWL.<init>(QuestOWL.java:110) ~[na:na]
	... 10 common frames omitted
Caused by: it.unibz.inf.ontop.exception.UnknownDatatypeException: Could not infer the type of rs1 and the option "ontop.inferDefaultDatatype" is disabled.

### Versions

latest version of Ontop plugin (Protege 5.5.0)

**Comment by bcogrel** [comment]
Hi @Modeuss , Ontop does not parse SQL aggregate queries in the mapping, treats them as black-boxes and therefore does not know how to extract their datatypes. In this situation, it cannot infer the RDF datatype from the database one.

Have you tried to specify the RDF datatype in the target part of the mapping assertion?

Best,
Benjamin

**Comment by Modeuss** [comment]
thanks for the suggestion I will look into that..

Best,
Modeus

**Comment by CrokyPlayzz** [comment]
> Hi @Modeuss , Ontop does not parse SQL aggregate queries in the mapping, treats them as black-boxes and therefore does not know how to extract their datatypes. In this situation, it cannot infer the RDF datatype from the database one.
> 
> Have you tried to specify the RDF datatype in the target part of the mapping assertion?
> 
> Best, Benjamin

How would you RDF datatype in the target part?

**Comment by bcogrel** [comment]
> How would you specify the RDF datatype in the target part?

Here is an example for `xsd:string` https://ontop-vkg.org/tutorial/basic/university-1.html#mappings .

As for the problem with black-box views, there is a good news: in 4.2.0 (to be released soon), the datatype can be extracted from black-box views by turning the property `ontop.allowRetrievingBlackBoxViewMetadataFromDB` to true (see https://ontop-vkg.org/guide/advanced/configuration).
