### ISSUE TITLE
bootstrap fails when there is a unique index that uses md5() of a column value

### ISSUE THREAD

**Issue by justin2004** [ontop/ontop#494]
### Description

bootstrap fails when there is a unique index that uses md5() of a column value with the following error:
```
20:42:22.607 [main] DEBUG o.s.owlapi.utilities.Injector - Injecting values [[org.semanticweb.owlapi.rdf.rdfxml.renderer.RDFXMLStorerFactory@13e698c7, org.semanticweb.owlapi.functional.renderer.FunctionalSyntaxStorerFactory@267bbe1a, org.semanticweb.owlapi.manchestersyntax.renderer.ManchesterSyntaxStorerFactory@1f12e153, org.semanticweb.owlapi.rio.RioJsonStorerFactory@6eafb10e, org.semanticweb.owlapi.rio.RioNTriplesStorerFactory@2873d672, org.semanticweb.owlapi.dlsyntax.renderer.DLSyntaxHTMLStorerFactory@6b410923, org.semanticweb.owlapi.krss2.renderer.KRSS2OWLSyntaxStorerFactory@389562d6, org.semanticweb.owlapi.rio.RioNQuadsStorerFactory@464a4442, org.semanticweb.owlapi.rio.RioJsonLDStorerFactory@1d3e6d34, org.semanticweb.owlapi.rdf.turtle.renderer.TurtleStorerFactory@5a101b1c, org.semanticweb.owlapi.rio.RioN3StorerFactory@26a94fa5, org.semanticweb.owlapi.rio.RioTurtleStorerFactory@757529a4, org.semanticweb.owlapi.rio.RioTrixStorerFactory@4303b7f0, org.semanticweb.owlapi.rio.RioRDFXMLStorerFactory@3bc735b3, org.semanticweb.owlapi.latex.renderer.LatexStorerFactory@3a60c416, org.semanticweb.owlapi.rio.RioTrigStorerFactory@577f9109, org.semanticweb.owlapi.oboformat.OBOFormatStorerFactory@6d64b553, org.semanticweb.owlapi.rio.RioBinaryRdfStorerFactory@53667cbe, org.semanticweb.owlapi.owlxml.renderer.OWLXMLStorerFactory@aed0151, org.semanticweb.owlapi.dlsyntax.renderer.DLSyntaxStorerFactory@e8fadb0]] on method public void uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.setOntologyStorers(java.util.Set).
Error occurred during bootstrapping: it.unibz.inf.ontop.exception.MetadataExtractionException: it.unibz.inf.ontop.dbschema.AttributeNotFoundException
Debugging information for developers:
it.unibz.inf.ontop.exception.MappingBootstrappingException: it.unibz.inf.ontop.exception.MetadataExtractionException: it.unibz.inf.ontop.dbschema.AttributeNotFoundException
        at it.unibz.inf.ontop.spec.mapping.bootstrap.impl.DirectMappingEngine.bootstrapMappingAndOntology(DirectMappingEngine.java:148)
        at it.unibz.inf.ontop.spec.mapping.bootstrap.impl.DirectMappingEngine.bootstrap(DirectMappingEngine.java:91)
        at it.unibz.inf.ontop.spec.mapping.bootstrap.impl.DefaultDirectMappingBootstrapper.bootstrap(DefaultDirectMappingBootstrapper.java:16)
        at it.unibz.inf.ontop.cli.OntopBootstrap.run(OntopBootstrap.java:56)
        at it.unibz.inf.ontop.cli.Ontop.main(Ontop.java:20)
Caused by: it.unibz.inf.ontop.exception.MetadataExtractionException: it.unibz.inf.ontop.dbschema.AttributeNotFoundException
        at it.unibz.inf.ontop.dbschema.impl.AbstractDBMetadataProvider.insertUniqueAttributes(AbstractDBMetadataProvider.java:243)
        at it.unibz.inf.ontop.dbschema.impl.AbstractDBMetadataProvider.insertIntegrityConstraints(AbstractDBMetadataProvider.java:154)
        at it.unibz.inf.ontop.dbschema.impl.CachingMetadataLookup.extractImmutableMetadata(CachingMetadataLookup.java:44)
        at it.unibz.inf.ontop.dbschema.ImmutableMetadata.extractImmutableMetadata(ImmutableMetadata.java:17)
        at it.unibz.inf.ontop.spec.mapping.bootstrap.impl.DirectMappingEngine.extractPPMapping(DirectMappingEngine.java:166)
        at it.unibz.inf.ontop.spec.mapping.bootstrap.impl.DirectMappingEngine.bootstrapMappingAndOntology(DirectMappingEngine.java:123)
        ... 4 more
Caused by: it.unibz.inf.ontop.dbschema.AttributeNotFoundException
        at it.unibz.inf.ontop.dbschema.impl.AbstractRelationDefinition.getAttribute(AbstractRelationDefinition.java:49)
        at it.unibz.inf.ontop.dbschema.impl.UniqueConstraintImpl$UniqueConstraintBuilder.addDeterminant(UniqueConstraintImpl.java:31)
        at it.unibz.inf.ontop.dbschema.impl.AbstractDBMetadataProvider.insertUniqueAttributes(AbstractDBMetadataProvider.java:234)
        ... 9 more

```

### Steps to Reproduce

load this into a postgres database and then run the ontop bootstrap command against it:
```
--
-- PostgreSQL database dump
--

-- Dumped from database version 11.12 (Debian 11.12-1.pgdg90+1)
-- Dumped by pg_dump version 11.12 (Debian 11.12-1.pgdg90+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: cat; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cat (
    id integer NOT NULL,
    name character varying,
    age integer
);


ALTER TABLE public.cat OWNER TO postgres;

--
-- Data for Name: cat; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cat (id, name, age) FROM stdin;
5       freddo  12
\.


--
-- Name: indycar; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX indycar ON public.cat USING btree (age, md5((name)::text));


--
-- PostgreSQL database dump complete
--

```

**Expected behavior:** [What you expect to see]

i expect to get a mapping file from the bootstrap process

**Actual behavior:** [What actually happens]

an error is emitted. but if you remove this
```
CREATE UNIQUE INDEX indycar ON public.cat USING btree (age, md5((name)::text));
```
then the bootstrap is able to run successfully.

**Reproduces how often:** [Does it happen every time?]

always

### Versions

the HEAD of the version4 branch. and i tried some older versions of ontop and had the same result.

**Comment by justin2004** [comment]
also, i think it might be the `unique` keyword there that is causing trouble.

that is if you replace this
```
CREATE UNIQUE INDEX indycar ON public.cat USING btree (age, md5((name)::text));
```
with
```
CREATE INDEX indycar ON public.cat USING btree (age, md5((name)::text));
```

i think it works.

**Comment by kontchakov** [comment]
Ontop uses only unique indexes (and absolutely ignores all other types of indexes) - hence, when the index is not unique, it does not affect Ontop.

At the moment, Ontop does not support unique indexes with complex expressions on columns, and if it finds one, it simply fails. I have managed to reproduce the issue and will publish a fix in the near future.

As a side note: what purpose does a (unique) index on the MD5 value serve? Is PostgreSQL really able to take advantage of such indexes? Also, there could be two different names with the same MD5 - so, the index would be too restrictive.

**Comment by justin2004** [comment]
> As a side note: what purpose does a (unique) index on the MD5 value serve?

i'm not sure. i just needed extract triples from a postgres db with DDL like that.

but i did just find this:
["if the text to be indexed is too large and doesn't fit PostgreSQL buffer page, indexing is not going to work."](https://dev.to/rhymes/how-to-build-unique-indexes-in-postgresql-on-large-text-3e6d)

**Comment by bcogrel** [comment]
Fixed by https://github.com/ontop/ontop/commit/b1c38604d28d4134836393ac6aea2fd3a29b0159
