### ISSUE TITLE
Failed to convert geom binary string to WKT format when using geo:asWKT

### ISSUE THREAD

**Issue by Cq5616** [ontop/ontop#523]
### Description

I have imported geosparql ontology in Protégé and decleare a simple mapping.  but when using geo:asWKT in SPARQL, it just return geometry in binary string format. 

### Steps to Reproduce
1. import geosparql ontology
    In ontology import pannel of Protégé, click "direct imports" and select local ontology file of geosparql.
    ontology file can get from https://github.com/opengeospatial/ogc-geosparql/blob/master/1.0/geo.ttl
2. declare a class inherit from geo:Geometry or geo:Feature
    See ontology file provided below for more detials. 
3. declare a mapping and explicitly declare the datatype of geometry
     RDF triple statement		
     ` :{osm_id} a :road ; geo:asWKT {geom}^^geo:wktLiteral . `
     SQL statement
     `select osm_id,geom from roads` 
4. start reasoner
     it goes wrong with error 
     ![image](https://user-images.githubusercontent.com/60844216/168212177-9e5757b1-2275-4691-b840-51d36138168a.png)
5. delete the datatype declaration of  geo:wktLiteral
       new RDF triple statement	
     ` :{osm_id} a :road ; geo:asWKT {geom} . `
     SQL statement
     `select osm_id,geom from roads` 
     In this case, the reasoner started well. But something goes wrong in the next step.
6. SPARQL qurey
just a simple query to show the geometry
```
PREFIX jt: <http://jiaotong/ontologies#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>

select ?t where{
?r a jt:road;
geo:asWKT ?t
}
```
  
**Expected behavior:**
geometry data should show in WKT format. like ontop-spatial tutorial video in https://www.youtube.com/watch?v=F5_2Zxi5_e8&t=48s
something like this 
![image](https://user-images.githubusercontent.com/60844216/168212949-eeefae57-a7cd-4a76-8a07-3bb361ff35a2.png)

**Actual behavior:** 
it just return geometry in binary string in xsd:string format. 
![image](https://user-images.githubusercontent.com/60844216/168212877-9cae8e6a-c001-4ea6-88e0-07e4fd3e6f59.png)

### Attached material

my ontology file 
```@prefix : <http://jiaotong/ontologies#> .
@prefix jt: <http://jiaotong/ontologies#> .
@prefix geo: <http://www.opengis.net/ont/geosparql#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix geof: <http://www.opengis.net/def/function/geosparql/> .
@prefix obda: <https://w3id.org/obda/vocabulary#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@base <http://jiaotong/ontologies#> .

<http://jiaotong/ontologies#> rdf:type owl:Ontology ;
                               owl:imports <http://www.opengis.net/ont/geosparql> .

#################################################################
#    Data properties
#################################################################

###  http://jiaotong/ontologies#name
jt:name rdf:type owl:DatatypeProperty ;
        rdfs:domain jt:road .


###  http://jiaotong/ontologies#type
jt:type rdf:type owl:DatatypeProperty ;
        rdfs:subPropertyOf owl:topDataProperty ;
        rdfs:domain jt:road .


###  http://www.opengis.net/ont/geosparql#hasSerialization
geo:hasSerialization rdfs:range xsd:string .


#################################################################
#    Classes
#################################################################

###  http://jiaotong/ontologies#road
jt:road rdf:type owl:Class ;
        rdfs:subClassOf geo:Geometry .


###  Generated by the OWL API (version 4.5.9.2019-02-01T07:24:44Z) https://github.com/owlcs/owlapi
```
my mapping file
 ```
[PrefixDeclaration]
:		http://jiaotong/ontologies#
jt:		http://jiaotong/ontologies#
geo:		http://www.opengis.net/ont/geosparql#
owl:		http://www.w3.org/2002/07/owl#
rdf:		http://www.w3.org/1999/02/22-rdf-syntax-ns#
xml:		http://www.w3.org/XML/1998/namespace
xsd:		http://www.w3.org/2001/XMLSchema#
geof:		http://www.opengis.net/def/function/geosparql/
obda:		https://w3id.org/obda/vocabulary#
rdfs:		http://www.w3.org/2000/01/rdf-schema#

[MappingDeclaration] @collection [[
mappingId	road
target		:{osm_id} a :road ; :name {name} ; :type {type} ; geo:asWKT {geom} . 
source		select osm_id,name,type,geom from roads
]]
```
log in protege when explicitly declare the datatype of geometry
```
>   ERROR  11:31:26  An error occurred during reasoning: it.unibz.inf.ontop.exception.MappingOntologyMismatchException: http://www.opengis.net/ont/geosparql#asWKT is declared as http://www.w3.org/2001/XMLSchema#string in the ontology, but is used as <http://www.opengis.net/ont/geosparql#wktLiteral> in the triplesMap:
[
id: road
target atom: triple(s,p,o) with s/RDF(http://jiaotong/ontologies#{}(TmpToTEXT(osm_id)),IRI), p/<http://www.opengis.net/ont/geosparql#asWKT>, o/RDF(TmpToTEXT(geom),http://www.opengis.net/ont/geosparql#wktLiteral)
source query: select osm_id,name,type,geom from roads
].
org.semanticweb.owlapi.reasoner.IllegalConfigurationException: it.unibz.inf.ontop.exception.MappingOntologyMismatchException: http://www.opengis.net/ont/geosparql#asWKT is declared as http://www.w3.org/2001/XMLSchema#string in the ontology, but is used as <http://www.opengis.net/ont/geosparql#wktLiteral> in the triplesMap:
[
id: road
target atom: triple(s,p,o) with s/RDF(http://jiaotong/ontologies#{}(TmpToTEXT(osm_id)),IRI), p/<http://www.opengis.net/ont/geosparql#asWKT>, o/RDF(TmpToTEXT(geom),http://www.opengis.net/ont/geosparql#wktLiteral)
source query: select osm_id,name,type,geom from roads
]
	at it.unibz.inf.ontop.owlapi.impl.QuestOWL.<init>(QuestOWL.java:115) ~[na:na]
	at it.unibz.inf.ontop.owlapi.impl.QuestOWLFactory.createReasoner(QuestOWLFactory.java:81) ~[na:na]
	at it.unibz.inf.ontop.owlapi.impl.QuestOWLFactory.createReasoner(QuestOWLFactory.java:94) ~[na:na]
	at it.unibz.inf.ontop.protege.core.OntopProtegeReasoner.reasonerSetup(OntopProtegeReasoner.java:65) ~[na:na]
	at it.unibz.inf.ontop.protege.core.OntopProtegeReasoner.<init>(OntopProtegeReasoner.java:34) ~[na:na]
	at it.unibz.inf.ontop.protege.core.OntopProtegeOWLFactory.createReasoner(OntopProtegeOWLFactory.java:72) ~[na:na]
	at it.unibz.inf.ontop.protege.core.OntopProtegeOWLFactory.createReasoner(OntopProtegeOWLFactory.java:25) ~[na:na]
	at org.protege.editor.owl.model.inference.ReasonerUtilities.createReasoner(ReasonerUtilities.java:20) ~[na:na]
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.ensureRunningReasonerInitialized(OWLReasonerManagerImpl.java:428) ~[na:na]
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.run(OWLReasonerManagerImpl.java:386) ~[na:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
Caused by: it.unibz.inf.ontop.exception.MappingOntologyMismatchException: http://www.opengis.net/ont/geosparql#asWKT is declared as http://www.w3.org/2001/XMLSchema#string in the ontology, but is used as <http://www.opengis.net/ont/geosparql#wktLiteral> in the triplesMap:
[
id: road
target atom: triple(s,p,o) with s/RDF(http://jiaotong/ontologies#{}(TmpToTEXT(osm_id)),IRI), p/<http://www.opengis.net/ont/geosparql#asWKT>, o/RDF(TmpToTEXT(geom),http://www.opengis.net/ont/geosparql#wktLiteral)
source query: select osm_id,name,type,geom from roads
]
	at it.unibz.inf.ontop.spec.mapping.validation.impl.MappingOntologyComplianceValidatorImpl.validateAssertion(MappingOntologyComplianceValidatorImpl.java:74) ~[na:na]
	at it.unibz.inf.ontop.spec.mapping.validation.impl.MappingOntologyComplianceValidatorImpl.validate(MappingOntologyComplianceValidatorImpl.java:58) ~[na:na]
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convertPPMapping(SQLMappingExtractor.java:176) ~[na:na]
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.extract(SQLMappingExtractor.java:115) ~[na:na]
	at it.unibz.inf.ontop.spec.impl.DefaultOBDASpecificationExtractor.extract(DefaultOBDASpecificationExtractor.java:60) ~[na:na]
	at it.unibz.inf.ontop.injection.impl.OntopMappingConfigurationImpl.loadSpecification(OntopMappingConfigurationImpl.java:117) ~[na:na]
	at it.unibz.inf.ontop.injection.impl.OntopMappingSQLConfigurationImpl.loadSpecification(OntopMappingSQLConfigurationImpl.java:87) ~[na:na]
	at it.unibz.inf.ontop.injection.impl.OntopMappingSQLAllConfigurationImpl.loadSpecification(OntopMappingSQLAllConfigurationImpl.java:47) ~[na:na]
	at it.unibz.inf.ontop.injection.impl.OntopSQLOWLAPIConfigurationImpl.loadOBDASpecification(OntopSQLOWLAPIConfigurationImpl.java:34) ~[na:na]
	at it.unibz.inf.ontop.injection.impl.OntopOBDAConfigurationImpl.loadSpecification(OntopOBDAConfigurationImpl.java:44) ~[na:na]
	at it.unibz.inf.ontop.injection.OntopSystemConfiguration.loadQueryEngine(OntopSystemConfiguration.java:20) ~[na:na]
	at it.unibz.inf.ontop.owlapi.impl.QuestOWL.<init>(QuestOWL.java:110) ~[na:na]
	... 10 common frames omitted
Caused by: it.unibz.inf.ontop.exception.MappingOntologyMismatchException: http://www.opengis.net/ont/geosparql#asWKT is declared as http://www.w3.org/2001/XMLSchema#string in the ontology, but is used as <http://www.opengis.net/ont/geosparql#wktLiteral> in the triplesMap:
	at it.unibz.inf.ontop.spec.mapping.validation.impl.MappingOntologyComplianceValidatorImpl.checkDataOrAnnotationProperty(MappingOntologyComplianceValidatorImpl.java:194) ~[na:na]
	at it.unibz.inf.ontop.spec.mapping.validation.impl.MappingOntologyComplianceValidatorImpl.checkTripleObject(MappingOntologyComplianceValidatorImpl.java:141) ~[na:na]
	at it.unibz.inf.ontop.spec.mapping.validation.impl.MappingOntologyComplianceValidatorImpl.validateAssertion(MappingOntologyComplianceValidatorImpl.java:71) ~[na:na]
	... 21 common frames omitted
```
Informations about the attachments (ontology, mappings and queries that are necessary to reproduce the problem)
Provide the log file (more information on how to obtain it in the guidelines)

### Versions
Ontop 4.2.0
Protege 5.5.0
Java version 1.8.0_321

**Comment by ghxiao** [comment]
Hi,

I noticed two suspected things:

1. In the ontology, the following block should be not there. Otherwise, you are modifying geo:hasSerialization from the GeoSPARQL ontology.

```
###  http://www.opengis.net/ont/geosparql#hasSerialization
geo:hasSerialization rdfs:range xsd:string .
```

2. The mapping should be
```
mappingId	road
target		:{osm_id} a :road ; :name {name} ; :type {type} ; geo:asWKT {wkt}^^geo:wktLiteral . 
source		select osm_id,name,type, ST_AsText(geom) AS wkt from roads
```

Please give it a try.

Notice that the tutorial on Youtube is outdated. The following tutorial is up-to-date:
https://github.com/ontopic-vkg/destination-tutorial

**Comment by Cq5616** [comment]
Hi @ghxiao, thank you soooo much for your answer! It works!
