### ISSUE TITLE
Ontp plugin Protegè error

### ISSUE THREAD

**Issue by mariobove** [ontop/ontop#533]
when I run the ontop reasoner version 4.2.1 I get the following error "this RDF term type is abstract". In the logs it is not specified what the problem is but I get the following error.
  ERROR  11:49:12  An error occurred during reasoning: This RDF term type is abstract.
java.lang.UnsupportedOperationException: This RDF term type is abstract
	at it.unibz.inf.ontop.model.type.impl.RDFTermTypeImpl.lambda$new$0(RDFTermTypeImpl.java:26) ~[na:na]
	at it.unibz.inf.ontop.model.type.impl.RDFTermTypeImpl.getClosestDBType(RDFTermTypeImpl.java:43) ~[na:na]
	at it.unibz.inf.ontop.model.term.impl.TermFactoryImpl.getConversionFromRDFLexical2DB(TermFactoryImpl.java:1005) ~[na:na]
	at it.unibz.inf.ontop.spec.mapping.transformer.impl.ABoxFactIntoMappingConverterImpl.extractNaturalDBValue(ABoxFactIntoMappingConverterImpl.java:383) ~[na:na]
	at it.unibz.inf.ontop.spec.mapping.transformer.impl.ABoxFactIntoMappingConverterImpl.lambda$createSingleTypeDBValuesNode$20(ABoxFactIntoMappingConverterImpl.java:348) ~[na:na]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_121]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_121]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_121]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_121]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_121]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_121]
	at it.unibz.inf.ontop.spec.mapping.transformer.impl.ABoxFactIntoMappingConverterImpl.createSingleTypeDBValuesNode(ABoxFactIntoMappingConverterImpl.java:349) ~[na:na]
	at it.unibz.inf.ontop.spec.mapping.transformer.impl.ABoxFactIntoMappingConverterImpl.createPropertyIQ(ABoxFactIntoMappingConverterImpl.java:194) ~[na:na]
	at it.unibz.inf.ontop.spec.mapping.transformer.impl.ABoxFactIntoMappingConverterImpl.createIQ(ABoxFactIntoMappingConverterImpl.java:140) ~[na:na]
	at it.unibz.inf.ontop.spec.mapping.transformer.impl.ABoxFactIntoMappingConverterImpl.lambda$convert$2(ABoxFactIntoMappingConverterImpl.java:103) ~[na:na]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_121]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_121]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_121]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_121]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_121]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_121]
	at it.unibz.inf.ontop.spec.mapping.transformer.impl.ABoxFactIntoMappingConverterImpl.convert(ABoxFactIntoMappingConverterImpl.java:105) ~[na:na]
	at it.unibz.inf.ontop.spec.mapping.transformer.impl.DefaultMappingTransformer.transform(DefaultMappingTransformer.java:65) ~[na:na]
	at it.unibz.inf.ontop.spec.impl.DefaultOBDASpecificationExtractor.extract(DefaultOBDASpecificationExtractor.java:64) ~[na:na]
	at it.unibz.inf.ontop.injection.impl.OntopMappingConfigurationImpl.loadSpecification(OntopMappingConfigurationImpl.java:117) ~[na:na]
	at it.unibz.inf.ontop.injection.impl.OntopMappingSQLConfigurationImpl.loadSpecification(OntopMappingSQLConfigurationImpl.java:87) ~[na:na]
	at it.unibz.inf.ontop.injection.impl.OntopMappingSQLAllConfigurationImpl.loadSpecification(OntopMappingSQLAllConfigurationImpl.java:47) ~[na:na]
	at it.unibz.inf.ontop.injection.impl.OntopSQLOWLAPIConfigurationImpl.loadOBDASpecification(OntopSQLOWLAPIConfigurationImpl.java:34) ~[na:na]
	at it.unibz.inf.ontop.injection.impl.OntopOBDAConfigurationImpl.loadSpecification(OntopOBDAConfigurationImpl.java:44) ~[na:na]
	at it.unibz.inf.ontop.injection.OntopSystemConfiguration.loadQueryEngine(OntopSystemConfiguration.java:20) ~[na:na]
	at it.unibz.inf.ontop.owlapi.impl.QuestOWL.<init>(QuestOWL.java:110) ~[na:na]
	at it.unibz.inf.ontop.owlapi.impl.QuestOWLFactory.createReasoner(QuestOWLFactory.java:81) ~[na:na]
	at it.unibz.inf.ontop.owlapi.impl.QuestOWLFactory.createReasoner(QuestOWLFactory.java:94) ~[na:na]
	at it.unibz.inf.ontop.protege.core.OntopProtegeReasoner.reasonerSetup(OntopProtegeReasoner.java:65) ~[na:na]
	at it.unibz.inf.ontop.protege.core.OntopProtegeReasoner.<init>(OntopProtegeReasoner.java:34) ~[na:na]
	at it.unibz.inf.ontop.protege.core.OntopProtegeOWLFactory.createReasoner(OntopProtegeOWLFactory.java:72) ~[na:na]
	at it.unibz.inf.ontop.protege.core.OntopProtegeOWLFactory.createReasoner(OntopProtegeOWLFactory.java:25) ~[na:na]
	at org.protege.editor.owl.model.inference.ReasonerUtilities.createReasoner(ReasonerUtilities.java:20) ~[na:na]
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.ensureRunningReasonerInitialized(OWLReasonerManagerImpl.java:428) ~[na:na]
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.run(OWLReasonerManagerImpl.java:386) ~[na:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]

**Comment by bcogrel** [comment]
Hi Mario, thanks for reporting the issue. The error message could be made better.
I suspect you are having a literal in your ontology with an abstract datatype (e.g. rdfs:Resource, owl:real).

Would it be for you to share a minimal subset of your ontology file that reproduces the issue?

Best,
Benjamin
