### ISSUE TITLE
Rdb2RdfTest dg0016 Failure: SQL Query Syntax - Illegal Mix of Collation for UNION - TIMESTAMP 

### ISSUE THREAD

**Issue by thomasjtaylor** [ontop/ontop#558]
### Description
Running Ontop against Rdb2Rdf Test dg0016 (direct mapping) on MySQL with `'utf8_unicode_ci'` collation results in `SQLException: Illegal mix of collations for operation 'UNION'`. 

* Test Case: https://github.com/ontop/ontop/tree/version4/test/rdb2rdf-compliance/src/test/resources/D016
* JUnit Tests: https://github.com/ontop/ontop/blob/version4/test/rdb2rdf-compliance/src/test/java/RDB2RDFTest.java
* Database: Docker mysql:5
* JDBC Driver: mysql-connector-java:8.0.30
While the JUnit test is coded against a H2 memory database, I have modified it to run with different databases.

The problem appears comes down to how `TIMESTAMP` is handled in the SQL Query. It looks like `INTEGER`, `FLOAT`, and `DATE` are cast to `CHAR CHARACTER SET UTF8` while `TIMESTAMP` is not.

It also appears that using the `general` collation works, but `unicode` collation does not. Likely because the default collation is `general`... If I remove all `CHARACTER SET UTF8` statements from the query, it also works. So, either all results must be cast to utf8 character set or no results should be cast to utf8, but casting only some results to utf8 cause the problem.

### Workarounds:
1. Change `COLLATE 'utf8_unicode_ci'` to `COLLATE 'utf8_general_ci'`

#### Problem Query Fragment - `CAST(v7.EntranceDate AS CHAR(30))`
```
SELECT v7.`ID` AS `ID1m20`, 'http://example.com/base/Patient#EntranceDate' AS `v30`, CONCAT(REPLACE(CAST(v7.`EntranceDate` AS CHAR(30)),' ', 'T'),REPLACE(TIME_FORMAT(TIMEDIFF(NOW(),CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),'+%H:%i'),'+-','-')) AS `v49`, 3 AS `v9`
FROM `Patient` v7
```
#### Fixed Query Fragment -- `CAST(v7.EntranceDate AS CHAR(30) CHARACTER SET utf8)`
```
SELECT v7.`ID` AS `ID1m20`, 'http://example.com/base/Patient#EntranceDate' AS `v30`, CONCAT(REPLACE(CAST(v7.`EntranceDate` AS CHAR(30) CHARACTER SET utf8),' ', 'T'),REPLACE(TIME_FORMAT(TIMEDIFF(NOW(),CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),'+%H:%i'),'+-','-')) AS `v49`, 3 AS `v9`
FROM `Patient` v7
```

#### Source Table - MySQL (`sessionVariables=sql_mode=ANSI`)
Use `sql_mode=ANSI` to support the ANSI-formatted scripts provided by rdb2rdf.
```
CREATE SCHEMA IF NOT EXISTS "Rdb2RdfTest" CHARACTER SET utf8 COLLATE utf8_unicode_ci"
CREATE TABLE "Patient" (
"ID" INTEGER,
"FirstName" VARCHAR(50),
"LastName" VARCHAR(50),
"Sex" VARCHAR(6),
"Weight" REAL,
"Height" FLOAT,
"BirthDate" DATE,
"EntranceDate" TIMESTAMP,
"PaidInAdvance" BOOLEAN,
"Photo" VARBINARY(200),
PRIMARY KEY ("ID")
);
```
#### Ontop SQLPPMapping
```
[PrefixDeclaration]
rdf:		http://www.w3.org/1999/02/22-rdf-syntax-ns#
rdfs:		http://www.w3.org/2000/01/rdf-schema#
owl:		http://www.w3.org/2002/07/owl#
xsd:		http://www.w3.org/2001/XMLSchema#
obda:		https://w3id.org/obda/vocabulary#

[MappingDeclaration] @collection [[
mappingId	MAPPING-ID1
target		<http://example.com/base/Patient/ID={ID}> a <http://example.com/base/Patient> ; <http://example.com/base/Patient#ID> {ID}^^xsd:integer ; <http://example.com/base/Patient#FirstName> {FirstName}^^xsd:string ; <http://example.com/base/Patient#LastName> {LastName}^^xsd:string ; <http://example.com/base/Patient#Sex> {Sex}^^xsd:string ; <http://example.com/base/Patient#Weight> {Weight}^^xsd:double ; <http://example.com/base/Patient#Height> {Height}^^xsd:double ; <http://example.com/base/Patient#BirthDate> {BirthDate}^^xsd:date ; <http://example.com/base/Patient#EntranceDate> {EntranceDate}^^xsd:dateTime ; <http://example.com/base/Patient#PaidInAdvance> {PaidInAdvance}^^xsd:boolean ; <http://example.com/base/Patient#Photo> {Photo}^^xsd:hexBinary . 
source		SELECT * FROM `Patient`
]]
```

#### SPARQL Query
```
SELECT * WHERE {?s ?p ?o}
```

#### Ontop's SQL Query Translation
```
SELECT v23.`ID1m20` AS `ID1m20`, v23.`v30` AS `v30`, v23.`v49` AS `v49`, v23.`v9` AS `v9`
FROM (SELECT v1.`ID` AS `ID1m20`, 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type' AS `v30`, 'http://example.com/base/Patient' AS `v49`, 0 AS `v9`
FROM `Patient` v1
UNION ALL 
SELECT v3.`ID` AS `ID1m20`, 'http://example.com/base/Patient#FirstName' AS `v30`, v3.`FirstName` AS `v49`, 1 AS `v9`
FROM `Patient` v3
WHERE v3.`FirstName` IS NOT NULL
UNION ALL 
SELECT v5.`ID` AS `ID1m20`, 'http://example.com/base/Patient#Height' AS `v30`, CAST(v5.`Height` AS CHAR CHARACTER SET utf8) AS `v49`, 2 AS `v9`
FROM `Patient` v5
WHERE v5.`Height` IS NOT NULL
UNION ALL 
SELECT v7.`ID` AS `ID1m20`, 'http://example.com/base/Patient#EntranceDate' AS `v30`, CONCAT(REPLACE(CAST(v7.`EntranceDate` AS CHAR(30)),' ', 'T'),REPLACE(TIME_FORMAT(TIMEDIFF(NOW(),CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),'+%H:%i'),'+-','-')) AS `v49`, 3 AS `v9`
FROM `Patient` v7
UNION ALL 
SELECT v9.`ID` AS `ID1m20`, 'http://example.com/base/Patient#PaidInAdvance' AS `v30`, CASE     WHEN (NOT (v9.`PaidInAdvance` = 0)) THEN 'true'
    WHEN (v9.`PaidInAdvance` = 0) THEN 'false'
    ELSE NULL 
END AS `v49`, 4 AS `v9`
FROM `Patient` v9
WHERE v9.`PaidInAdvance` IS NOT NULL
UNION ALL 
SELECT v11.`ID` AS `ID1m20`, 'http://example.com/base/Patient#Sex' AS `v30`, v11.`Sex` AS `v49`, 1 AS `v9`
FROM `Patient` v11
WHERE v11.`Sex` IS NOT NULL
UNION ALL 
SELECT v13.`ID` AS `ID1m20`, 'http://example.com/base/Patient#ID' AS `v30`, CAST(v13.`ID` AS CHAR CHARACTER SET utf8) AS `v49`, 5 AS `v9`
FROM `Patient` v13
UNION ALL 
SELECT v15.`ID` AS `ID1m20`, 'http://example.com/base/Patient#Weight' AS `v30`, CAST(v15.`Weight` AS CHAR CHARACTER SET utf8) AS `v49`, 2 AS `v9`
FROM `Patient` v15
WHERE v15.`Weight` IS NOT NULL
UNION ALL 
SELECT v17.`ID` AS `ID1m20`, 'http://example.com/base/Patient#BirthDate' AS `v30`, CAST(v17.`BirthDate` AS CHAR CHARACTER SET utf8) AS `v49`, 6 AS `v9`
FROM `Patient` v17
WHERE v17.`BirthDate` IS NOT NULL
UNION ALL 
SELECT v19.`ID` AS `ID1m20`, 'http://example.com/base/Patient#Photo' AS `v30`, CAST(v19.`Photo` AS CHAR CHARACTER SET utf8) AS `v49`, 7 AS `v9`
FROM `Patient` v19
WHERE v19.`Photo` IS NOT NULL
UNION ALL 
SELECT v21.`ID` AS `ID1m20`, 'http://example.com/base/Patient#LastName' AS `v30`, v21.`LastName` AS `v49`, 1 AS `v9`
FROM `Patient` v21
WHERE v21.`LastName` IS NOT NULL
) v23
```
#### Java Stack Trace
```
2022-10-07T09:16:51,163 DEBUG [Thread-1] QuestStatement - Executing the query and get the result...
2022-10-07T09:16:51,193 ERROR [Thread-1] QuestStatement - java.sql.SQLException: Illegal mix of collations for operation 'UNION'
it.unibz.inf.ontop.exception.OntopQueryEvaluationException: java.sql.SQLException: Illegal mix of collations for operation 'UNION'
	at it.unibz.inf.ontop.answering.connection.impl.SQLQuestStatement.executeSelectQuery(SQLQuestStatement.java:202) ~[ontop-system-sql-core-4.2.1.jar:4.2.1]
	at it.unibz.inf.ontop.answering.connection.impl.QuestStatement.executeSelectQuery(QuestStatement.java:122) ~[ontop-system-core-4.2.1.jar:4.2.1]
	at it.unibz.inf.ontop.answering.connection.impl.QuestStatement.executeSelectQuery(QuestStatement.java:114) ~[ontop-system-core-4.2.1.jar:4.2.1]
	at it.unibz.inf.ontop.answering.connection.impl.QuestStatement$QueryExecutionThread.run(QuestStatement.java:97) ~[ontop-system-core-4.2.1.jar:4.2.1]
Caused by: java.sql.SQLException: Illegal mix of collations for operation 'UNION'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1200) ~[mysql-connector-java-8.0.30.jar:8.0.30]
```

### Versions

* Ontop: 4.2.1 (Maven Central)
* MySQL DB: mysql:5 (Docker Hub)
* JDBC Driver: mysql-connector-java:8.0.30 (Maven Central)

### Other Notes
After some more experimentation, it appears that if the first CAST in the query includes `CHARACTER SET utf8` then all of the subsequent CASTs must include `CHARACTER SET utf8`. However, if the first CAST doesn't include `CHARACTER SET utf8` it doesn't matter if any of the remaining CASTs include the character set.

```
# including CHARACTER SET in the first CAST statement requires all remaining CASTs to include charset
SELECT v5.`ID` AS `ID1m20`, 'http://example.com/base/Patient#Height' AS `v30`, CAST(v5.`Height` AS CHAR  CHARACTER SET utf8) AS `v49`, 2 AS `v9`

# excluding CHARACTER SET from the first CAST statement allows other CASTs to include or omit the charset
SELECT v5.`ID` AS `ID1m20`, 'http://example.com/base/Patient#Height' AS `v30`, CAST(v5.`Height` AS CHAR) AS `v49`, 2 AS `v9`
```

**Comment by bcogrel** [comment]
Hi @thomasjtaylor,

Many thanks for extensively testing MySQL. That's an interesting issue, we need to dive into it. 
Thanks for the suggestion.

Some of these tests (the ones about R2RML) were run once over 4.1.0 for MySQL and PostgreSQL: 
https://github.com/ontop/r2rml-implementation-report

We haven't run them recently, but normally, we should now get a better score for the development version. If you are interested, feel free to have a look.

Best,
Benjamin

**Comment by thomasjtaylor** [comment]
This may have been resolved in #779
