### ISSUE TITLE
Non-latin concept names error

### ISSUE THREAD

**Issue by ipostanogov** [ontop/ontop#56]
I run [easy tutorial](https://github.com/ontop/ontop/wiki/Easy-Tutorial%3A-Using-Ontop-API-from-Eclipse) with h2db and it worked fine.
Then I decided to test non-latin support and renamed `Author` to `Автор` both in [exampleBooks.obda](https://gist.github.com/ipostanogov/bc59163c4ff7eeacf72c) & [exampleBooks.owl](https://gist.github.com/ipostanogov/10658cb121bc85208aab). Example now hangs on `ioManager.load(obdafile)` consuming a lot of CPU & RAM.

**Comment by ipostanogov** [comment]
Could you allow '$' symbol?

I have
```
mappingId   cl_conference_participation_participation_type$id
target      :conference_participation/{conference_participation_id}/ :conference_participation_participation_type$id {conference_participation_participation_type$id} .
source      SELECT "conference_participation"."id" AS "conference_participation_id", "conference_participation"."participation_type$id" AS "conference_participation_participation_type$id" FROM "conference_participation"
```

Latest develop 1.14.1-SNAPSHOT fails with
```
Caused by: java.lang.RuntimeException: Syntax error: no viable alternative at input '$' Location: line 12:101
	at it.unibz.krdb.obda.parser.TurtleOBDAParser.recover(TurtleOBDAParser.java:190)
	at it.unibz.krdb.obda.parser.TurtleOBDAParser.object(TurtleOBDAParser.java:1185)
	at it.unibz.krdb.obda.parser.TurtleOBDAParser.objectList(TurtleOBDAParser.java:921)
	at it.unibz.krdb.obda.parser.TurtleOBDAParser.predicateObjectList(TurtleOBDAParser.java:780)
	at it.unibz.krdb.obda.parser.TurtleOBDAParser.triples(TurtleOBDAParser.java:735)
	at it.unibz.krdb.obda.parser.TurtleOBDAParser.triplesStatement(TurtleOBDAParser.java:496)
	at it.unibz.krdb.obda.parser.TurtleOBDAParser.parse(TurtleOBDAParser.java:394)
	at it.unibz.krdb.obda.parser.TurtleOBDASyntaxParser.parse(TurtleOBDASyntaxParser.java:92)
	... 26 more
```

P.S. I checked Protege 4.3.0. '$' is valid symbol in IRI.

**Comment by skomlaebri** [comment]
Hi,
our parser do not support it because rdf and sparql specification do not allow $ in the prefix when the compact format is used (See http://www.w3.org/TR/turtle/#sec-grammar-grammar). If you need to use the dollar you can write the complete IRI.
Example in the mapping instead of :conference_participation_participation_type$id you can use
<http://www.theprefix.org/conference_participation_participation_type$id>

**Comment by ghxiao** [comment]
Another workaround is the define a prefix 

`temp:  http://www.theprefix.org/conference_participation_participation_type$`

and later use `temp:id` in your mapping.

**Comment by ipostanogov** [comment]
@skomlaebri, latest develop snapshot fails at

```
mappingId   cl_conference_participation_participation_type$id
target      :conference_participation/{conference_participation_id}/ http://www.theprefix.org/conference_participation_participation_type$id {conference_participation_participation_type$id} .
source      SELECT "conference_participation"."id" AS "conference_participation_id", "conference_participation"."participation_type$id" AS "conference_participation_participation_type$id" FROM "conference_participation"
```

and even at 
```
mappingId   cl_conference_participation_participation_type$id
target      http://www.theprefix.org/conference_participation/{conference_participation_id}/ http://www.theprefix.org/conference_participation_participation_type$id {conference_participation_participation_type$id} .
source      SELECT "conference_participation"."id" AS "conference_participation_id", "conference_participation"."participation_type$id" AS "conference_participation_participation_type$id" FROM "conference_participation"
```
Have I misunderstood you?

**Comment by skomlaebri** [comment]
Hi you need to include the iri between angle brackets. 

So <http://www.theprefix.org/conference_participation_participation_type$id>

**Comment by ipostanogov** [comment]
Thanks, now my code almost works!

> Just for history: adding DEFAULT_PREFIX (`http://www.theprefix.org/` in this thread) will lead to compact format on save using ModelIOManager and afterwards to the discussed parse error on load.

If I open the following ontology & mapping -> go to "ontop Mappings" -> "Mapping manager" -> "Select datasource:" **it will hang ontopro-plugin-with-protege-1.14.0.zip bundle**.

reply.owl:
```
<?xml version="1.0"?>
<rdf:RDF xmlns="http://www.theprefix.org#"
     xml:base="http://www.theprefix.org"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">
    <owl:Ontology rdf:about="http://www.theprefix.org"/>

    <!-- http://www.theprefix.org#conference_participation_conference$id -->
    <owl:DatatypeProperty rdf:about="http://www.theprefix.org#conference_participation_conference$id"/>    
</rdf:RDF>
```

reply.obda:
```
[PrefixDeclaration]
owl:		http://www.w3.org/2002/07/owl#
rdf:		http://www.w3.org/1999/02/22-rdf-syntax-ns#
xsd:		http://www.w3.org/2001/XMLSchema#
quest:		http://obda.org/quest#
rdfs:		http://www.w3.org/2000/01/rdf-schema#

[SourceDeclaration]
sourceUri	reply.owl
connectionUrl	jdbc:postgresql://localhost/reply
username	ipostanogov
password	ipostanogov
driverClass	org.postgresql.Driver

[MappingDeclaration] @collection [[
mappingId	cl_conference_participation_conference$id
target		<http://www.theprefix.org#conference_participation/{conference_participation_id}/> <http://www.theprefix.org#conference_participation_conference$id> {conference_participation_conference$id} . 
source		SELECT "conference_participation"."id" AS "conference_participation_id", "conference_participation"."conference$id" AS "conference_participation_conference$id" FROM "conference_participation"
]]
```
