### ISSUE TITLE
Rdb2RdfTest Problem with Querying Postgresql with many-to-many relations (INT treated as TEXT)

### ISSUE THREAD

**Issue by thomasjtaylor** [ontop/ontop#564]
### Description
I am running the [RDB2RDFTest.java](https://github.com/ontop/ontop/blob/c3baf4b1ff34b52d2423c86ddc48c0f3569a1c3f/test/rdb2rdf-compliance/src/test/java/RDB2RDFTest.java) tests on different DBMS to validate functionality. In this particular case, I'm running against docker `postgresql:13` (it also is reproducible with Ontop's `ontop/ontop-pgsql` docker image, based on `postgres:9` ).

I've revised the H2-based test case to use Postgresql:
[RDB2RDFTestPostgres.java.txt](https://github.com/ontop/ontop/files/9823009/RDB2RDFTestPostgres.java.txt)
https://github.com/thomasjtaylor/ontop/commit/259ba1d258b4436ea01c49356bc0a5e13a60382a

Several of the Rdb2Rdf tests fail for various reasons (e.g., problems comparing XSD.DOUBLE, timezones, bnodes, etc.). For reference, `dg` prefixes refer to rdb2rdf direct mapping tests, while `tc` prefixes` refer to custom r2rml mappings.
```
FAILED 29 ["tc0003a", "dg0005", "dg0005-modified", "tc0005a", "tc0005a-modified",
 "tc0005b", "tc0005b-modified", "dg0011", "dg0012", "dg0012-modified", "tc0012a",
 "tc0012a-modified", "tc0012e", "tc0012e-modified", "dg0014", "dg0016", "tc0016a", 
"tc0016b", "tc0016b-modified", "tc0016c", "tc0016d", "tc0016e", "dg0018", "tc0019a",
 "dg0021", "dg0022", "dg0023", "dg0024", "dg0025"]
```
**JUnit Test Results:** [RDB2RDFTestPostgres-all-tests-20221019-140353.xml.txt](https://github.com/ontop/ontop/files/9823121/RDB2RDFTestPostgres-all-tests-20221019-140353.xml.txt)

For this issue, there is a problem with `INTEGER` columns in complex foreign keys.
`"dg0011","dg0014","dg0021","dg022","dg0023","dg0024","dg0025"`
**JUnit Test Results:** [RDB2RDFTestPostgres-foreignkeys-20221019-141052.xml.txt](https://github.com/ontop/ontop/files/9823124/RDB2RDFTestPostgres-foreignkeys-20221019-141052.xml.txt)

The simplest test appears to be `D0011: Database with many to many relations`:
[D0011/create.sql](https://github.com/ontop/ontop/blob/c3baf4b1ff34b52d2423c86ddc48c0f3569a1c3f/test/rdb2rdf-compliance/src/test/resources/D011/create.sql)
```
CREATE TABLE "Student" (
"ID" integer PRIMARY KEY,
"FirstName" varchar(50),
"LastName" varchar(50)
);
CREATE TABLE "Sport" (
"ID" integer PRIMARY KEY,
"Description" varchar(50)
);
CREATE TABLE "Student_Sport" (
"ID_Student" integer,
"ID_Sport" integer,
PRIMARY KEY ("ID_Student","ID_Sport"),
FOREIGN KEY ("ID_Student") REFERENCES "Student"("ID"),
FOREIGN KEY ("ID_Sport") REFERENCES "Sport"("ID")
);

INSERT INTO "Student" ("ID","FirstName","LastName") VALUES (10,'Venus', 'Williams');
INSERT INTO "Student" ("ID","FirstName","LastName") VALUES (11,'Fernando', 'Alonso');
INSERT INTO "Student" ("ID","FirstName","LastName") VALUES (12,'David', 'Villa');

INSERT INTO "Sport" ("ID", "Description") VALUES (110,'Tennis');
INSERT INTO "Sport" ("ID", "Description") VALUES (111,'Football');
INSERT INTO "Sport" ("ID", "Description") VALUES (112,'Formula1');

INSERT INTO "Student_Sport" ("ID_Student", "ID_Sport") VALUES (10,110);
INSERT INTO "Student_Sport" ("ID_Student", "ID_Sport") VALUES (11,111);
INSERT INTO "Student_Sport" ("ID_Student", "ID_Sport") VALUES (11,112);
INSERT INTO "Student_Sport" ("ID_Student", "ID_Sport") VALUES (12,111);
```
Running the JUnit Test results in the following stack trace:
```
4:11:07.301 [Thread-7] ERROR i.u.i.o.a.c.impl.QuestStatement - ERROR: function replace(integer, unknown, unknown) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 475
it.unibz.inf.ontop.exception.OntopQueryEvaluationException: ERROR: function replace(integer, unknown, unknown) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 475
	at it.unibz.inf.ontop.answering.connection.impl.SQLQuestStatement.executeConstructQuery(SQLQuestStatement.java:234)
	at it.unibz.inf.ontop.answering.connection.impl.QuestStatement.executeConstructQuery(QuestStatement.java:152)
	at it.unibz.inf.ontop.answering.connection.impl.QuestStatement.executeConstructQuery(QuestStatement.java:144)
	at it.unibz.inf.ontop.answering.connection.impl.QuestStatement$QueryExecutionThread.run(QuestStatement.java:97)
```
Turning on debug logging, shows that ultimately the `INTEGER` `Student.ID` is being assumed to be `TEXT`:
[RDB2RDFTestPostgres-D0011-debug.txt](https://github.com/ontop/ontop/files/9823211/RDB2RDFTestPostgres-D0011-debug.txt)
```
SELECT ('http://example.com/base/Student/ID=' || REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(v1."ID", '%', '%25'), ' ', '%20'), '!', '%21'), '"', '%22'), '#', '%23'), '$', '%24'), '&', '%26'), '''', '%27'), '(', '%28'), ')', '%29'), '*', '%2A'), '+', '%2B'), ',', '%2C'), '/', '%2F'), ':', '%3A'), ';', '%3B'), '<', '%3C'), '=', '%3D'), '>', '%3E'), '?', '%3F'), '@', '%40'), '[', '%5B'), '\', '%5C'), ']', '%5D'), '^', '%5E'), '`', '%60'), '{', '%7B'), '|', '%7C'), '}', '%7D')) AS "v10", 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type' AS "v19", 'http://example.com/base/Student' AS "v38", 0 AS "v8"
FROM "Student" v1
```
If I try to re-run this query fragment directly in `psql`, I get the same error.

### Potential Workarounds
However, I can get this to work in any one of the following ways:
1. Use Postgres `::text` conversion `REPLACE(v1."ID"::text, '%', '%25')`
2. Use `CAST` `REPLACE(CAST(v1."ID" AS TEXT), '%', '%25')`
3. Remove the `REPLACE` operators. `v1."ID"`
```
SELECT ('http://example.com/base/Student/ID=' || v1."ID") AS "v10", 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type' AS "v19", 'http://example.com/base/Student' AS "v38", 0 AS "v8"
FROM "Student" v1
```
4. Remove the `FOREIGN KEY` statements from the `Student_Sport` table.
```
CREATE TABLE "Student_Sport" (
"ID_Student" integer,
"ID_Sport" integer,
PRIMARY KEY ("ID_Student","ID_Sport"),
--FOREIGN KEY ("ID_Student") REFERENCES "Student"("ID"),
--FOREIGN KEY ("ID_Sport") REFERENCES "Sport"("ID")
);
```
Perhaps the `INTEGERToTEXT` operation could be updated to fix this issue?

### Steps to Reproduce
1. Start Postgres Database: `docker run --name ontop_postgres_running -p 7777:5432 -e POSTGRES_PASSWORD=postgres2 -d ontop/ontop-pgsql` (Note: the ontop-pgsql database takes a long time to start/initialize, prefer postgres:13)
2. Make sure Postgres JDBC Driver is on classpath (default RDB2RDFTest only includes H2)
3. Run the `RDB2RDFTestPostgrs.java` Unit Test

**Expected behavior:** 
Rdb2Rdf Test Succeeds
[D011/directGraph.ttl](https://github.com/ontop/ontop/blob/c3baf4b1ff34b52d2423c86ddc48c0f3569a1c3f/test/rdb2rdf-compliance/src/test/resources/D011/directGraph.ttl)

**Actual behavior:**
Rdb2Rdf Test Fails

**Reproduces how often:**
Always

### Versions
Ontop: `4.3.0-SNAPSHOT` (source); also occurs with Ontop `4.2.1` (maven central)
Postgresql: docker `postgres:13`; also occurs with  `ontop/ontop-pgsql`
Postgres Driver: `42.5.0`; (also occurs with earlier drivers)

### Additional Information

I've committed this test case to my fork: 
https://github.com/thomasjtaylor/ontop/commit/259ba1d258b4436ea01c49356bc0a5e13a60382a

**Comment by thomasjtaylor** [comment]
Repeating this test on `dg0014`, the test passes if I comment out the `ename`, `job` columns and `LIKES` table, but if I add any of these back to the schema the `replace(integer, unknown, unknown)` error returns. It also doesn't matter if `ename` and/or `job` are placed after `deptno`. This is the minimal 'working' example.
```
CREATE TABLE "DEPT" (
      "deptno" INTEGER UNIQUE,
      "dname" VARCHAR(30),
      "loc" VARCHAR(100)
      );
--INSERT INTO "DEPT" ("deptno", "dname", "loc") VALUES (10, 'APPSERVER', 'NEW YORK');

CREATE TABLE "EMP" (
      "empno" INTEGER PRIMARY KEY,
--      "ename" VARCHAR(100),
--      "job" VARCHAR(30),
	  "deptno" INTEGER REFERENCES "DEPT" ("deptno"),
	  "etype" VARCHAR(30)
	  );
--INSERT INTO "EMP" ("empno", "ename", "job", "deptno", "etype" ) VALUES (7369, 'SMITH', 'CLERK', 10, 'PART_TIME');
--INSERT INTO "EMP" ("empno",  "deptno", "etype" ) VALUES (7369,  10, 'PART_TIME');

--CREATE TABLE "LIKES" (
--      "id" INTEGER,
--      "likeType" VARCHAR(30),
--      "likedObj" VARCHAR(100));
--INSERT INTO "LIKES" ("id", "likeType", "likedObj") VALUES (7369, 'Playing', 'Soccer');
--INSERT INTO "LIKES" ("id", "likeType", "likedObj") VALUES (7369, 'Watching', 'Basketball');
```

**Comment by thomasjtaylor** [comment]
Repeating on test `dg0022`. Works if I remove `attrB`
```
CREATE TABLE "Target" (
	"litattr1" INT,
	PRIMARY KEY("litattr1"),
	"key1attr1" CHAR(4),
	"key1attr2" CHAR(4),
	UNIQUE ("key1attr1", "key1attr2"),
	"key2attr1" CHAR(4),
	"key2attr2" CHAR(4),
	UNIQUE ("key2attr2", "key2attr1")
);

CREATE TABLE "Source" (
	"ID" INT,
	PRIMARY KEY("ID"),
	"attrA" CHAR(4)
	--"attrB" CHAR(4)
	--FOREIGN KEY ("attrA", "attrB") REFERENCES "Target"("key2attr2", "key2attr1")
);

INSERT INTO "Target" ("litattr1", "key1attr1", "key1attr2", "key2attr1", "key2attr2")
              VALUES (1010      , 'K1A1'     , 'K1A2'     , 'K2A1'     , 'K2A2');

--INSERT INTO "Source" ("ID", "attrA", "attrB")
--              VALUES (1100, 'K2A2' , 'K2A1' );
INSERT INTO "Source" ("ID", "attrA")
              VALUES (1100, 'K2A2' );
```
Comparing the `QuestQueryProcessor - Resulting native query` from the log:

Excluding `Source.attrB`:
```
# SQLGeneratorImpl - New query after the dialect-specific extra normalization:
UNION [v14, v28, v6, v0, ID1m4, litattr11m10, ID1m11, ID1m12, litattr11m13, litattr11m14, litattr11m15, litattr11m16, litattr11m17]
   CONSTRUCT [v14, v28, v6, v0, ID1m4, litattr11m10, ID1m11, ID1m12, litattr11m13, litattr11m14, litattr11m15, litattr11m16, litattr11m17] [v6/"0"^^BIGINT, ID1m11/NULL-INTEGER(), litattr11m13/NULL-INTEGER(), litattr11m10/NULL-INTEGER(), v14/"http://www.w3.org/1999/02/22-rdf-syntax-ns#type"^^TEXT, litattr11m16/NULL-INTEGER(), litattr11m17/NULL-INTEGER(), v0/"0"^^BIGINT, litattr11m14/NULL-INTEGER(), litattr11m15/NULL-INTEGER(), v28/"http://example.com/base/Source"^^TEXT, ID1m12/NULL-INTEGER()]
      EXTENSIONAL "Source"(0:ID1m4)
...
# QueryQueryProcessor - Resulting native query:
CONSTRUCT [s, p, o] [p/RDF(v14,IRI), s/RDF(DB_IDX_9(v0,http://example.com/base/Source/ID={}(ID1m4),http://example.com/base/Target/litattr1={}(litattr11m10),http://example.com/base/Source/ID={}(ID1m11),http://example.com/base/Source/ID={}(ID1m12),http://example.com/base/Target/litattr1={}(litattr11m13),http://example.com/base/Target/litattr1={}(litattr11m14),http://example.com/base/Target/litattr1={}(litattr11m15),http://example.com/base/Target/litattr1={}(litattr11m16),http://example.com/base/Target/litattr1={}(litattr11m17)),IRI), o/RDF(v28,RDF_TYPE{0=IRI,1=xsd:integer,2=xsd:string}(v6))]
   NATIVE [ID1m11, ID1m12, ID1m4, litattr11m10, litattr11m13, litattr11m14, litattr11m15, litattr11m16, litattr11m17, v0, v14, v28, v6]
SELECT v19."ID1m11" AS "ID1m11", v19."ID1m12" AS "ID1m12", v19."ID1m4" AS "ID1m4", v19."litattr11m10" AS "litattr11m10", v19."litattr11m13" AS "litattr11m13", v19."litattr11m14" AS "litattr11m14", v19."litattr11m15" AS "litattr11m15", v19."litattr11m16" AS "litattr11m16", v19."litattr11m17" AS "litattr11m17", v19."v0" AS "v0", v19."v14" AS "v14", v19."v28" AS "v28", v19."v6" AS "v6"
FROM (SELECT CAST(NULL AS INTEGER) AS "ID1m11", CAST(NULL AS INTEGER) AS "ID1m12", v1."ID" AS "ID1m4", CAST(NULL AS INTEGER) AS "litattr11m10", CAST(NULL AS INTEGER) AS "litattr11m13", CAST(NULL AS INTEGER) AS "litattr11m14", CAST(NULL AS INTEGER) AS "litattr11m15", CAST(NULL AS INTEGER) AS "litattr11m16", CAST(NULL AS INTEGER) AS "litattr11m17", 0 AS "v0", 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type' AS "v14", 'http://example.com/base/Source' AS "v28", 0 AS "v6"
FROM "Source" v1
...
```

Including `Source.attrB`:
```
# SQLGeneratorImpl - New query after the dialect-specific extra normalization:
UNION [v8, v16, v32, v7]
   CONSTRUCT [v8, v16, v32, v7] [v7/"0"^^BIGINT, v8/http://example.com/base/Source/ID={}(ID1m1), v16/"http://www.w3.org/1999/02/22-rdf-syntax-ns#type"^^TEXT, v32/"http://example.com/base/Source"^^TEXT]
      EXTENSIONAL "Source"(0:ID1m1)
   CONSTRUCT [v8, v16, v32, v7] [v7/"0"^^BIGINT, v8/http://example.com/base/Target/litattr1={}(litattr11m5), v16/"http://www.w3.org/1999/02/22-rdf-syntax-ns#type"^^TEXT, v32/"http://example.com/base/Target"^^TEXT]
      EXTENSIONAL "Target"(0:litattr11m5)
   CONSTRUCT [v8, v16, v32, v7] [v7/"1"^^BIGINT, v8/http://example.com/base/Source/ID={}(ID1m2), v16/"http://example.com/base/Source#ID"^^TEXT, v32/INTEGERToTEXT(ID1m2)]
      EXTENSIONAL "Source"(0:ID1m2)
...
# QuestQueryProcessor - Resulting native query:
CONSTRUCT [s, p, o] [p/RDF(v16,IRI), s/RDF(v8,IRI), o/RDF(v32,RDF_TYPE{0=IRI,1=xsd:integer,2=xsd:string}(v7))]
   NATIVE [v16, v32, v7, v8]
SELECT v21."v16" AS "v16", v21."v32" AS "v32", v21."v7" AS "v7", v21."v8" AS "v8"
FROM (SELECT 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type' AS "v16", 'http://example.com/base/Source' AS "v32", 0 AS "v7", ('http://example.com/base/Source/ID=' || REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(v1."ID", '%', '%25'), ' ', '%20'), '!', '%21'), '"', '%22'), '#', '%23'), '$', '%24'), '&', '%26'), '''', '%27'), '(', '%28'), ')', '%29'), '*', '%2A'), '+', '%2B'), ',', '%2C'), '/', '%2F'), ':', '%3A'), ';', '%3B'), '<', '%3C'), '=', '%3D'), '>', '%3E'), '?', '%3F'), '@', '%40'), '[', '%5B'), '\', '%5C'), ']', '%5D'), '^', '%5E'), '`', '%60'), '{', '%7B'), '|', '%7C'), '}', '%7D')) AS "v8"
FROM "Source" v1
```

**Comment by bcogrel** [comment]
Hi @thomasjtaylor, sorry again for the late reply and thanks for the reporting the issue.

Since 4.0, Ontop is more rigorous about data types and normally cast the arguments of IRI templates to string. It is just that we forgot to update that aspect in the mapping bootstrapper. We never detected before because we were only testing the bootstrapper with H2 on this dataset.

Here is my fix: https://github.com/ontop/ontop/commit/b17630acdfe9dccff58af4d110e5e9dfef5179ae .
It has already been merged in the `version4` branch.

Could you please confirm it works for you?

Best,
Benjamin
