### ISSUE TITLE
Ontop CLI - Make error messages more informative

### ISSUE THREAD

**Issue by apano-on** [ontop/ontop#579]
### Description

Error messages generated from the Ontop CLI when the properties, mapping or ontology files are not located are not sufficiently informative and succinct. Ontop generates a long thread of errors even if the DEBUG mode is not active. It should ideally only state that the file was not found.

### Steps to Reproduce

1. Run Ontop CLI with the university tutorial missplacing the input files. https://ontop-vkg.org/tutorial/endpoint/endpoint-cli.html
2. View long thread of error log, where only the second to last could be fully relevant

**Expected behavior:** Informative error message on file not found or unreachable. Also, the error message should be consistent for all 3 missing input files.

**Actual behavior:** Suboptimal error message logs
[ErrorLog_PropertiesFileNotFound_Ontopv4.2.2.txt](https://github.com/ontop/ontop/files/10209019/ErrorLog_PropertiesFileNotFound_Ontopv4.2.2.txt)
[ErrorLog_OBDAFileNotFound_Ontopv4.2.2.txt](https://github.com/ontop/ontop/files/10209020/ErrorLog_OBDAFileNotFound_Ontopv4.2.2.txt)

Properties file not found (last 2 blocks)
```
Caused by: it.unibz.inf.ontop.exception.InvalidOntopConfigurationException: Cannot reach the property file: bsbm2.properties
	at it.unibz.inf.ontop.injection.impl.OntopModelConfigurationImpl.extractProperties(OntopModelConfigurationImpl.java:247)
	at it.unibz.inf.ontop.injection.impl.OntopModelConfigurationImpl$DefaultOntopModelBuilderFragment.propertyFile(OntopModelConfigurationImpl.java:176)
	at it.unibz.inf.ontop.injection.impl.OntopModelConfigurationImpl$DefaultOntopModelBuilderFragment.propertyFile(OntopModelConfigurationImpl.java:171)
	at it.unibz.inf.ontop.injection.impl.OntopMappingConfigurationImpl$OntopMappingBuilderMixin.propertyFile(OntopMappingConfigurationImpl.java:336)
	at it.unibz.inf.ontop.injection.impl.OntopSQLOWLAPIConfigurationImpl$BuilderImpl.propertyFile(OntopSQLOWLAPIConfigurationImpl.java:113)
	at it.unibz.inf.ontop.injection.impl.OntopMappingConfigurationImpl$OntopMappingBuilderMixin.propertyFile(OntopMappingConfigurationImpl.java:220)
	at it.unibz.inf.ontop.endpoint.beans.OntopVirtualRepositoryBean.setupOntopConfiguration(OntopVirtualRepositoryBean.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 64 more
Exception in thread "main" java.lang.AssertionError
	at it.unibz.inf.ontop.cli.Ontop.main(Ontop.java:30)
```
Ontology or mapping file not found (last 2 blocks)
```
Caused by: java.io.FileNotFoundException: input/university-complete.ttl (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at org.semanticweb.owlapi.io.FileDocumentSource.getInputStream(FileDocumentSource.java:91)
	... 75 more
Exception in thread "main" java.lang.AssertionError
	at it.unibz.inf.ontop.cli.Ontop.main(Ontop.java:30)
```
**Reproduces how often:** Always

### Attached material

Full error logs attached.

### Versions

Ontop v4.2.2

### Additional Information

None

**Comment by SimoneFarallo** [comment]
I've the same errore in version 5.0.2.
I I'm trying to solve it, it gives the error it seems not to find the files but follow for an answer

**Comment by apano-on** [comment]
Last block of log messages in the stacktrace ```it.unibz.inf.ontop.exception.InvalidOntopConfigurationException: Cannot reach the property file: <filename>``` and ```java.io.FileNotFoundException: <filename> (No such file or directory)``` are probably sufficiently informative.
