### ISSUE TITLE
Unparseable date @ AdventureWorks2008 MS SQL

### ISSUE THREAD

**Issue by ipostanogov** [ontop/ontop#61]
I'm using [AdventureWorks Database 2008](http://msftdbprodsamples.codeplex.com/). The schema is [here](http://our.componentone.com/wp-content/uploads/2010/5/8540.AdventureWorks2008.pdf). A lot of tables have `ModifiedDate` field of type `datetime`.
In mapping manager I have a valid target & source. `Test SQL Query` works fine.
```
:specialoffer/{specialoffer_specialofferid}/ :SpecialOffer_ModifiedDate {specialoffer_modifieddate} . 

SELECT "SpecialOffer"."SpecialOfferID" AS "specialoffer_specialofferid", "SpecialOffer"."ModifiedDate" AS "specialoffer_modifieddate" FROM "Sales"."SpecialOffer"
```
Running SPARQL like
```
SELECT DISTINCT ?x ?y { ?x :SpecialOffer_ModifiedDate ?y }
```
I'm getting errors like
```
java.lang.RuntimeException: java.text.ParseException: Unparseable date: "May  2 2005 12:00AM"
```
-----------------------
Ontop: ontopPro-plugin-with-protege-1.15.0.zip. I've replaced `it.unibz.inf.obda.p4plugin-1.15.0.jar` with latest `develop` from this repo - doesn't work either. 
DBMS: Microsoft SQL Server 2008 R2
JDBC: "net.sourceforge.jtds" % "jtds" % "1.3.1"

**Comment by martinrezk** [comment]
Hi,

what's the type of SpecialOffer_ModifiedDate? Did you set it to xsd:dateTime ?

Btw... we are collecting use case... could you add yours here?

https://github.com/ontop/ontop/wiki/UseCases

cheers

M.

**Comment by ipostanogov** [comment]
Oh, seems working with xsd:dateTimeStamp. Thanks! You can move it to supported [here](https://github.com/ontop/ontop/wiki/OntopDatatypes) :)

Is there any other documented cases where range type is obligatory? Before that it has worked out of the box with any other simple type.

Added my use case.

**Comment by martinrezk** [comment]
thanks!

It shouldn't be mandatory. We will look into it. Thanks! also for the pointer and the use-case.

cheers

**Comment by martinrezk** [comment]
Hi againm we have a colleague in Oslo (Prof. Martin Giese) who is interested in your use case. If you can share your email and I will give it to him.

best

M.

**Comment by skomlaebri** [comment]
hi @ipostanogov  range time should not be mandatory and if your table is datetime in sql server it should be possible to return it as xds:dateTime.  Can you send ontology, mapping and schema or at least the complete logging file with the errors ? I will try to reproduce the problem in ontop .
Thanks

**Comment by ipostanogov** [comment]
hi @skomlaebri. schema is in the first post

adventureWorks.owl
```
<?xml version="1.0"?>
<rdf:RDF xmlns="http://knova.ru/adventureWorks.owl#"
     xml:base="http://knova.ru/adventureWorks.owl"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
     xmlns:reply="http://knova.ru/reply#">
    <owl:Ontology rdf:about="http://knova.ru/adventureWorks.owl"/>
    <!-- http://knova.ru/adventureWorks.owl#SpecialOffer_ModifiedDate -->
    <owl:DatatypeProperty rdf:about="http://knova.ru/adventureWorks.owl#SpecialOffer_ModifiedDate">
    </owl:DatatypeProperty>
    <!-- http://knova.ru/adventureWorks.owl#SpecialOffer -->
    <owl:Class rdf:about="http://knova.ru/adventureWorks.owl#SpecialOffer">
    </owl:Class>    
</rdf:RDF>
```
adventureWorks.obda
```
[PrefixDeclaration]
owl:		http://www.w3.org/2002/07/owl#
rdf:		http://www.w3.org/1999/02/22-rdf-syntax-ns#
xsd:		http://www.w3.org/2001/XMLSchema#
quest:		http://obda.org/quest#
rdfs:		http://www.w3.org/2000/01/rdf-schema#

[SourceDeclaration]
sourceUri	adventureWorks.owl
connectionUrl	jdbc:jtds:sqlserver://localhost:1433;DatabaseName=AdventureWorks2008R2
username	mssql
password	root
driverClass	net.sourceforge.jtds.jdbc.Driver

[MappingDeclaration] @collection [[
mappingId	cl_specialoffer
target		<http://knova.ru/adventureWorks.owl#specialoffer/{specialoffer_specialofferid}/> a <http://knova.ru/adventureWorks.owl#SpecialOffer> . 
source		SELECT "SpecialOffer"."SpecialOfferID" AS "specialoffer_specialofferid" FROM "Sales"."SpecialOffer"

mappingId	cl_specialoffer_modifieddate
target		<http://knova.ru/adventureWorks.owl#specialoffer/{specialoffer_specialofferid}/> <http://knova.ru/adventureWorks.owl#SpecialOffer_ModifiedDate> {specialoffer_modifieddate} . 
source		SELECT "SpecialOffer"."SpecialOfferID" AS "specialoffer_specialofferid", "SpecialOffer"."ModifiedDate" AS "specialoffer_modifieddate" FROM "Sales"."SpecialOffer"
]]
```
adventureWorks.q
```
[QueryGroup="COLUMNS"] @collection [[

[QueryItem="SpecialOffer_ModifiedDate"]
PREFIX : <http://knova.ru/adventureWorks.owl#>
SELECT DISTINCT ?x ?y { ?x :SpecialOffer_ModifiedDate ?y }
]]
```

log
```
Starting Protege Desktop (Version 5.0.0, Build = beta-17)
Platform:
    Java: JVM 1.7.0_79-b15 Memory: 1838M
    Language: ru, Country: RU
    Framework: Apache Software Foundation (1.7)
    OS: windows7 (6.1)
    Processor: x86-64
Plugin: Cajun Visualization Library (1.0.2)
Plugin: Guava: Google Core Libraries for Java (18.0.0)
Plugin: -ontopPro- (1.15.0)
Plugin: DL Query (2.0.1)
Plugin: OWLViz (4.1.4)
Plugin: OWL Code Generation Plug-in (1.0.2)
Plugin: OWL Difference (5.0.0)
Plugin: Protege Editor OWL (5.0.0.beta-17)
Plugin: Protege SPARQL Plugin (1.0.0)
Plugin: Explanation Workbench (2.0.0)
Plugin: Protege HermiT Integration (1.0.0)
Plugin: OntoGraf (1.0.3)
Plugin: Jdbc Registry (1.0.0)
Plugin: Protege JDBC Registry Plugin (1.0.2.2012_01_26_1133)
Plugin: OWL Difference Engine (2.0.0)
Plugin: OWLAPI RDF Library (1.0.2)
Plugin: owlapi-osgidistribution (3.5.1)
	Cajun Visualization Library Plugin has no plugin.xml resource
	Guava: Google Core Libraries for Java Plugin has no plugin.xml resource
	OWL Difference Engine Plugin has no plugin.xml resource
	OWLAPI RDF Library Plugin has no plugin.xml resource
	owlapi-osgidistribution Plugin has no plugin.xml resource
Using OWL API version 3.5.1
Rebuilding entity indices...
... rebuilt in 4 ms
#logback.classic pattern: %d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
Setting active ontology to OntologyID(OntologyIRI(<http://www.semanticweb.org/user/ontologies/2015/5/untitled-ontology-170>))
Rebuilding entity indices...
... rebuilt in 2 ms
01:16:12.596 [FelixDispatchQueue] DEBUG i.u.k.o.p.core.OBDAModelManager - ACTIVE ONTOLOGY CHANGED
01:16:12.598 [FelixDispatchQueue] DEBUG i.u.k.obda.model.impl.OBDAModelImpl - OBDA model is initialized!
... active ontology changed
Cannot generate ontology catalog for ontology at http://www.semanticweb.org/user/ontologies/2015/5/untitled-ontology-170
01:16:12.601 [FelixDispatchQueue] DEBUG i.u.k.o.p.core.OBDAModelManager - ONTOLOGY CREATED
Setting active ontology to OntologyID(OntologyIRI(<http://www.semanticweb.org/user/ontologies/2015/5/untitled-ontology-170>))
Rebuilding entity indices...
... rebuilt in 0 ms
01:16:12.661 [FelixDispatchQueue] DEBUG i.u.k.o.p.core.OBDAModelManager - ACTIVE ONTOLOGY CHANGED
... active ontology changed
01:16:12.661 [FelixDispatchQueue] DEBUG i.u.k.o.p.core.OBDAModelManager - VISIBILITY CHANGED
Using OWL API version 3.5.1
Rebuilding entity indices...
... rebuilt in 2 ms
Adding root folder: C:\ ...
	...done
loading OntologyID(Anonymous-0) from file:/C:/adventureWorks.owl
Setting active ontology to OntologyID(OntologyIRI(<http://knova.ru/adventureWorks.owl>))
Rebuilding entity indices...
... rebuilt in 2 ms
01:16:17.880 [AWT-EventQueue-0] DEBUG i.u.k.o.p.core.OBDAModelManager - ACTIVE ONTOLOGY CHANGED
01:16:17.880 [AWT-EventQueue-0] DEBUG i.u.k.obda.model.impl.OBDAModelImpl - OBDA model is initialized!
... active ontology changed
01:16:17.882 [AWT-EventQueue-0] DEBUG i.u.k.o.p.core.OBDAModelManager - ONTOLOGY LOADED/RELOADED
01:16:17.885 [AWT-EventQueue-0] DEBUG i.u.k.obda.model.impl.OBDAModelImpl - OBDA model is reset
Setting active ontology to OntologyID(OntologyIRI(<http://knova.ru/adventureWorks.owl>))
Rebuilding entity indices...
... rebuilt in 2 ms
01:16:18.125 [AWT-EventQueue-0] DEBUG i.u.k.o.p.core.OBDAModelManager - ACTIVE ONTOLOGY CHANGED
... active ontology changed
01:16:18.126 [AWT-EventQueue-0] DEBUG i.u.k.o.p.core.OBDAModelManager - VISIBILITY CHANGED
01:16:20.857 [AWT-EventQueue-0] DEBUG i.u.k.o.p.core.OBDAModelManager - ABOUT TO CLASSIFY
01:16:20.883 [Classification Thread] DEBUG i.u.k.obda.model.impl.OBDAModelImpl - OBDA model is initialized!
01:16:20.886 [Classification Thread] DEBUG i.u.k.o.o.owlapi3.QuestOWL - Load ontologies called. Translating ontologies.
01:16:20.888 [Classification Thread] DEBUG i.u.k.o.o.OWLAPI3TranslatorUtility - Load ontologies called. Translating ontologies.
01:16:20.895 [Classification Thread] DEBUG i.u.k.o.o.OWLAPI3TranslatorUtility - Ontology loaded: [Ontology info. Axioms: 0 Classes: 1 Object Properties: 0 Data Properties: 1]
01:16:20.896 [Classification Thread] DEBUG i.u.k.o.o.owlapi3.QuestOWL - Initializing a new Quest instance...
01:16:20.899 [Classification Thread] DEBUG i.u.k.obda.owlrefplatform.core.Quest - Quest configuration:
01:16:20.899 [Classification Thread] DEBUG i.u.k.obda.owlrefplatform.core.Quest - Extensional query rewriting enabled: false
01:16:20.899 [Classification Thread] DEBUG i.u.k.obda.owlrefplatform.core.Quest - Optimize TBox using class/property equivalences: true
01:16:20.899 [Classification Thread] DEBUG i.u.k.obda.owlrefplatform.core.Quest - Optimize TBox using dependencies in ABox: true
01:16:20.899 [Classification Thread] DEBUG i.u.k.obda.owlrefplatform.core.Quest - ABox mode: virtual
01:16:20.899 [Classification Thread] DEBUG i.u.k.obda.model.impl.OBDAModelImpl - OBDA model is initialized!
01:16:20.899 [Classification Thread] DEBUG i.u.k.obda.owlrefplatform.core.Quest - Initializing Quest...
01:16:20.900 [Classification Thread] DEBUG i.u.k.o.o.c.t.MappingVocabularyRepair - Fixing OBDA Model
01:16:20.900 [Classification Thread] DEBUG i.u.k.obda.model.impl.OBDAModelImpl - OBDA model is initialized!
01:16:20.909 [Classification Thread] DEBUG i.u.k.obda.owlrefplatform.core.Quest - Testing DB connection...
01:16:21.126 [Classification Thread] DEBUG i.u.k.obda.owlrefplatform.core.Quest - Connection Pool Properties:
01:16:21.126 [Classification Thread] DEBUG i.u.k.obda.owlrefplatform.core.Quest - Start size: 2
01:16:21.126 [Classification Thread] DEBUG i.u.k.obda.owlrefplatform.core.Quest - Max size: 20
01:16:21.126 [Classification Thread] DEBUG i.u.k.obda.owlrefplatform.core.Quest - Remove abandoned connections: false
01:16:21.159 [Classification Thread] DEBUG i.u.krdb.sql.JDBCConnectionManager - get metadata for SpecialOffer
01:16:21.182 [Classification Thread] DEBUG i.u.k.obda.owlrefplatform.core.Quest - Original mapping size: 2
01:16:21.192 [Classification Thread] DEBUG i.u.k.o.o.core.QuestUnfolder - TMapping size: 2
01:16:21.192 [Classification Thread] DEBUG i.u.k.o.o.core.QuestUnfolder - TMapping processing time: 7 ms
01:16:21.192 [Classification Thread] DEBUG i.u.k.o.o.core.QuestUnfolder - Appended 0 class assertions from ontology as fact rules
01:16:21.192 [Classification Thread] DEBUG i.u.k.o.o.core.QuestUnfolder - Appended 0 object property assertions as fact rules
01:16:21.195 [Classification Thread] DEBUG i.u.k.o.o.core.QuestUnfolder - Final set of mappings: 
 http://knova.ru/adventureWorks.owl#SpecialOffer_ModifiedDate(URI("http://knova.ru/adventureWorks.owl#specialoffer/{}/",t1),http://www.w3.org/2001/XMLSchema#dateTime(t11)) :- Sales.SpecialOffer(t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11), IS_NOT_NULL(t1), IS_NOT_NULL(t11)
http://knova.ru/adventureWorks.owl#SpecialOffer(URI("http://knova.ru/adventureWorks.owl#specialoffer/{}/",t1)) :- Sales.SpecialOffer(t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11), IS_NOT_NULL(t1)
triple(URI("http://knova.ru/adventureWorks.owl#specialoffer/{}/",t1),URI("http://knova.ru/adventureWorks.owl#SpecialOffer_ModifiedDate"),http://www.w3.org/2001/XMLSchema#dateTime(t11)) :- Sales.SpecialOffer(t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11), IS_NOT_NULL(t1), IS_NOT_NULL(t11)
triple(URI("http://knova.ru/adventureWorks.owl#specialoffer/{}/",t1),URI("http://www.w3.org/1999/02/22-rdf-syntax-ns#type"),URI("http://knova.ru/adventureWorks.owl#SpecialOffer")) :- Sales.SpecialOffer(t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11), IS_NOT_NULL(t1)
01:16:21.196 [Classification Thread] DEBUG i.u.k.obda.owlrefplatform.core.Quest - DB Metadata: 
Sales.SpecialOffer="Sales"."SpecialOffer"[SpecialOfferID:4:PK,Description:12,DiscountPct:3,Type:12,Category:12,StartDate:93,EndDate:93,MinQty:4,MaxQty:4,rowguid:1,ModifiedDate:93]

01:16:21.198 [Classification Thread] DEBUG i.u.k.o.o.c.t.SigmaTBoxOptimizer - Starting semantic-reduction
01:16:21.199 [Classification Thread] DEBUG i.u.k.obda.owlrefplatform.core.Quest - ... Quest has been initialized.
01:16:21.351 [Classification Thread] DEBUG i.u.k.o.o.owlapi3.QuestOWL - Quest has completed the setup and it is ready for query answering!
Initializing the reasoner by performing the following steps:
	class hierarchy
	object property hierarchy
	data property hierarchy
	class assertions
	object property assertions
	same individuals
Quest 1.15.0 (ontop) classified in 492ms
01:16:21.357 [AWT-EventQueue-0] INFO  i.u.k.o.p.core.OBDAModelManager - REASONER CHANGED
01:16:23.173 [AWT-EventQueue-0] DEBUG i.u.k.o.p.views.QueryInterfaceView - Query Manager view initialized
01:16:27.037 [Thread-5] DEBUG o.o.query.parser.QueryParserRegistry - Registered service class org.openrdf.query.parser.sparql.SPARQLParserFactory
01:16:27.090 [Thread-6] DEBUG i.u.k.o.o.core.QuestStatement - Executing SPARQL query: 
PREFIX : <http://knova.ru/adventureWorks.owl#>
SELECT DISTINCT ?x ?y { ?x :SpecialOffer_ModifiedDate ?y }

01:16:27.092 [Thread-6] DEBUG i.u.k.o.o.c.t.SparqlAlgebraToDatalogTranslator - SPARQL algebra: 
Distinct
   Projection
      ProjectionElemList
         ProjectionElem "x"
         ProjectionElem "y"
      StatementPattern
         Var (name=x)
         Var (name=-const-http://knova.ru/adventureWorks.owl#SpecialOffer_ModifiedDate-uri, value=http://knova.ru/adventureWorks.owl#SpecialOffer_ModifiedDate, anonymous)
         Var (name=y)

01:16:27.093 [Thread-6] DEBUG i.u.k.o.o.core.QuestStatement - Datalog program translated from the SPARQL query: 
ans10(x,y) :- http://knova.ru/adventureWorks.owl#SpecialOffer_ModifiedDate(x,y)
ans1(x,y) :- ans10(x,y)

01:16:27.094 [Thread-6] DEBUG i.u.k.o.o.core.QuestStatement - Flattened program: 
ans1(x,y) :- http://knova.ru/adventureWorks.owl#SpecialOffer_ModifiedDate(x,y)

01:16:27.094 [Thread-6] DEBUG i.u.k.o.o.core.QuestStatement - Replacing equivalences...
01:16:27.095 [Thread-6] DEBUG i.u.k.o.o.core.QuestStatement - Normalized program: 
ans1(x,y) :- http://knova.ru/adventureWorks.owl#SpecialOffer_ModifiedDate(x,y)

01:16:27.095 [Thread-6] DEBUG i.u.k.o.o.core.QuestStatement - Start the rewriting process...
01:16:27.096 [Thread-6] DEBUG i.u.k.o.o.core.QuestStatement - Start the partial evaluation process...
01:16:27.097 [Thread-6] DEBUG i.u.k.o.o.core.QuestStatement - Data atoms evaluated: 
ans1(URI("http://knova.ru/adventureWorks.owl#specialoffer/{}/",t1_2),http://www.w3.org/2001/XMLSchema#dateTime(t11_2)) :- Sales.SpecialOffer(t1_2,t2_2,t3_2,t4_2,t5_2,t6_2,t7_2,t8_2,t9_2,t10_2,t11_2), IS_NOT_NULL(t1_2), IS_NOT_NULL(t11_2)

01:16:27.097 [Thread-6] DEBUG i.u.k.o.o.core.QuestStatement - Irrelevant rules removed: 
ans1(URI("http://knova.ru/adventureWorks.owl#specialoffer/{}/",t1_2),http://www.w3.org/2001/XMLSchema#dateTime(t11_2)) :- Sales.SpecialOffer(t1_2,t2_2,t3_2,t4_2,t5_2,t6_2,t7_2,t8_2,t9_2,t10_2,t11_2), IS_NOT_NULL(t1_2), IS_NOT_NULL(t11_2)

01:16:27.098 [Thread-6] DEBUG i.u.k.o.o.core.QuestStatement - Boolean expression evaluated: 
ans1(URI("http://knova.ru/adventureWorks.owl#specialoffer/{}/",t1_2),http://www.w3.org/2001/XMLSchema#dateTime(t11_2)) :- Sales.SpecialOffer(t1_2,t2_2,t3_2,t4_2,t5_2,t6_2,t7_2,t8_2,t9_2,t10_2,t11_2), IS_NOT_NULL(t1_2), IS_NOT_NULL(t11_2)

01:16:27.098 [Thread-6] DEBUG i.u.k.o.o.core.QuestStatement - Partial evaluation ended.
01:16:27.098 [Thread-6] DEBUG i.u.k.o.o.core.QuestStatement - Producing the SQL string...
01:16:27.101 [Thread-6] DEBUG i.u.k.o.o.core.QuestStatement - Resulting SQL: 
SELECT *
FROM (
SELECT DISTINCT 
   1 AS "xQuestType", NULL AS "xLang", ('http://knova.ru/adventureWorks.owl#specialoffer/' + CAST(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CAST(QVIEW1."SpecialOfferID" AS VARCHAR(8000)),' ', '%20'),'!', '%21'),'@', '%40'),'#', '%23'),'$', '%24'),'&', '%26'),'*', '%42'), '(', '%28'), ')', '%29'), '[', '%5B'), ']', '%5D'), ',', '%2C'), ';', '%3B'), ':', '%3A'), '?', '%3F'), '=', '%3D'), '+', '%2B'), '''', '%22'), '/', '%2F') as varchar(8000)) + CAST('/' as varchar(8000))) AS "x", 
   8 AS "yQuestType", NULL AS "yLang", CAST(QVIEW1."ModifiedDate" AS VARCHAR(8000)) AS "y"
 FROM 
"Sales"."SpecialOffer" QVIEW1
WHERE 
QVIEW1."SpecialOfferID" IS NOT NULL AND
QVIEW1."ModifiedDate" IS NOT NULL
) SUB_QVIEW

01:16:27.101 [Thread-6] DEBUG i.u.k.o.o.core.QuestStatement - Executing the SQL query and get the result...
01:16:27.103 [Thread-6] DEBUG i.u.k.o.o.core.QuestStatement - Execution finished.

java.lang.RuntimeException: java.text.ParseException: Unparseable date: "May  2 2005 12:00AM"
        at it.unibz.krdb.obda.owlrefplatform.core.resultset.QuestResultset.getConstant(QuestResultset.java:233)
        at it.unibz.krdb.obda.owlrefplatform.owlapi3.QuestOWLResultSet.getOWLPropertyAssertionObject(QuestOWLResultSet.java:116)
        at it.unibz.krdb.obda.protege4.gui.OWLResultSetTableModel.fetchRows(OWLResultSetTableModel.java:165)
        at it.unibz.krdb.obda.protege4.gui.OWLResultSetTableModel.access$200(OWLResultSetTableModel.java:38)
        at it.unibz.krdb.obda.protege4.gui.OWLResultSetTableModel$1.run(OWLResultSetTableModel.java:114)
Caused by: java.text.ParseException: Unparseable date: "May  2 2005 12:00AM"
        at java.text.DateFormat.parse(Unknown Source)
        at it.unibz.krdb.obda.owlrefplatform.core.resultset.QuestResultset.getConstant(QuestResultset.java:227)
        ... 4 more
```

**Comment by skomlaebri** [comment]
Hi, thanks for the data, there was indeed a problem handling different datetime format.
Please note as driver for SQLServer we don't officially support net.sourceforge.jtds, but only com.microsoft.sqlserver.jdbc.SQLServerDriver, so if the behaviour of the two jdbc driver differ, only SQLServerDriver is supported

**Comment by ipostanogov** [comment]
Hi, @skomlaebri. Still can't make it work.



[adventureWorks.q.txt](https://github.com/ontop/ontop/files/79803/adventureWorks.q.txt)
[adventureWorks.obda.txt](https://github.com/ontop/ontop/files/79804/adventureWorks.obda.txt)
[adventureWorks.owl.txt](https://github.com/ontop/ontop/files/79805/adventureWorks.owl.txt)
[log.txt](https://github.com/ontop/ontop/files/79806/log.txt)

**Comment by skomlaebri** [comment]
Hi @ipostanogov, I tried to replicate your problem. 
I tested AdventureWorks2008R2 with SQL Server 2008R2 and using sqljdbc4 driver version 4.0.2206.100 on our latest version 1.16.1 and no exception is generated. Can you tell me which are your settings?

**Comment by ipostanogov** [comment]
Hi @skomlaebri, I'm using [AdventureWorks2008R2](http://msftdbprodsamples.codeplex.com/downloads/get/478216) with SQL Server 2008R2 and [sqljdbc4.jar](https://www.microsoft.com/en-us/download/details.aspx?displaylang=en&id=11774) driver version 4.0.2206.100 on 1.16.1.

[log.txt](https://github.com/ontop/ontop/files/119289/log.txt)

P.S. The problem might be in the OS's localization. I have a Windows 7 (Russian)

**Comment by ipostanogov** [comment]
Looks OK in 1.17.0.

**Comment by skomlaebri** [comment]
Hi @ipostanogov, we just released version 1.17 today.  We made a fix adding localization in this release, I didn't had the time to inform you. I'm glad to hear now it's working properly.

**Comment by ipostanogov** [comment]
@skomlaebri, I've also tested it with jTDS. It works like a charm. Thanks!

**Comment by mfriedemann** [comment]
Hey,

ran into that problem yesterday, with v1.18.0, and the MSSQL server host using a German locale.

OnTop SQL query converted the `datetime` columns to `VARCHAR(8000)`:
```
...
SELECT 
   8 AS "oQuestType", NULL AS "oLang", CAST(QVIEW2."StartTime" AS VARCHAR(8000)) AS "o", 
...
```

```
Exception in thread "main" java.lang.RuntimeException: java.text.ParseException: Unparseable date: "Okt  2 2015  8:35AM"
	at it.unibz.inf.ontop.owlrefplatform.core.resultset.QuestTupleResultSet.getConstant(QuestTupleResultSet.java:260)
	at it.unibz.inf.ontop.owlrefplatform.owlapi.QuestOWLResultSet.getOWLObject(QuestOWLResultSet.java:163)
```

# Found a fix just now
When using the jTDS driver, you can supply the language to use in the connection URL.
## Append `;language=English` to the connection URL
Like so: `jdbc:jtds:sqlserver://<server-host>[:<port>]/<databaseName>;language=English`.

This way, the MS SQL server will make of use the given language via jTDS driver and convert the `datetime` columns appropriately.

HTH,
M.
