### ISSUE TITLE
[BUG] Union causes java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by 87royalts87** [ontop/ontop#742]
### Description
Hello :)
I'm using Ontop:5.1.0 connected to AWS Redshift using jdbc.
When I issue the following query:
`SELECT ?subject ?pred ?value ?subjectClass ?pToSubject ?pFromSubject {
      ?subject a     ?subjectClass;
               ?pred ?value {
        SELECT DISTINCT ?subject ?pToSubject ?pFromSubject {
          BIND(<[a IRI]> AS ?argument)
          VALUES ?subjectClass { <[a class]> }
          {   
            ?argument ?pToSubject ?subject.
            ?subject a         ?subjectClass;
                     ?sPred    ?sValue .
                
          }   
          UNION
          {   
            ?subject ?pFromSubject ?argument;
                     a         ?subjectClass;
                     ?sPred    ?sValue .
               
          }   
        }   
        LIMIT 7 OFFSET 0
      }   
      FILTER(isLiteral(?value))
    }   `

[a class] and [a IRI] was replaced by this placeholder, I got the following error:

`snapshot_docker_backend | {"@timestamp":"2023-08-16T11:22:39.203Z","message":"query:result-set-unblocked","application":"supply_chain_ontology","payload":{"queryId":"5dc0089a-26ce-48d0-8761-6c02456499f8","executionBeforeUnblockingDuration":697}}
snapshot_docker_backend | Exception in thread "RingBufferThread" java.lang.OutOfMemoryError: Java heap space
snapshot_docker_backend | Exception in thread "Catalina-utility-2" java.lang.OutOfMemoryError: Java heap space
snapshot_docker_backend | Exception in thread "Thread-4" java.lang.OutOfMemoryError: Java heap space
snapshot_docker_backend | org.eclipse.rdf4j.query.QueryEvaluationException: java.lang.NullPointerException
snapshot_docker_backend |       at it.unibz.inf.ontop.rdf4j.query.impl.OntopTupleQuery.evaluate(OntopTupleQuery.java:62)
snapshot_docker_backend |       at it.unibz.inf.ontop.rdf4j.query.impl.OntopTupleQuery.evaluate(OntopTupleQuery.java:69)
snapshot_docker_backend |       at it.unibz.inf.ontop.endpoint.processor.SparqlQueryExecutor.evaluateSelectQuery(SparqlQueryExecutor.java:140)
snapshot_docker_backend |       at it.unibz.inf.ontop.endpoint.processor.SparqlQueryExecutor.executeQuery(SparqlQueryExecutor.java:61)
snapshot_docker_backend |       at it.unibz.inf.ontop.endpoint.controllers.SparqlQueryController.query_get(SparqlQueryController.java:42)
snapshot_docker_backend |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
snapshot_docker_backend |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
snapshot_docker_backend |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
snapshot_docker_backend |       at java.base/java.lang.reflect.Method.invoke(Unknown Source)
snapshot_docker_backend |       at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
snapshot_docker_backend |       at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
snapshot_docker_backend |       at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
snapshot_docker_backend |       at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
snapshot_docker_backend |       at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
snapshot_docker_backend |       at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
snapshot_docker_backend |       at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
snapshot_docker_backend |       at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
snapshot_docker_backend |       at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
snapshot_docker_backend |       at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
snapshot_docker_backend |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:529)
snapshot_docker_backend |       at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
snapshot_docker_backend |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
snapshot_docker_backend |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
snapshot_docker_backend |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
snapshot_docker_backend |       at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
snapshot_docker_backend |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
snapshot_docker_backend |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
snapshot_docker_backend |       at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
snapshot_docker_backend |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
snapshot_docker_backend |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
snapshot_docker_backend |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
snapshot_docker_backend |       at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
snapshot_docker_backend |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
snapshot_docker_backend |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
snapshot_docker_backend |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
snapshot_docker_backend |       at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
snapshot_docker_backend |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
snapshot_docker_backend |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
snapshot_docker_backend |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
snapshot_docker_backend |       at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
snapshot_docker_backend |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
snapshot_docker_backend |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
snapshot_docker_backend |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
snapshot_docker_backend |       at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
snapshot_docker_backend |       at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
snapshot_docker_backend |       at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
snapshot_docker_backend |       at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
snapshot_docker_backend |       at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
snapshot_docker_backend |       at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
snapshot_docker_backend |       at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
snapshot_docker_backend |       at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
snapshot_docker_backend |       at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
snapshot_docker_backend |       at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
snapshot_docker_backend |       at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
snapshot_docker_backend |       at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
snapshot_docker_backend |       at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
snapshot_docker_backend |       at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
snapshot_docker_backend |       at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
snapshot_docker_backend |       at java.base/java.lang.Thread.run(Unknown Source)
snapshot_docker_backend | Caused by: java.lang.NullPointerException
snapshot_docker_backend |       at it.unibz.inf.ontop.rdf4j.query.impl.OntopTupleQuery.evaluate(OntopTupleQuery.java:55)
snapshot_docker_backend |       ... 58 more
snapshot_docker_backend | org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space
snapshot_docker_backend |       at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1087)
snapshot_docker_backend |       at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
snapshot_docker_backend |       at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
snapshot_docker_backend |       at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
snapshot_docker_backend |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:529)
snapshot_docker_backend |       at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
snapshot_docker_backend |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
snapshot_docker_backend |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
snapshot_docker_backend |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
snapshot_docker_backend |       at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
snapshot_docker_backend |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
snapshot_docker_backend |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
snapshot_docker_backend |       at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
snapshot_docker_backend |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
snapshot_docker_backend |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
snapshot_docker_backend |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
snapshot_docker_backend |       at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
snapshot_docker_backend |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
snapshot_docker_backend |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
snapshot_docker_backend |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
snapshot_docker_backend |       at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
snapshot_docker_backend |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
snapshot_docker_backend |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
snapshot_docker_backend |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
snapshot_docker_backend |       at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
snapshot_docker_backend |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
snapshot_docker_backend |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
snapshot_docker_backend |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
snapshot_docker_backend |       at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
snapshot_docker_backend |       at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
snapshot_docker_backend |       at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
snapshot_docker_backend |       at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
snapshot_docker_backend |       at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
snapshot_docker_backend |       at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
snapshot_docker_backend |       at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
snapshot_docker_backend |       at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
snapshot_docker_backend |       at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
snapshot_docker_backend |       at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
snapshot_docker_backend |       at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
snapshot_docker_backend |       at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
snapshot_docker_backend |       at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
snapshot_docker_backend |       at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
snapshot_docker_backend |       at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
snapshot_docker_backend |       at java.base/java.lang.Thread.run(Unknown Source)
snapshot_docker_backend | Caused by: java.lang.OutOfMemoryError: Java heap space
`

**Comment by bcogrel** [comment]
Hi @87royalts87, thanks for reporting the issue.

Have you tried this query with Ontop 5.0.2? Was it running?

Reformulating this query can be expensive when the mapping is large. Still I managed to run it on some datasets with PostgreSQL.

Feel free to send us the logs and the list of options enabled privately (https://ontop-vkg.org/community/contributing/bug-report.html#how-to-generate-the-log-file)

NB: the variable `?subjectClass` outside the `SELECT DISTINCT` is not connected to the variable `?subjectClass` inside the UNION because it is not projected by the `SELECT DISTINCT` subquery. Is it intended?

Best,
Benjamin

**Comment by 87royalts87** [comment]
Thank you for your reply :)
Unfortunately I can't test it using Ontop:5.0.2 cause we have some NULL values and the config option to ignore them just came up with ontop:5.1.0. This query worked several times for me but with one specific class it fails. More than that: The complete docker backend container crashes and remains unuseable.
Currently I'm waiting for the approval of the logs. As soon as I got this I will send this to you.
The query itself came from the aws_graph_explorer so I have no chance to change them unfortunately :/ 

regards
Stefan
