### ISSUE TITLE
Left Join Failure

### ISSUE THREAD

**Issue by jp3477** [ontop/ontop#803]
### Description

I am attempting to create a mapping on top of an MSSQL database. In my mapping's source query, I have a JOIN that succeeds when it is an INNER JOIN, but fails when it is an OUTER JOIN (LEFT & RIGHT). Some of the fields extracted from the JOIN clause are fed into placeholders within the target triples. Does Ontop support OUTER JOINs?

### Steps to Reproduce

1. Add mapping entry to `ont.obda` file with LEFT JOIN in source query
2. Start ontop client `ontop-cli-5.1.2/ontop endpoint --ontology=ont.ttl --mapping=ont.obda --properties==ont.properties`
3. Add mapping entry to .obda file with INNER JOIN in source query
4. Start ontop client `ontop-cli-5.1.2/ontop endpoint --ontology=ont.ttl --mapping=ont.obda --properties==ont.properties`

#### Mapping entry
```
mappingId	Observation.valueQuantity
target		:Observation/{measurement_id} fhir:value :Observation/{measurement_id}/valueQuantity . :Observation/{measurement_id}/valueQuantity a fhir:Quantity ; fhir:value :Observation/{measurement_id}/valueQuantity/value ; fhir:unit :Observation/{measurement_id}/valueQuantity/unit ; fhir:codeP :Observation/{measurement_id}/valueQuantity/code . :Observation/{measurement_id}/valueQuantity/value a fhir:decimal ; fhir:v {value}^^xsd:float . :Observation/{measurement_id}/valueQuantity/unit a fhir:string ; fhir:v {unit}^^xsd:string . :Observation/{measurement_id}/valueQuantity/code a fhir:code ; fhir:v {code}^^xsd:string . 
source		SELECT
                    measurement_id,
                    m.value_as_number [value],
                    unit_c.concept_code unit,
                    unit_c.concept_code code
                FROM
                    measurement m
                    LEFT JOIN concept unit_c ON unit_c.concept_id = m.unit_concept_id
                    AND unit_c.concept_id != 0
                WHERE
                    m.value_as_number IS NOT NULL
```

**Expected behavior:**

It is expected that running the ontop client will run successfully after this mapping is added to the `ont.obda` file.

**Actual behavior:**

The ontop client fails to load. Here is a relevant excerpt:

```
Caused by: it.unibz.inf.ontop.exception.InvalidMappingSourceQueriesException: The placeholder(s) value in the target do(es) not occur in source query of the mapping assertion
[id: Observation.valueQuantity
target atom: triple(s, p, o) with s/RDF(http://hl7.org/fhir/mcode.ttl#Observation/{}/valueQuantity/value(TmpToNVARCHAR(measurement_id)),IRI), p/<file:///path/to/ont/fhir.ttl#v>, o/RDF(TmpToNVARCHAR(value),xsd:string)
source query: SELECT measurement_id, m.value_as_number value, unit_c.concept_code unit, unit_c.concept_code code FROM measurement m LEFT JOIN concept unit_c ON unit_c.concept_id = m.unit_concept_id AND unit_c.concept_id != 0 WHERE m.value_as_number IS NOT NULL]
	at it.unibz.inf.ontop.spec.mapping.pp.impl.SQLPPMappingConverterImpl.convert(SQLPPMappingConverterImpl.java:130)
	at it.unibz.inf.ontop.spec.mapping.pp.impl.SQLPPMappingConverterImpl.convert(SQLPPMappingConverterImpl.java:83)
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convert(SQLMappingExtractor.java:248)
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convert(SQLMappingExtractor.java:219)
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convert(SQLMappingExtractor.java:188)
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convertPPMapping(SQLMappingExtractor.java:153)
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.extract(SQLMappingExtractor.java:108)
	at it.unibz.inf.ontop.spec.impl.DefaultOBDASpecificationExtractor.extract(DefaultOBDASpecificationExtractor.java:51)
	at it.unibz.inf.ontop.injection.impl.OntopMappingConfigurationImpl.loadSpecification(OntopMappingConfigurationImpl.java:130)
	at it.unibz.inf.ontop.injection.impl.OntopMappingSQLConfigurationImpl.loadSpecification(OntopMappingSQLConfigurationImpl.java:85)
	at it.unibz.inf.ontop.injection.impl.OntopMappingSQLAllConfigurationImpl.loadSpecification(OntopMappingSQLAllConfigurationImpl.java:47)
	at it.unibz.inf.ontop.injection.impl.OntopSQLOWLAPIConfigurationImpl.loadOBDASpecification(OntopSQLOWLAPIConfigurationImpl.java:35)
	at it.unibz.inf.ontop.injection.impl.OntopOBDAConfigurationImpl.loadSpecification(OntopOBDAConfigurationImpl.java:44)
	at it.unibz.inf.ontop.injection.OntopSystemConfiguration.loadQueryEngine(OntopSystemConfiguration.java:20)
	at it.unibz.inf.ontop.rdf4j.repository.impl.OntopVirtualRepository.initializeInternal(OntopVirtualRepository.java:72)
	... 41 more
Exception in thread "main" java.lang.AssertionError
	at it.unibz.inf.ontop.cli.Ontop.main(Ontop.java:30)

```

**Reproduces how often:**

Happens every time I attempt to start the client with the LEFT JOIN present. Works with only a JOIN present.

### Versions

Ontop client: 5.1.2

**Comment by kontchakov** [comment]
Hi Jason

Could you try with the AS keyword introducing column aliases? It's optional for MS SQL Server, but Ontop expects it.

Best
Roman

**Comment by jp3477** [comment]
Thanks for the reply, Roman. I just tried the query with AS added to the FROM and LEFT JOIN clauses, but still get the same errors.

Query:
```
SELECT
    measurement_id,
    m.value_as_number [value],
    unit_c.concept_code unit,
    unit_c.concept_code code
FROM
    measurement AS m
    LEFT JOIN concept AS unit_c ON unit_c.concept_id = m.unit_concept_id
    AND unit_c.concept_id != 0
WHERE
    m.value_as_number IS NOT NULL;
```
Error:
```
Caused by: it.unibz.inf.ontop.exception.InvalidMappingSourceQueriesException: The placeholder(s) value in the target do(es) not occur in source query of the mapping assertion
[id: Observation.valueQuantity
target atom: triple(s, p, o) with s/RDF(http://hl7.org/fhir/mcode.ttl#Observation/{}/valueQuantity/value(TmpToNVARCHAR(measurement_id)),IRI), p/<file:///path/to/ont/fhir.ttl#v>, o/RDF(TmpToNVARCHAR(value),xsd:float)
source query: SELECT measurement_id, m.value_as_number [value], unit_c.concept_code unit, unit_c.concept_code code FROM measurement AS m LEFT JOIN concept AS unit_c ON unit_c.concept_id = m.unit_concept_id AND unit_c.concept_id != 0 WHERE m.value_as_number IS NOT NULL]
	at it.unibz.inf.ontop.spec.mapping.pp.impl.SQLPPMappingConverterImpl.convert(SQLPPMappingConverterImpl.java:130)
	at it.unibz.inf.ontop.spec.mapping.pp.impl.SQLPPMappingConverterImpl.convert(SQLPPMappingConverterImpl.java:83)
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convert(SQLMappingExtractor.java:248)
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convert(SQLMappingExtractor.java:219)
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convert(SQLMappingExtractor.java:188)
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convertPPMapping(SQLMappingExtractor.java:153)
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.extract(SQLMappingExtractor.java:108)
	at it.unibz.inf.ontop.spec.impl.DefaultOBDASpecificationExtractor.extract(DefaultOBDASpecificationExtractor.java:51)
	at it.unibz.inf.ontop.injection.impl.OntopMappingConfigurationImpl.loadSpecification(OntopMappingConfigurationImpl.java:130)
	at it.unibz.inf.ontop.injection.impl.OntopMappingSQLConfigurationImpl.loadSpecification(OntopMappingSQLConfigurationImpl.java:85)
	at it.unibz.inf.ontop.injection.impl.OntopMappingSQLAllConfigurationImpl.loadSpecification(OntopMappingSQLAllConfigurationImpl.java:47)
	at it.unibz.inf.ontop.injection.impl.OntopSQLOWLAPIConfigurationImpl.loadOBDASpecification(OntopSQLOWLAPIConfigurationImpl.java:35)
	at it.unibz.inf.ontop.injection.impl.OntopOBDAConfigurationImpl.loadSpecification(OntopOBDAConfigurationImpl.java:44)
	at it.unibz.inf.ontop.injection.OntopSystemConfiguration.loadQueryEngine(OntopSystemConfiguration.java:20)
	at it.unibz.inf.ontop.rdf4j.repository.impl.OntopVirtualRepository.initializeInternal(OntopVirtualRepository.java:72)
	... 41 more
Exception in thread "main" java.lang.AssertionError
	at it.unibz.inf.ontop.cli.Ontop.main(Ontop.java:30)
```

**Comment by kontchakov** [comment]
Could you please try the following version, with appropriate changes in the target atoms?

```
SELECT
    measurement_id,
    m.value_as_number AS val,
    unit_c.concept_code AS unit,
    unit_c.concept_code AS code
FROM
    measurement AS m
    LEFT JOIN concept AS unit_c ON unit_c.concept_id = m.unit_concept_id
    AND unit_c.concept_id != 0
```

Apart from the `AS` keywords, alias `value` is renamed to avoid any problems with keywords and the `WHERE` clause is removed because Ontop requires all columns to be non-nulls anyway (otherwise, the RDF triples might be undefined).

**Comment by jp3477** [comment]
Interesting, that worked for me. It seems like the necessity of the `AS` keywords is dependent on whether the JOIN is a LEFT or not.  I'm seeing this pattern:

| JOIN type | AS keyword included with variables | AS keyword omitted from variables |
| ------------- | ------------- | ------------- |
| JOIN | PASSES | PASSES  |
| LEFT JOIN | PASSES | FAILS |

So for some reason, `AS` can be omitted if `JOIN` is used (side note: I haven't tried adding the `INNER` keyword). But it becomes necessary if a `LEFT JOIN` is used (side note: I haven't tried `FULL OUTER JOIN` or `RIGHT JOIN` yet). Is this known behavior?

Also, do you have more documentation of how Ontop handles NULL values. I run into a ton of trouble with querying whenever a column happens to have a NULL value, I try to use OUTER joins, or even sometimes when I try to use the `COALESCE` function. I tend to get strange errors. This may be beyond the scope of this question, though, so I can always open up a new discussion elsewhere.

Thanks!

**Comment by kontchakov** [comment]
`JOIN`s and all `OUTER JOIN` in mappings are handled differently at the moment.

Ontop treats `NULL`s in the same way as R2RML - see [Generated RDF](https://www.w3.org/TR/r2rml/#generated-rdf); in particular Item 1 in Section 11.2.

**Comment by jp3477** [comment]
Thanks, I think that solves my issue then. I will work towards understanding the `NULL` handling better as well.
