### ISSUE TITLE
Ontop fails with an exception on materializing triples with boolean values

### ISSUE THREAD

**Issue by pulsar314** [ontop/ontop#826]
### Description

Ontop fails with an exception on materializing triples with boolean values: it.unibz.inf.ontop.query.resultset.impl.SQLOntopBindingSet$InvalidTermAsResultException: Term RDF(NULL,xsd:boolean) does not evaluate to a constant.

This error appears when working with AWS Redshift and SQL query contains conditional column like:

    @prefix :        <https://example.org/> .
    @prefix rr:      <http://www.w3.org/ns/r2rml#> .
    @prefix xsd:     <http://www.w3.org/2001/XMLSchema#> .

    [] rr:logicalTable [
        rr:sqlQuery """
          SELECT a.id, CASE WHEN b.test LIKE 'not%' THEN TRUE END AS negated
          FROM table_a a
          JOIN table_b b
            ON a.key = b.key
        """
      ] ;
      rr:subjectMap [
        rr:graph <https://example.org/> ;
        rr:class :Entity ;
        rr:template "https://example.org/entity/#{id}"
      ] ;
      rr:predicateObjectMap [
        rr:predicate :negated ;
        rr:objectMap [
          rr:datatype xsd:boolean ;
          rr:column "negated"
        ]
      ] .

Ontop transforms the query and moves conditional logic to postprocessing:

    CONSTRUCT [s, o, g] [s/RDF(https://example.org/entity/#(v0),IRI), g/<https://example.org/>, o/RDF(booleanLexicalNorm(IF_ELSE_NULL(IS_TRUE(v1),"true"^^BOOLEAN)),xsd:boolean)]
      NATIVE [v0, v1]
    SELECT DISTINCT v1."id" AS "v0", (v2."test" LIKE 'not%') AS "v1"
    FROM "table_a" v1, "table_b" v2
    WHERE v1."id" IS NOT NULL AND (v2."test" LIKE 'not%') AND v2."test" IS NOT NULL

Reformulated query returns records where all "v1" are equal `TRUE` (boolean, not string). It seems though that Redshift dialect in Ontop expects values to be strings "true" or "false", and actual results do not simplify to `TRUE` but return `NULL`. (Probably [here](https://github.com/ontop/ontop/blob/version5/core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/DefaultDBIfElseNullFunctionSymbol.java#L51-L63))

### Steps to Reproduce

I was not able to reproduce it outside a production database.

**Expected behavior:** `ontop materialize` produces triples when condition evaluates to true:

    <https://example.org/entity/#{id}> <https://example.org/negated> true .

**Actual behavior:** `ontop materialize` fails with exception.

**Reproduces how often:** Reproduces every time for the same table. Works for other similar but not exactly identical queries.

### Attached material

Configuration properties:

    jdbc.url = jdbc:redshift://redshift-host.com:5439/db
    jdbc.property.User = ****
    jdbc.property.Password = ****
    jdbc.property.AutoCreate = True
    jdbc.property.Region = us-east-1
    jdbc.property.ClusterID = cluster01
    jdbc.property.DbGroup = public
    jdbc.driver = com.amazon.redshift.jdbc42.Driver
    ontop.inferDefaultDatatype=false
    ontop.allowRetrievingBlackBoxViewMetadataFromDB=true
    ontop.queryLogging=true
    ontop.queryLogging.includeReformulatedQuery=true

Empty file is used as ontology (`-t` option).

Full stack trace:

    java.lang.RuntimeException: org.eclipse.rdf4j.query.QueryEvaluationException: it.unibz.inf.ontop.exception.OntopResultConversionException: it.unibz.inf.ontop.query.resultset.impl.SQLOntopBindingSet$InvalidTermAsResultException: Term RDF(NULL,xsd:boolean) does not evaluate to a constant
        at it.unibz.inf.ontop.cli.OntopMaterialize.runWithSingleFile(OntopMaterialize.java:136)
        at it.unibz.inf.ontop.cli.OntopMaterialize.run(OntopMaterialize.java:102)
        at it.unibz.inf.ontop.cli.Ontop.main(Ontop.java:19)
    Caused by: org.eclipse.rdf4j.query.QueryEvaluationException: it.unibz.inf.ontop.exception.OntopResultConversionException: it.unibz.inf.ontop.query.resultset.impl.SQLOntopBindingSet$InvalidTermAsResultException: Term RDF(NULL,xsd:boolean) does not evaluate to a constant
        at it.unibz.inf.ontop.rdf4j.materialization.impl.DefaultRDF4JMaterializer$GraphMaterializationIteration.next(DefaultRDF4JMaterializer.java:232)
        at it.unibz.inf.ontop.rdf4j.materialization.impl.DefaultRDF4JMaterializer$GraphMaterializationIteration.next(DefaultRDF4JMaterializer.java:201)
        at org.eclipse.rdf4j.common.iteration.IterationWrapper.next(IterationWrapper.java:88)
        at it.unibz.inf.ontop.cli.OntopMaterialize.serializeTripleBatch(OntopMaterialize.java:280)
        at it.unibz.inf.ontop.cli.OntopMaterialize.runWithSingleFile(OntopMaterialize.java:129)
        ... 2 more
    Caused by: it.unibz.inf.ontop.exception.OntopResultConversionException: it.unibz.inf.ontop.query.resultset.impl.SQLOntopBindingSet$InvalidTermAsResultException: Term RDF(NULL,xsd:boolean) does not evaluate to a constant
        at it.unibz.inf.ontop.query.resultset.impl.JDBCTupleResultSet.readCurrentRow(JDBCTupleResultSet.java:67)
        at it.unibz.inf.ontop.query.resultset.impl.JDBCTupleResultSet.readCurrentRow(JDBCTupleResultSet.java:20)
        at it.unibz.inf.ontop.query.resultset.impl.AbstractTupleResultSet.next(AbstractTupleResultSet.java:79)
        at it.unibz.inf.ontop.query.resultset.impl.AbstractTupleResultSet.next(AbstractTupleResultSet.java:18)
        at it.unibz.inf.ontop.materialization.impl.DefaultMaterializedGraphResultSet.next(DefaultMaterializedGraphResultSet.java:175)
        at it.unibz.inf.ontop.rdf4j.materialization.impl.DefaultRDF4JMaterializer$GraphMaterializationIteration.next(DefaultRDF4JMaterializer.java:230)
        ... 6 more
    Caused by: it.unibz.inf.ontop.query.resultset.impl.SQLOntopBindingSet$InvalidTermAsResultException: Term RDF(NULL,xsd:boolean) does not evaluate to a constant
        at it.unibz.inf.ontop.query.resultset.impl.JDBCTupleResultSet.evaluate(JDBCTupleResultSet.java:109)
        at it.unibz.inf.ontop.query.resultset.impl.JDBCTupleResultSet.getBinding(JDBCTupleResultSet.java:89)
        at it.unibz.inf.ontop.query.resultset.impl.JDBCTupleResultSet.lambda$computeBindingMap$1(JDBCTupleResultSet.java:80)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at it.unibz.inf.ontop.query.resultset.impl.JDBCTupleResultSet.computeBindingMap(JDBCTupleResultSet.java:83)
        at it.unibz.inf.ontop.query.resultset.impl.JDBCTupleResultSet.readCurrentRow(JDBCTupleResultSet.java:64)
        ... 11 more
    Exception in thread "main" java.lang.AssertionError
        at it.unibz.inf.ontop.cli.Ontop.main(Ontop.java:31)

### Versions

Redshift JDBC: redshift-jdbc42-2.1.0.30
Ontop: ontop version 5.2.0

### Additional Information

There is a workaround which helps to produce correct output, but it seems not reliable:

    NULLIF(
      CASE b.test LIKE 'not%'
        WHEN TRUE THEN 'true'
        ELSE 'false'
      END
      , 'false'
    ) AS negated

**Comment by bcogrel** [comment]
Thanks for reporting the issue.

I gave a quick try with the serverless version of Redshift and I didn't manage to reproduce the issue. I hope there is no tricky differences between the provisioned and the serverless versions.

Let me give it a deeper look.
