### ISSUE TITLE
Ontop Protege plugin throws error when loading ontologies from URLs

### ISSUE THREAD

**Issue by rsgoncalves** [ontop/ontop#94]
For example, loading http://protege.cim3.net/file/pub/ontologies/koala/koala.owl in Protege (5 beta 23, using Java 1.8.0_74) from the URL results in an error dialog containing:

An exception has occurred when loading input file.
Message: URI scheme is not "file"

Debugging information (for the authors)

	at org.semanticweb.ontop.protege.core.OBDAModelManager$OBDAPluginOWLModelManagerListener.handleOntologyLoadedAndReLoaded(OBDAModelManager.java:579)
	at org.semanticweb.ontop.protege.core.OBDAModelManager$OBDAPluginOWLModelManagerListener.handleChange(OBDAModelManager.java:453)
	at org.protege.editor.owl.model.OWLModelManagerImpl.fireEvent(OWLModelManagerImpl.java:791)
	at org.protege.editor.owl.model.OWLModelManagerImpl.loadOntologyFromPhysicalURI(OWLModelManagerImpl.java:280)
	at org.protege.editor.owl.OWLEditorKit.handleLoadFrom(OWLEditorKit.java:201)
	at org.protege.editor.core.ProtegeManager.loadAndSetupEditorKitFromURI(ProtegeManager.java:241)
	at org.protege.editor.owl.ui.action.OpenFromURLAction.openInNewWorkspace(OpenFromURLAction.java:56)
	at org.protege.editor.core.ui.util.UIUtil.openRequest(UIUtil.java:210)
	at org.protege.editor.owl.ui.action.OpenFromURLAction.actionPerformed(OpenFromURLAction.java:25)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)
	at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
	at java.awt.MenuItem.processEvent(MenuItem.java:628)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

And the message ``URI scheme is not "file" `` is printed to the console.

**Comment by ghxiao** [comment]
Hi, this is a known limitation of Ontop plugin. Ontop can only open files from disk. The reason is that Ontop will generate other files (.obda and .q) in the same directory. For http protocol, such directory is not writable. 

To solve the issue, you can download the file to local disk and open it.
