### ISSUE TITLE
Ontop Protege plugin throws warning/exception when loading ontology from file

### ISSUE THREAD

**Issue by rsgoncalves** [ontop/ontop#95]
Unfortunately I couldn't reproduced this anymore, it happened when loading the ontology at https://curate.nd.edu/concern/generic_files/9p29086355b from the file system.

    BADLY BEHAVING LISTENER: Optional.get() cannot be called on an absent value has been removed 
    java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
    	at com.google.common.base.Absent.get(Absent.java:47) ~[guava.jar:na]
    	at org.semanticweb.ontop.protege.core.OBDAModelManager$OntologyRefactoringListener.ontologiesChanged(OBDAModelManager.java:146) ~[na:na]
    	at org.semanticweb.owlapi.model.DefaultChangeBroadcastStrategy.broadcastChanges(DefaultChangeBroadcastStrategy.java:38) ~[owlapi-osgidistribution.jar:4.1.3.20151118-2017]
    	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.broadcastChanges(OWLOntologyManagerImpl.java:1443) [owlapi-osgidistribution.jar:4.1.3.20151118-2017]
    	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.applyChanges(OWLOntologyManagerImpl.java:605) [owlapi-osgidistribution.jar:4.1.3.20151118-2017]
    	at org.protege.owl.server.util.ClientUtilities.loadOntology(ClientUtilities.java:70) [protege-server-3.0.0-SNAPSHOT.jar:na]
    	at org.protege.owl.server.util.ClientUtilities.loadOntology(ClientUtilities.java:62) [protege-server-3.0.0-SNAPSHOT.jar:na]
    	at org.protege.editor.owl.client.panel.OpenFromServerDialog.openOntologyDocument(OpenFromServerDialog.java:305) [protege-client-3.0.0-SNAPSHOT.jar:na]
    	at org.protege.editor.owl.client.panel.OpenFromServerDialog$1.mouseClicked(OpenFromServerDialog.java:190) [protege-client-3.0.0-SNAPSHOT.jar:na]
    	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270) [na:1.8.0_74]
    	at java.awt.Component.processMouseEvent(Component.java:6538) [na:1.8.0_74]
    	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) [na:1.8.0_74]
    	at java.awt.Component.processEvent(Component.java:6300) [na:1.8.0_74]
    	at java.awt.Container.processEvent(Container.java:2236) [na:1.8.0_74]
    	at java.awt.Component.dispatchEventImpl(Component.java:4891) [na:1.8.0_74]
    	at java.awt.Container.dispatchEventImpl(Container.java:2294) [na:1.8.0_74]
    	at java.awt.Component.dispatchEvent(Component.java:4713) [na:1.8.0_74]
    	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) [na:1.8.0_74]
    	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534) [na:1.8.0_74]
    	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) [na:1.8.0_74]
    	at java.awt.Container.dispatchEventImpl(Container.java:2280) [na:1.8.0_74]
    	at java.awt.Window.dispatchEventImpl(Window.java:2750) [na:1.8.0_74]
    	at java.awt.Component.dispatchEvent(Component.java:4713) [na:1.8.0_74]
    	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [na:1.8.0_74]
    	at java.awt.EventQueue.access$500(EventQueue.java:97) [na:1.8.0_74]
    	at java.awt.EventQueue$3.run(EventQueue.java:709) [na:1.8.0_74]
    	at java.awt.EventQueue$3.run(EventQueue.java:703) [na:1.8.0_74]
    	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_74]
    	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [na:1.8.0_74]
    	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) [na:1.8.0_74]
    	at java.awt.EventQueue$4.run(EventQueue.java:731) [na:1.8.0_74]
    	at java.awt.EventQueue$4.run(EventQueue.java:729) [na:1.8.0_74]
    	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_74]
    	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [na:1.8.0_74]
    	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [na:1.8.0_74]
    	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_74]
    	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_74]
    	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109) [na:1.8.0_74]
    	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184) [na:1.8.0_74]
    	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229) [na:1.8.0_74]
    	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227) [na:1.8.0_74]
    	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_74]
    	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227) [na:1.8.0_74]
    	at java.awt.Dialog.show(Dialog.java:1084) [na:1.8.0_74]
    	at java.awt.Component.show(Component.java:1673) [na:1.8.0_74]
    	at java.awt.Component.setVisible(Component.java:1625) [na:1.8.0_74]
    	at java.awt.Window.setVisible(Window.java:1014) [na:1.8.0_74]
    	at java.awt.Dialog.setVisible(Dialog.java:1005) [na:1.8.0_74]
    	at org.protege.editor.owl.client.action.OpenFromServerAction.actionPerformed(OpenFromServerAction.java:24) [protege-client-3.0.0-SNAPSHOT.jar:na]
    	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) [na:1.8.0_74]
    	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) [na:1.8.0_74]
    	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) [na:1.8.0_74]
    	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) [na:1.8.0_74]
    	at javax.swing.AbstractButton.doClick(AbstractButton.java:376) [na:1.8.0_74]
    	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125) [na:1.8.0_74]
    	at java.awt.MenuItem.processActionEvent(MenuItem.java:669) [na:1.8.0_74]
    	at java.awt.MenuItem.processEvent(MenuItem.java:628) [na:1.8.0_74]
    	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351) [na:1.8.0_74]
    	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339) [na:1.8.0_74]
    	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761) [na:1.8.0_74]
    	at java.awt.EventQueue.access$500(EventQueue.java:97) [na:1.8.0_74]
    	at java.awt.EventQueue$3.run(EventQueue.java:709) [na:1.8.0_74]
    	at java.awt.EventQueue$3.run(EventQueue.java:703) [na:1.8.0_74]
    	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_74]
    	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [na:1.8.0_74]
    	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) [na:1.8.0_74]
    	at java.awt.EventQueue$4.run(EventQueue.java:731) [na:1.8.0_74]
    	at java.awt.EventQueue$4.run(EventQueue.java:729) [na:1.8.0_74]
    	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_74]
    	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [na:1.8.0_74]
    	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [na:1.8.0_74]
    	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_74]
    	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_74]
    	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_74]
    	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_74]
    	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_74]
    	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_74]

In another occasion, loading another ontology from file, I got the following:

    ------------------------------- Loading Ontology ------------------------------- 
    Loading ontology from file:/Users/me/Documents/ontologies/random/protege-v5-example.owl 
    Loading OntologyID(Anonymous-10) from file:/Users/me/Documents/ontologies/random/protege-v5-example.owl 
    dumping remaining triples 
    done dumping remaining triples 
    Exception thrown by listener: org.semanticweb.ontop.protege.core.OBDAModelManager$OBDAPluginOWLModelManagerListener.  Detatching bad listener. 
    Loading for ontology and imports closure successfully completed in 11 ms

**Comment by ghxiao** [comment]
Hi I am not able produce your problem when opening your files. Could you try again?
