### ISSUE TITLE
ontop-cli to-r2rml option

### ISSUE THREAD

**Issue by tirrolo** [ontop/ontop#97]
Hi,

I cannot translate obda mappings compliant with the syntax for ontop 1.17 (i.e., <{uri}>) into r2rml. I get the following error:

./ontop mapping to-r2rml -i onto/postgres/1.17/npd-v2-ql-postgres-ontop1.17.obda 
15:02:10.137 |-DEBUG in i.u.k.obda.model.impl.OBDAModelImpl - OBDA model is initialized!
15:02:10.145 |-DEBUG in i.u.k.obda.model.impl.OBDAModelImpl - OBDA model is reset
java.lang.ArrayIndexOutOfBoundsException: 0
	at it.unibz.krdb.obda.utils.URITemplates.getUriTemplateString(URITemplates.java:118)
	at it.unibz.krdb.obda.utils.URITemplates.getUriTemplateString(URITemplates.java:136)
	at it.unibz.krdb.obda.r2rml.OBDAMappingTransformer.getTriplesMap(OBDAMappingTransformer.java:371)
	at it.unibz.krdb.obda.r2rml.R2RMLWriter.getTriplesMaps(R2RMLWriter.java:113)
	at it.unibz.krdb.obda.r2rml.R2RMLWriter.write(R2RMLWriter.java:142)
	at org.semanticweb.ontop.cli.OntopOBDAToR2RML.run(OntopOBDAToR2RML.java:97)
	at org.semanticweb.ontop.cli.Ontop.main(Ontop.java:21)
java.lang.ArrayIndexOutOfBoundsException: 0
	at it.unibz.krdb.obda.utils.URITemplates.getUriTemplateString(URITemplates.java:118)
	at it.unibz.krdb.obda.utils.URITemplates.getUriTemplateString(URITemplates.java:136)
	at it.unibz.krdb.obda.r2rml.OBDAMappingTransformer.getTriplesMap(OBDAMappingTransformer.java:371)
	at it.unibz.krdb.obda.r2rml.R2RMLWriter.getTriplesMaps(R2RMLWriter.java:113)
	at it.unibz.krdb.obda.r2rml.R2RMLWriter.write(R2RMLWriter.java:142)
	at org.semanticweb.ontop.cli.OntopOBDAToR2RML.run(OntopOBDAToR2RML.java:97)
	at org.semanticweb.ontop.cli.Ontop.main(Ontop.java:21)
15:02:14.413 |-DEBUG in o.a.j.riot.stream.JenaIOEnvironment - Failed to find configuration: location-mapping.ttl;location-mapping.rdf;location-mapping.n3;etc/location-mapping.rdf;etc/location-mapping.n3;etc/location-mapping.ttl
R2RML mapping file onto/postgres/1.17/npd-v2-ql-postgres-ontop1.17.ttl written!

[npd-v2-ql-mysql-ontop1.17.obda.txt](https://github.com/ontop/ontop/files/142959/npd-v2-ql-mysql-ontop1.17.obda.txt)

**Comment by ghxiao** [comment]
The issue comes from that the behavior of `String.split()` method is not reliable [1].

I am reimplementing the `getUriTemplateString()` method using guava Splitter now.

[1] https://github.com/google/guava/wiki/StringsExplained#splitter

**Comment by ghxiao** [comment]
Fixed in commit 775c77a3c8a7459f22f73841f893b5c108ab298a
